### ISSUE TITLE
shell autocomplete generator

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-node#1013]
It would be nice if `neofs-cli` could generate autocomplete file for different shells.

Something like https://gohugo.io/commands/hugo_gen_autocomplete/

**Comment by alexvanin** [comment]
Need to double check this: https://github.com/nspcc-dev/neofs-node/blob/master/cmd/neofs-cli/modules/completion.go

**Comment by carpawell** [comment]
Also, for `neofs-adm`, I think.

**Comment by alexvanin** [comment]
Autocomplete works fine in Linux/Bash.
```
$ source <(neofs-cli completion bash)
```

Make sure, that `neofs-cli` is available in `$PATH`.
