### ISSUE TITLE
IsActive() status when main chain disabled

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1025]
During the tests I had a situation when main chain was disabled, but alphabet node still consideres non active (IsActive() returns false). Not sure if this is correct behavior. Unfortunately it is quite hard to keep track of such things when you have so many running modes.

**Comment by cthulhu-rider** [comment]
@alexvanin the problem occurs when we disable mainchain in config `without_mainnet`. In this case `IsActive` status is calculated from the result of calling the `InnerRingList` method of `Netmap` contract. In dev env it returns empty list.

**Comment by alexvanin** [comment]
`Netmap` contract should be used as the source of the Inner Ring nodes when notary is disabled. I propose to fix that and fetch Inner Ring list from `RoleManagement` contract in this case. What do you think about that?
