### ISSUE TITLE
Reconsider object size split in blobovnicza instance

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1029]
BoltDB instance of blobovnicza is split into multiple buckets that arrange objects per object size. All objects with the size of < 32 KiB goes into one bucket, less than 64KiB in another, etc.

This approach is not optimal because it does not split objects between buckets uniformly. There might be single stream of objects with constant size and blobovnicza's will store such objects in the same bucket. This leads to massive under performance. 

![image](https://user-images.githubusercontent.com/6323066/145406163-7ab38a5e-e837-4b5a-b8f6-4398762c5f84.png)

Instead we can split objects based on their object ID between the buckets. This provides better object distribution and better BoltDB performance.

**Comment by carpawell** [comment]
### What I did

I used raw [blobovnicza](https://github.com/nspcc-dev/neofs-node/blob/v0.27.0/pkg/local_object_storage/blobovnicza/blobovnicza.go#L15) instance and tried to put 1Kib objects using 1000 active goroutines. One test - one new blobovnicza.

#### Old approach
![old](https://user-images.githubusercontent.com/24619368/146405296-cf9c2442-08fd-4f70-9ac3-d5a81598f5cd.png)

Just to make sure that I have similar results on my machine with my test.

#### New approach
I used the first byte of `oid` as bucket ID, so blobovnicza is supposed to have 255 buckets and object distribution should be kinda random and should not be concentrated in one of the buckets. Despite the above, it did not help at all and, moreover, put time of one object has been increased a little (because of too many buckets I guess).

![new](https://user-images.githubusercontent.com/24619368/146406917-6b1be4e7-143d-47a0-aa87-4a6799878599.png)



It seems that object distribution did not affect put time as dramatically as it was thought. But such a new approach can help with `Get` and `Delete` operations due to the fact that the object address can always say its bucket name and prevents from iterating all buckets.

Will investigate object distribution and double-check testing and relation between results.

**Comment by alexvanin** [comment]
> I used the first byte of oid

Can you try with two and four byte offset? I remember that I had some issues with one byte offset. 

And double check that buckets are different (maybe a bit of logs in the beginning or bucket stats in the end). I got some false positive results when all objects were with the same address.

**Comment by carpawell** [comment]
I repeated the same test on the server machine and got results:

### Old approach
![old_vegman](https://user-images.githubusercontent.com/24619368/147608040-30a2c04c-3ecf-4011-9e5e-6875b0b5f6e0.png)

And some bucket statistics (for the last 2M object blobovnicza): 
```
Aggregate statistics for 6 buckets

Page count statistics
	Number of logical branch pages: 15127
	Number of physical branch overflow pages: 0
	Number of logical leaf pages: 685418
	Number of physical leaf overflow pages: 171788
Tree statistics
	Number of keys/value pairs: 2000000
	Number of levels in B+tree: 5
Page size utilization
	Bytes allocated for physical branch pages: 61960192
	Bytes actually used for branch data: 42936802 (69%)
	Bytes allocated for physical leaf pages: 3511115776
	Bytes actually used for leaf data: 2180856265 (62%)
Bucket statistics
	Total number of buckets: 6
	Total number on inlined buckets: 5 (83%)
	Bytes used for inlined buckets: 80 (0%)
	Min number of objects in bucket: 0
	Max number of objects in bucket: 2000000
```

### New approach (1 byte as bucket key)
![new_vegman](https://user-images.githubusercontent.com/24619368/147608203-3938abfa-9133-4535-853a-7628545162e5.png)

And some bucket statistics (for the last 2M object blobovnicza): 
```
Aggregate statistics for 256 buckets

Page count statistics
	Number of logical branch pages: 15876
	Number of physical branch overflow pages: 0
	Number of logical leaf pages: 685564
	Number of physical leaf overflow pages: 171651
Tree statistics
	Number of keys/value pairs: 2000000
	Number of levels in B+tree: 3
Page size utilization
	Bytes allocated for physical branch pages: 65028096
	Bytes actually used for branch data: 42987557 (66%)
	Bytes allocated for physical leaf pages: 3511152640
	Bytes actually used for leaf data: 2180858601 (62%)
Bucket statistics
	Total number of buckets: 256
	Total number on inlined buckets: 0 (0%)
	Bytes used for inlined buckets: 0 (0%)
	Min number of objects in bucket: 7567
	Max number of objects in bucket: 8069
```

### New approach (2 bytes as bucket key)
![new_2_bytes](https://user-images.githubusercontent.com/24619368/147608295-7f46b4de-e3d7-4184-bfca-93dad15d0ec8.png)\

And some bucket statistics (for the last 2M object blobovnicza): 
```
Aggregate statistics for 65536 buckets

Page count statistics
	Number of logical branch pages: 65536
	Number of physical branch overflow pages: 0
	Number of logical leaf pages: 683256
	Number of physical leaf overflow pages: 172649
Tree statistics
	Number of keys/value pairs: 2000000
	Number of levels in B+tree: 2
Page size utilization
	Bytes allocated for physical branch pages: 268435456
	Bytes actually used for branch data: 42689482 (15%)
	Bytes allocated for physical leaf pages: 3505786880
	Bytes actually used for leaf data: 2180821673 (62%)
Bucket statistics
	Total number of buckets: 65536
	Total number on inlined buckets: 0 (0%)
	Bytes used for inlined buckets: 0 (0%)
	Min number of objects in bucket: 12
	Max number of objects in bucket: 54
```


It seems that object distribution is ok. Moreover, the results are almost the same and do not show degradation at all (even when using the old approach).
Test with 4 bytes as bucket key did now succeed at all: I waited for ~1h to see any difference in db file but its size was not changing. I guess it is hard for the bolt to handle 4294967295 buckets OR its initialization (blobovnicza creates all possible buckets on `Init` call) takes that much time, anyway, I think this is not smth that we want to implement, so did not investigate that case deep.

**Comment by carpawell** [comment]
After such "the same" results I decided to increase object number and tested from 1M to 20M objects (3M step, 20M blobovnicza = ~34GB)

### Old approach
![old_20M](https://user-images.githubusercontent.com/24619368/147609065-4d69570f-56a3-487d-9303-d3669d002ebe.png)

And some bucket statistics (for the last 20M object blobovnicza):
```
Aggregate statistics for 6 buckets

Page count statistics
	Number of logical branch pages: 152231
	Number of physical branch overflow pages: 0
	Number of logical leaf pages: 6857892
	Number of physical leaf overflow pages: 1715597
Tree statistics
	Number of keys/value pairs: 20000000
	Number of levels in B+tree: 5
Page size utilization
	Bytes allocated for physical branch pages: 623538176
	Bytes actually used for branch data: 429666501 (68%)
	Bytes allocated for physical leaf pages: 35117010944
	Bytes actually used for leaf data: 21808623305 (62%)
Bucket statistics
	Total number of buckets: 6
	Total number on inlined buckets: 5 (83%)
	Bytes used for inlined buckets: 80 (0%)
	Min number of objects in bucket: 0
	Max number of objects in bucket: 20000000
```

### New approach (1 byte as bucket key)

![new_20M](https://user-images.githubusercontent.com/24619368/147609157-12c0f3de-75d6-4392-a155-3ff5b8053242.png)

And some bucket statistics (for the last 20M object blobovnicza):
```
Aggregate statistics for 256 buckets

Page count statistics
	Number of logical branch pages: 149165
	Number of physical branch overflow pages: 0
	Number of logical leaf pages: 6857735
	Number of physical leaf overflow pages: 1715066
Tree statistics
	Number of keys/value pairs: 20000000
	Number of levels in B+tree: 4
Page size utilization
	Bytes allocated for physical branch pages: 610979840
	Bytes actually used for branch data: 429405689 (70%)
	Bytes allocated for physical leaf pages: 35114192896
	Bytes actually used for leaf data: 21808620793 (62%)
Bucket statistics
	Total number of buckets: 256
	Total number on inlined buckets: 0 (0%)
	Bytes used for inlined buckets: 0 (0%)
	Min number of objects in bucket: 77528
	Max number of objects in bucket: 78850
```

### New approach (2 bytes as bucket key)
![new_2_byte_20M](https://user-images.githubusercontent.com/24619368/147609214-941472d1-01fd-4a7b-bfda-f1767087b22b.png)

```
Aggregate statistics for 65536 buckets

Page count statistics
	Number of logical branch pages: 196815
	Number of physical branch overflow pages: 0
	Number of logical leaf pages: 6855482
	Number of physical leaf overflow pages: 1715198
Tree statistics
	Number of keys/value pairs: 20000000
	Number of levels in B+tree: 3
Page size utilization
	Bytes allocated for physical branch pages: 806154240
	Bytes actually used for branch data: 428956272 (53%)
	Bytes allocated for physical leaf pages: 35105505280
	Bytes actually used for leaf data: 21808584745 (62%)
Bucket statistics
	Total number of buckets: 65536
	Total number on inlined buckets: 0 (0%)
	Bytes used for inlined buckets: 0 (0%)
	Min number of objects in bucket: 236
	Max number of objects in bucket: 384
```

Still, the results are almost the same and no degradation.

**Comment by alexvanin** [comment]
Thanks for the contribution!

**Comment by carpawell** [comment]
Test [code](https://gist.github.com/carpawell/9f5f1a96afb0cb15609e60099c0febb2) and [util](https://gist.github.com/carpawell/7a0d64e2e8a326550e8a100faa895b5a) that prints bucket statistics.
