### ISSUE TITLE
Define blobovniza tree width and height automatically

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1030]
We should determine optimal size of single blobovnicza (at what side it is fast enough to store new objects, take into consideration #1029)

After that, instead of width and depth, neofs-node should take approximate size of whole blobovnicza tree from storage node config. Based on this information, app should build the tree with width and depth, so the total size of the tree will be `optimal_blobovniza_size*width^(depth+1)`.

**Comment by roman-khimov** [comment]
Obsoleted by #2453.
