### ISSUE TITLE
Tombstone deleting

### ISSUE THREAD

**Issue by ZhangTao1596** [nspcc-dev/neofs-node#1051]
## Is your feature request related to a problem? Please describe.
Currently user can delete tombstone which makes node create another tombstone.

## Describe the solution you'd like
Prevent user delete tombstone.

**Comment by alexvanin** [comment]
1. Restriction of `object.Delete` invocation on tombstone objects does not prevent users from creating tombstones for a tombstone manually with `object.Put`.

2. Tombstone object is still an object and this creates one more corner case when object does not behave like an object, you can't delete it. It makes API behavior a bit less predictable, which is not so good.

3. Removing a tombstone can be used for roll-backs and data restoration in case of accidental removals. It is not implemented now, but it can be done with a bit of tuning of the tombstone lifecycle and GC.

**Comment by alexvanin** [comment]
Closing, according comment above. Reopen or link this issue in case of related issues or proposals.
