### ISSUE TITLE
Status can't cover errors during acl check

### ISSUE THREAD

**Issue by ZhangTao1596** [nspcc-dev/neofs-node#1062]
I think this is because acl checker is outside of sign service.
## Expected Behavior
Status in response can carry errors during acl check. For example, `container not found` error.

## Current Behavior
Still return error like before

## Steps to Reproduce (for bugs)
`Get` a object whoes container id is inexistent.

BTW, Why we need status in response? We can throw exception with [StatusCode](https://grpc.github.io/grpc/csharp/api/Grpc.Core.StatusCode.html) in c# and return error in golang as we do before.
Now we need to check both response and exception(error).

**Comment by alexvanin** [comment]
> BTW, Why we need status in response? We can throw exception with StatusCode in c# and return error in golang as we do before.

For two reasons:
1. To separate transport level issues from NeoFS related errors. You can think of it as HTTP response codes: if there are no transport layer issues (TCP), you will get response message from the server, but it can be either success (200) or failure (300\400\500).

2. To negotiate protocol version between client and server. To do that client needs to get version field from `ResponseMetaHeader`. If client's version is not supported by the server, it throws errors which omits whole response message. With status codes, server will return `ResponseMetaHeader` so the client can negotiate protocol version after failure.

> Now we need to check both response and exception(error).

It is true, but we believe that this "double work" should be done only in client packages like `neofs-sdk-go/client` or c# client. These packages should both check gRPC error and stauts code and throw single error message like it was done before (see https://github.com/nspcc-dev/neofs-sdk-go/issues/91).

**Comment by ZhangTao1596** [comment]
> It is true, but we believe that this "double work" should be done only in client packages like `neofs-sdk-go/client` or c# client. These packages should both check gRPC error and stauts code and throw single error message like it was done before (see [nspcc-dev/neofs-sdk-go#91](https://github.com/nspcc-dev/neofs-sdk-go/issues/91)).

`neofs-api-csharp/client` is updated as this.
