### ISSUE TITLE
Object clean after container deleted

### ISSUE THREAD

**Issue by ZhangTao1596** [nspcc-dev/neofs-node#1070]
## Is your feature request related to a problem? Please describe.
Now objects still exist in storage node after container is deleted. These objects still occupy storage quota and cause errors in replication and used space services.

## Describe the solution you'd like
Storage node subcribe container delete event and clean objects when the event occurs.

**Comment by alexvanin** [comment]
Need to double check that policer removes objects from removed container (error during container fetch operation).

**Comment by realloc** [comment]
In the initial design, when container is deleted, the objects stored on the node must be considered invalid and removed by GC. Making a mass object delete for each container removal event may be extremely expensive operation, especially compared to am asynchronous GC cleanup.

**Comment by alexvanin** [comment]
Indeed, policer checks if container exists and marks object as inhumed (removed)
https://github.com/nspcc-dev/neofs-node/blob/58d90eec7db5c1abd4bd359725f76dc97bd003a2/pkg/services/policer/check.go#L18-L27

After https://github.com/nspcc-dev/neofs-node/pull/965 policer checks object all the time, so sooner or later objects of removed container will be removed from storage.

**Comment by ZhangTao1596** [comment]
I'm closing this.
