### ISSUE TITLE
unknown rpc-endpoint to get address balance / transfer NEP-17 tokens in N3 mainnet

### ISSUE THREAD

**Issue by jisnardo** [nspcc-dev/neofs-node#1075]
What is the rpc-endpoint to get address balance / transfer NEP-17 tokens in N3 mainnet?

```
neo-go wallet nep17 balance --help

NAME:
   neo-go wallet nep17 balance - get address balance

USAGE:
   balance --wallet <path> --rpc-endpoint <node> [--timeout <time>] [--address <address>] [--token <hash-or-name>]

OPTIONS:
   --wallet value, -w value        Target location of the wallet file.
   --token value                   Token to use (hash or name (for NEO/GAS or imported tokens))
   --address value, -a value       Address to use
   --rpc-endpoint value, -r value  RPC node address
   --timeout value, -s value       Timeout for the operation (10 seconds by default) (default: 0s)
```

Like this in testnet:

https://github.com/nspcc-dev/neofs-node/blob/master/config/testnet/README.md#deposit

```
neo-go wallet nep17 balance -w wallet.json -r https://rpc01.testnet.n3.nspcc.ru:21331

Account NXxRAFPqPstaPByndKMHuC8iGcaHgtRY3m
GAS: GasToken (d2a4cff31913016155e38e474a2c06d08be276cf)
    Amount : 48.98376551
    Updated: 902527
NEO: NeoToken (ef4073a0f2b305a38ec4050e4d3d28bc40ea63f5)
    Amount : 50
    Updated: 902426
```

```
neo-go wallet nep17 transfer -w wallet.json -r https://rpc01.testnet.n3.nspcc.ru:21331 \
--from NXxRAFPqPstaPByndKMHuC8iGcaHgtRY3m \
--to NadZ8YfvkddivcFFkztZgfwxZyKf1acpRF \
--token GAS \
--amount 1
```

No info for mainet:

https://github.com/nspcc-dev/neofs-node/blob/master/config/mainnet/README.md

Thanks in advance.

**Comment by jisnardo** [comment]
@alexvanin @anatoly-bogatyrev any suggestion to find this essential info? Thanks in advance.

**Comment by alexvanin** [comment]
We are preparing doc site with guides, manuals and other useful information. 
Try to use endpoints from there: https://testcdn.fs.neo.org/doc/integrations/endpoints/

**Comment by jisnardo** [comment]
Those endopints does not show the real balance of the wallet.

**Example on N3 Testnet**

After claim to the faucet.

```
neo-go wallet nep17 balance -r https://rpc01.testnet.n3.nspcc.ru:21331 -w wallet.json 
Account xxx
NEO: NeoToken (ef4073a0f2b305a38ec4050e4d3d28bc40ea63f5)
    Amount : 50
    Updated: 902426
GAS: GasToken (d2a4cff31913016155e38e474a2c06d08be276cf)
    Amount : 50
    Updated: 902426
```

```
neo-go wallet nep17 balance -r https://rpc01.morph.testnet.fs.neo.org:51331 -w wallet.json 
Account xxx
```

This works **https://rpc01.testnet.n3.nspcc.ru:21331** this does not works **https://rpc0x.morph.testnet.fs.neo.org:51331**

**The same on N3 Mainnet**

Real balance displayed for example with **Neon Wallet**, but unexpected balance appears with **https://rpcx.morph.fs.neo.org:40341**

**Comment by alexvanin** [comment]
Oups, misunderstood your issue. So you asking about N3 Testnet and N3 Mainnet RPC endpoints. Those endpoints can be found in network monitors like dora: https://dora.coz.io/monitor. Pick `Neo N3 (Mainnet)` or `Neo N3 (Testnet)` in the top right corner and try any endpoint.

At NSPCC we also maintain N3 Mainnet RPC node available at `https://rpc10.n3.nspcc.ru:10331`

**Comment by jisnardo** [comment]
Thanks @alexvanin, https://dora.coz.io/ was what I have found. I expected the N3 Mainnet RPC node address from NSPCC **https://rpc10.n3.nspcc.ru:10331** at https://github.com/nspcc-dev/neofs-node/blob/master/config/mainnet/README.md like **https://rpc01.testnet.n3.nspcc.ru:21331** for https://github.com/nspcc-dev/neofs-node/blob/master/config/testnet/README.md
Thanks for all.

**Comment by dusmart** [comment]
> Oups, misunderstood your issue. So you asking about N3 Testnet and N3 Mainnet RPC endpoints. Those endpoints can be found in network monitors like dora: https://dora.coz.io/monitor. Pick `Neo N3 (Mainnet)` or `Neo N3 (Testnet)` in the top right corner and try any endpoint.
> 
> At NSPCC we also maintain N3 Mainnet RPC node available at `https://rpc10.n3.nspcc.ru:10331`

Is there any N3 Testnet RPC node available? I cannot find any from dora.coz.io.

**Comment by roman-khimov** [comment]
https://status.fs.neo.org/
https://rpc.t5.n3.nspcc.ru:20331
