### ISSUE TITLE
Tombstone split

### ISSUE THREAD

**Issue by ZhangTao1596** [nspcc-dev/neofs-node#1080]
## Is your feature request related to a problem? Please describe.
We find this problem when testing with different `MaxObjectSize` from small to big and split object. There will be a error if we put a tombstone exceeding `MaxObjectSize`. Because we can't parse it from one object payload if the tomestone is splited.
https://github.com/nspcc-dev/neofs-node/blob/0b0c61f4a51c8ccad34f6480ab9c92036532889a/pkg/core/object/fmt.go#L151

This prevents us from deleting a parent object whose children list is greater than `MaxObjectSize` limit.

**Comment by alexvanin** [comment]
> This prevents us from deleting a parent object whose children list is greater than MaxObjectSize limit.

I think it is known limitation. If tombstone object is going to be split, then payload should be properly aligned to contain list of addresses in tombstone children or storage nodes garbage collector should perform some extra network requests to gather original tombstone object.

On the other hand, `MaxObjectSize` expected to be tens of megabytes (maybe hundred in some environments), it can store _many_ children. For example, in the public N3 network  we have `MaxObjectSize` of 64 MiB. With 100 byte address, it can store roughly about 6.4 million children. 6.4 million x 64 MiB ~ 50 petabytes. Don't think we ever gonna store an object that big.

/cc @realloc @cthulhu-rider

**Comment by realloc** [comment]
According to the [API spec](https://github.com/nspcc-dev/neofs-api/blob/master/object/types.proto#L12), the tombstone object must never be split.

**Comment by ZhangTao1596** [comment]
I add object type check when split object https://github.com/neo-ngd/neo-plugins/commit/06d2504ca325ca52d8362fc12e7093ccdeabda6d.
I'm ok with this if `MaxObjectSize` is always big enough.
