### ISSUE TITLE
Confusing `neofs-cli` config file usage

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1083]
1. Add some warning words when using flags from config file (in verbose mode or even in general). It may lead to mistakes when a user uses flags that he did not mention in the command line, especially when config is read from the default path and has not been placed with `-c` flag.
2. Do something with a confusing situation when config file says to use `binary-key` and user uses `-w` flag (config file's key would be used since it is parsed firstly in `neofs-cli` and no warning would be printed).

**Comment by carpawell** [comment]
IMO trying to read config file from some _default_ path should be dropped.

**Comment by alexvanin** [comment]
Let's try to use single flag for everything:
```
--wallet [wallet-path]
--wallet [WIF]
--wallet [binary-key]
```

This will fix issue (2). Verbose flag still may print what wallet (or wallet address) has been used.

**Comment by fyrchik** [comment]
Related #610.

**Comment by carpawell** [comment]
is `wallet` a good name for such a flag?

**Comment by alexvanin** [comment]
I think yes, because  NEP-6 compatible JSON Wallet is a preferred way to specify credentials, unless user knows what he is doing with his WIF or binary private key.

**Comment by carpawell** [comment]
How about `1.` of the issue?

**Comment by alexvanin** [comment]
> How about 1. of the issue?

The core of the problem is gone with single credential key. But I don't mind to mention if the default config file is used in verbose mode. Can you do that @carpawell ? If so, reopen the issue.
