### ISSUE TITLE
Storage node configurator for N3 networks

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1090]
Storage node configuration for public networks might not be an easy task which requires deposit on main chain, correct LOCODE input, correct announcement address (see https://github.com/nspcc-dev/neofs-node/issues/923), etc.

While hardcore engineers can tune configuration manually by reading [config example](https://github.com/nspcc-dev/neofs-node/blob/master/config/example/node.yaml) and find correct contract address for deposit in [docs](https://testcdn.fs.neo.org/doc/integrations/endpoints/), I believe there should be simple way to configure minimal viable config for public networks.

We can improve UX with storage node configurator: an application, that will check side chain balance for bootstrap and ask simple question to prepare storage node config.

Something like this:

```
$ neofs-storage-configurator --wallet [...] --address [...] ./path-to-config.yaml
> Choose the network [mainnet/testnet]:
> Your account has no side chain GAS, you need to make initial deposit, continue? [y/n]:
> Amount of GAS to deposit [1.0]:
> Publicly announced address:
> Listening port [8080]:
> TLS Certificate (optional): 
> UN-LOCODE attribute in [XX-YYY]: 
> Path to the storage dir (all available storage will be used): 
```

Pool of RPC endpoints for main chain and side chain is hadrcoded inside the application.
Application will validate all inputs (will not accept local addresses as announced addresses, will check UN-LOCODE format).

It can be:
- subcommand of neofs-adm,
- new application,
- new application in new repo.

**Comment by fyrchik** [comment]
It should be subcommand of neofs-adm, as this is the purpose of this tool -- simplifying configuration and deployment.

**Comment by alexvanin** [comment]
Also add relay mode support.
