### ISSUE TITLE
Fix TODOs or link them to issues

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1094]
I have walked through some of the TODOs and found out that we have more and more of them with each release.
```
> for i in (git tag); echo -n "$i: "; git checkout $i 2>/dev/null; rg -i todo | wc -l; end
v0.12.0: 57
...
v0.15.0: 68
...
v0.20.0: 82
...
v0.26.0: 89
...
v0.27.4: 91
```

While some of them are reasonable, Many of them can be fixed immediately or have a link to the corresponding issue.

**Comment by alexvanin** [comment]
As @fyrchik suggested, we can try to solve todos from object storage components at least. They are pretty much the same behavior issues so we need to decide what behavior is suitable and implement it.

E.g.:
https://github.com/nspcc-dev/neofs-node/blob/ac82899e850dc5bfe52be73307c72117e5592e0f/pkg/local_object_storage/engine/delete.go#L52

**Comment by fyrchik** [comment]
@alexvanin yes, and the second part would be to link remaining TODOs to tasks, possibly create some.

**Comment by fyrchik** [comment]
Much better now:
```
$ rg -i 'todo|fixme' | wc -l
44
```
