### ISSUE TITLE
`neofs-cli control` usability

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-node#1103]
- [x] 1. One should be able to set path to wallet and its password in the Control API config file
- [x] 2. `--generate-key` flag has no sense for Control API
- [ ] 3. It would be nice to have a Control API config example with all available options and reasonable comments about them, for instance, alognside with storage node configs
- [x] 4. It might improve usability if help messages about flags will provide an infomation about flags mutual exclusion
- [x] 5. I believe it will improve usability if help message for `healthcheck` will explicitly state that by default request is formed for Storage Node. If a user needs to send healthcheck request to Inner Ring node, they need to set `--ir` flag

**Comment by alexvanin** [comment]
> One should be able to set path to wallet and its password in the Control API config file

For regular NeoFS API as well. Luckily, this code is shared between APIs.

**Comment by aprasolova** [comment]
What about points 3 and 4?

**Comment by cthulhu-rider** [comment]
> What about points 3 and 4?

@aprasolova  sorry the issue was closed accidentally due to `fix` keyword in PR.

Btw can you provide an example of mutexed flags described in 4?

**Comment by aprasolova** [comment]
Sure. `--binary-key`, `--wallet`+password and `--wif` are mutually exclusive.

**Comment by alexvanin** [comment]
> Sure. `--binary-key`, `--wallet`+password and `--wif` are mutually exclusive.

In v0.27.5 `--binary-key` and `--wif` are removed, so there won't be any issues with that. 
If there are no more cases like that, we can consider it done.

**Comment by aprasolova** [comment]
Okay, then point 4 isn't applicable anymore.
