### ISSUE TITLE
True CLI

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#1108]
Please add a real CLI mode:

```
$ neofs-cli -w wallet -r rpc -i
cli> list
....
cli> delete <CID>
```

**Comment by alexvanin** [comment]
I guess it is possible to implement REPL like this one day. Requires some refactor from #1074

**Comment by roman-khimov** [comment]
I think with the possibility to have a local config (so that you don't need to repeat wallet/rpc/etc) this doesn't give a lot of value anymore. Private key reuse may be the only other benefit. So while this can be done, it's certainly not a priority.

**Comment by roman-khimov** [comment]
Not planned for now, can be reopened if need be.
