### ISSUE TITLE
Remove WIF support in `--wallet` argument

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#1128]
I believe there should be no way to pass a sensitive data as a command line argument.

**Comment by alexvanin** [comment]
`--wif` is removed in v0.27.5. You still able to provide WIF with `--wallet` but it is less encouraged this way. Indeed, it is not secure, but it is useful for testing (e.g. neofs-testcases uses it a lot). 

Config is tightly coupled with arguments, it will be hard to keep WIF in config but remove it from arguments. 

I guess we will drop WIF support completely one day.

**Comment by carpawell** [comment]
We are ready.

**Comment by fyrchik** [comment]
I think NEP2 support can also be dropped, I haven't never seen it being actually used anywhere.
