### ISSUE TITLE
Is there a detailed documents about grpc API available for reference?

### ISSUE THREAD

**Issue by Tasselsd** [nspcc-dev/neofs-node#1130]
I see that every grpc request has three fields:
- body
- metaHeader
- verifyHeader

Now I'm not clear about the metaHeader and verifyHeader.

This page https://github.com/nspcc-dev/neofs-api/edit/master/proto-docs/session.md introduced what fields are available, which is good. But how should I set these fields?

If there is no such description document so far, can you explain it for me under this issue? 

You'd better use `neo.fs.v2.accounting.AccountingService/Balance` to give me an example.

Thanks.

**Comment by alexvanin** [comment]
I suggest you to read https://nspcc.ru/upload/neofs-spec-latest.pdf#5a This section contains details about message structure and signing, together with some schematic drawings. 

If you are familiar with go, then I suggest to look at [this snippet](https://github.com/nspcc-dev/neofs-sdk-go/blob/6a7ba33b59efdbfe1e64b7c6e76059dc82244bfd/client/common.go#L227-L257) from SDK Client. This code prepares request by setting meta header and signs it by calling [signature.SignServiceMessage()](https://github.com/nspcc-dev/neofs-api-go/blob/32dd0bb3f9c5c6c444473f6a7ef0f3dd3ed6b201/signature/sign.go#L147) from `neofs-api-go` which sets verification header.

**Comment by Tasselsd** [comment]
this section https://nspcc.ru/upload/neofs-spec-latest.pdf#5a means **" if it is the `Sender`(or requestor), the `origin` and `originSignature` is set to nil "**  like the following code:
```
var body = ...
var metaHeader = ...
var bodySignature = ...
var metaSignature = ...

var req = BalanceRequest(
  body: body,
  metaHeader: metaHeader,
  verifyHeader: RequestVerificationHeader(
    bodySignature: bodySignature,
    metaSignature: metaSignature,
  ));

var accountServiceClient = ...
var res = await accountServiceClient.balance(req);
```
but i caught the error: 
> gRPC Error (code: 2, codeName: UNKNOWN, message: could not verify request: could not verify origin of verification header: could not unmarshal signature, details: [], rawResponse: null, trailers: {})

am I overlooking something?

**Comment by Tasselsd** [comment]
> gRPC Error (code: 2, codeName: UNKNOWN, message: could not verify request: could not verify origin of verification header: could not unmarshal signature, details: [], rawResponse: null, trailers: {})

oh, this error is caused by setting TTL greater than 0.

**Comment by Tasselsd** [comment]
> oh, this error is caused by setting TTL greater than 0.

❌completely wrong!  the TTL should set a number  that greater than 0! 

> gRPC Error (code: 2, codeName: UNKNOWN, message: could not verify request: could not verify origin of verification header: could not unmarshal signature, details: [], rawResponse: null, trailers: {})

✔️this error is caused by not setting originSignature. origin is nil, so originSignature should :
```
originSignature = ecdsaSign(privKey.bytes(), byte[0])
```
