### ISSUE TITLE
Think about how we transfer errors through gRPC

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1139]
See https://github.com/nspcc-dev/neofs-node/blob/master/pkg/network/transport/container/grpc/service.go#L33 and similar TODOs.
Related #1115 .

**Comment by alexvanin** [comment]
I think we come up with API errors and those lines can be removed.
/cc @cthulhu-rider

**Comment by fyrchik** [comment]
Closed via #1145 .
