### ISSUE TITLE
Support working in degraded mode (no metabase)

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1143]
https://github.com/nspcc-dev/neofs-node/blob/master/pkg/local_object_storage/blobstor/exists.go#L60
It is used in code, but unimplemented. `Blobstor.Exists()` seems to be unused, though, as `Shard.Exists` uses metabase only.
Maybe we can remove `Blobstor.Exists()` completely or use it in some way.

**Comment by alexvanin** [comment]
We need exist to work in degraded mode without matabase. Let's change this issue to "support degraded mode in storage engine"

**Comment by fyrchik** [comment]
Refs #1186.
