### ISSUE TITLE
Remove or document `ToV2` casts

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1147]
We still have some `ToV2` version casts in code:
https://github.com/nspcc-dev/neofs-node/blob/master/pkg/innerring/processors/container/process_container.go#L194
https://github.com/nspcc-dev/neofs-node/blob/master/pkg/innerring/processors/reputation/process_put.go#L67
https://github.com/nspcc-dev/neofs-node/blob/master/pkg/innerring/processors/reputation/process_put.go#L94

There are some questions to discuss:
1. Document where `ToV2` casts can be used. Consider a metabase which should work irregardless of gRPC API version https://github.com/nspcc-dev/neofs-node/blob/master/pkg/local_object_storage/metabase/select.go#L588 .
2. A lot of cases use `ToV2().GetValue()` or a `len` of it. This can be approached in SDK with `.Bytes()` method.

Related #596 .
cc @cthulhu-rider

**Comment by roman-khimov** [comment]
These can suggest some SDK problems or maybe can be improved based on current SDK, we need to figure it out.

**Comment by roman-khimov** [comment]
These can suggest some SDK problems or maybe can be improved based on current SDK, we need to figure it out.
