### ISSUE TITLE
Handle errors during object placement

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1153]
https://github.com/nspcc-dev/neofs-node/blob/master/pkg/services/object_manager/placement/traverser.go#L165
https://github.com/nspcc-dev/neofs-node/blob/master/pkg/services/object/util/placement.go#L57

**Comment by alexvanin** [comment]
Remove these `todo` in https://github.com/nspcc-dev/neofs-node/pull/1145

**Comment by fyrchik** [comment]
Closed via #1145 .
