### ISSUE TITLE
Move placement policy parsers to SDK

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#116]
QL parsers are quite useful for applications such as protocol gates or GUI apps. It provides human readable way to set up container policies. So it will be nice to have it in SDK library.

**Comment by alexvanin** [comment]
We've moved JSON parsers of placement policy to the neofs-api-go in https://github.com/nspcc-dev/neofs-api-go/pull/186 and https://github.com/nspcc-dev/neofs-api-go/pull/189

JSON is a convenient way to represent placement policy in a non-binary way. JSON fields are specified in protobuf files in neofs-api. However Query Language isn't.

I am not sure QL grammar will be a part of specification. If it will be, then it makes sense to move it to neofs-api-go. Otherwise it would be better to put QL parser in separate repo with detailed description or keep it in neofs-node for a while.

**Comment by realloc** [comment]
SQL-like QL is part of neofs-cli and it was shown in our presentations many times. This should make external observer think it is NeoFS API integral part, though it's not described in `neofs-api` directly.

I suggest to have SQL-like QL implemented in `neofs-api-go` for convenience. Most probably we will add SQL-like QL grammar declarations in `neofs-api` later, when we agree on tools and format.

**Comment by realloc** [comment]
Should be reconsidered after separate `neofs-client` and `neofs-sdk` releases.

**Comment by roman-khimov** [comment]
I think we can move it now to `neofs-sdk`. It's used by S3 authmate code and at the moment this requires importing `neofs-node`. The package itself is rather small and doesn't have any dependencies on `neofs-node` code, so it can be moved easily.
