### ISSUE TITLE
`StorageEngine` can't read object from `BlobStor` if it is missing in `Metabase`

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1186]
## Context
We've encountered a problem in NeoFS mainnet when node couldn't respond with the stored object because `BlobStor` record was in the `Shard` other then one with `Metabase` record.

## Current behavior
If object is stored in `BlobStor`, but missing in `Metabase`, `Shard.Get` returns `ErrNotFound`.

## Expected behavior
`Shard` (or `StorageEngine`) tries his best and reads the object from `BlobStor` anyway.

**Comment by fyrchik** [comment]
Wouldn't it be a bit of an overkill if we try to access blobstor on every `not found` error?  This is somewhat acceptable in degraded mode, but having to check both FSTree and blobstor on every access attempt to a missing object is a lot of overhead for (not rare) the `Get` itself and for other operations being executed concurrently.
For example, if an object is found in metabase, but not in blobstor, error counter could be incremented and upon reaching degraded mode this logic can be triggered.

**Comment by cthulhu-rider** [comment]
From the side of taking care of the node - yes, it'd be nice to disturb blobstors less often. However, as part of the user call, we are required to service the request at all costs (at least until the NeoFS protocol supports delayed retries feedback), otherwise a false-negative response will be returned.

However, I agree that blobstor and metabase in-shard discrepancy errors should be handled:

1. we can find an object in all blobstors, and upon finding it, update the entry in the same-shard metabase;
2. delete an irrelevant entry in the problem metabase.

So that this repair does not slow down the execution of user operations, we can, as you suggested, track problem cases, and as a sufficient set of them accumulates, move on to asynchronous correction (by log or global).
