### ISSUE TITLE
Object record in `Metabase` and `BlobStor` may end up in different `Shard`s

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1187]
## Context
We've encountered a problem in NeoFS mainnet when node couldn't respond with the stored object because `BlobStor` record was in the `Shard` other then one with `Metabase` record.

In current implementation this behavior is not expected.

## Possible soution
After discovering the cause.

**Comment by cthulhu-rider** [comment]
Still not caught.

**Comment by roman-khimov** [comment]
Well, a good bug will reproduce. If we haven't seen this for 1.5Y, maybe there no bug.
