### ISSUE TITLE
Simple test of WalletConnect support

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-node#1220]
We need to setup a simple demo/test scenario to show that web/dApp can use [WalletConnect](https://neoline20.medium.com/neoline-wallet-chrome-user-guide-a7093c51106d ) for [signing](https://neoline.io/dapi/#signMessage) BearerToken structures and use them in following NeoFs request.

Suggested scenario:

- web page has hardcoded unsigned bearer token
- Bearer Token gets signed with WalletConnect call in interactive mode
- User copies the token and uses it with `neof-cli` or `curl`

The similar scenario may be implemented as integration test in a non-interactive mode.

**Comment by fyrchik** [comment]
Preliminary support is in `wallet-connect` branch, waiting for feedback.

**Comment by amlwwalker** [comment]
@fyrchik can you link to this please? I would like to integrate walletConnect with my Go application using NeoFS

**Comment by fyrchik** [comment]
@amlwwalker This is an implementation https://github.com/nspcc-dev/neofs-sdk-go/blob/master/crypto/ecdsa/wallet_connect.go

You need to wrap your private key into the corresponding type and use as any other scheme.

**Comment by roman-khimov** [comment]
Obsolete.
