### ISSUE TITLE
SN does not notify about objects with 0 `__NEOFS__TICK_EPOCH`

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1228]
In #1183 object notification retrieving was added but not handling object with zero `__NEOFS__TICK_EPOCH` attribute value. Such objects must produce notifications immediately after creation according to spec.

**Comment by carpawell** [comment]
Also, it is not clear what SN should do when it gets objects with `__NEOFS__TICK_EPOCH` with the current epoch value (seems like also immediately notify about them but it is not described in spec).

**Comment by cthulhu-rider** [comment]
So it doesn't matter how must times we produce notification about creation? Consider sequence of events within single epoch (both creation and notification epoch):

1. object is created by user an stored locally
2. object is physically removed for any reason
3. object is stored again for any reason (e.g. replication from other nodes)

In this scenario we'll produce 2 notifications, and this is OK, am I right?

**Comment by carpawell** [comment]
> how much times we produce notification about creation

in fact, it is impossible to notify twice since every notification has a unique ID (from object address) and node works with reduplication mechanisms.

> object is stored again for any reason (e.g. replication from other nodes)

theoretically, if another node has that object, it has already sent the notification (but the current node must be unsure about that and must send its own notification)

anyway, I *do not have* any thoughts about what is correct notification usage in such corner cases, and that is why I have not implemented it in the way it is described in the issue's body.

I just know that @alexvanin and @realloc expected notification to work a little bit differently, maybe they can answer some questions.

**Comment by alexvanin** [comment]
It is okay to produce multiple notifications in some time window, where notification queue can aggregate and de duplicate such messages. 

I don't see an issue of having "immediate notification" if current epoch equal to `__NEOFS__TICK_EPOCH` value. Time window is quite clear: one epoch.

But I do see an issue with zero value in `__NEOFS__TICK_EPOCH`. Every replication will trigger new notification, indeed. So I suppose it should be reworded in spec: zero value in `__NEOFS__TICK_EPOCH` should be interpreted as value from `CreationEpoch` attribute.

In this case immediate notification will be possible and it won't trigger unnecessary notifications during object replication, etc.

/cc @realloc

**Comment by realloc** [comment]
For NeoFS it's technically impossible to guarantee the "exactly once" message delivery semantics, we only focus on "at least once" case. In a short timeframe it's up to a message bus to improve that. In a long run the application should be ready to get duplicated notifications and process them correctly according to its logic.

The immediate tick can't be tied to the object creation epoch, as it may be created earlier and put later. I'd suggest considering multiple immediate ticks a normal situation and add a clarification for this in API spec.
