### ISSUE TITLE
`"lastPart": null` on raw HEAD request of Large Object

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-node#1304]
When I run "raw" HEAD request to Large Object, I expect to get a structure with SplitID, Link Object OID and Last Object OID.
Depending on the node I send the request to, I sometimes get response without Last Object OID. For instance
```
$ neofs-cli --rpc-endpoint s01.neofs.devenv:8080 --wallet L3szhcm4WmZBrFrxuA7PYimNPya39vFrJHvrMg4EEJvmmKVPCGXq object head --cid FW1uZ8m6879R7gBKnE5xX2h9VsgYh1nS3LhTkjwPrwhN --oid ANSsQnhj8bKKSECZo9SMgYZjppsAqc7knNQDtWTyLzvQ   --json --raw

Output: Object is complex, split information received.
{"splitId":"N8NngdnxR9qBUKvWmWo7Aw==", "lastPart":null, "link":{"value":"fweq+mAXw5YBilO1c5XCGkynVvuO9vIfxVvZofWsQT0="}}
```

## Steps to Reproduce (for bugs)
1. Make a deposit
2. Create a container
3. PUT a Large object to that container
4. Run HEAD request on the Large Object OID, try with different nodes.

This issue reproduces from time to time. I get the incomplete output multiple times with one node, but when I request another node, the response is as expected.

## Your Environment
```
$ neofs-cli --version
Version: v0.27.5-206-g82fda423 
Build: 2022-04-05T18:47:00+00:00 
Debug: false
```

**Comment by aprasolova** [comment]
The same issue I observe with `link` filed as well
```
$ neofs-cli --rpc-endpoint s01.neofs.devenv:8080 --wallet KyCHKdHWktkGMHCpmzyBtAdNZHPBSW2gS8bYeuXByx6LrYqekAFF object head --cid F2wHoFraBvARrFB3ZZgnnwrq3qYYdtCA9dyQA3dCqyTy --oid DWZ4ARyL84ZtU1cKCNSDiwK2FY5eX2U5VhCzNPqTvpKk   --json --raw 

Object is complex, split information received.
{"splitId":"PnW3GjzFQCiP/YvfcX3kBA==", "lastPart":{"value":"FYXuNG7Q9BKk8MrpJk6n7tZJj2WqKGDmAh4QLQimO4Q="}, "link":null}
```

**Comment by cthulhu-rider** [comment]
Whether this behavior is expected or not, let me explain how it works. See [docs](https://github.com/nspcc-dev/neofs-spec/blob/master/01-arch/04-object_split.md) for details.

`SplitInfo` is not stored directly in container. Each part of the object split-chain can bring a part of the split information:
* `splitId` is a per-container split-chain UUID presented in each chain element
* `lastPart` is an identifier of the last chain element (`Last Part` in spec)
* `link` is an identifier of linking element (`Linking Object` in spec)

Each part of the chain is represented as an object in a container. As you know, the placement of an object in a container is determined by the storage policy. From this it follows that the chain can be "scattered" in various ways over the nodes of the container. It follows from this that each node can have any part `SplitInfo` structure variant with presented `splitId`.

Why does node responds with its own `SplitInfo` view and doesn't gather all the structure? Well, I guess there are two reasons:

1. split-chain can be restored having any field of the `SplitInfo`
2. there is no way to say `don't gather full SplitInfo, respond what you store locally`, at the same time structure can be formed asking each container node and merging the answers

In general I think that current behavior is defined and legitimately.
