### ISSUE TITLE
Container cache invalidation might not work exactly as we expect

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1313]
We use container cache to avoid extra RPCs to blockchain node. Containers can be removed and it leads to a cache invalidation, see: https://github.com/nspcc-dev/neofs-node/blob/606dfa341437795b56a46bb6234b3a017cc5fff8/cmd/neofs-node/container.go#L594
Containers are not created or deleted immediately, but clients usually want to lock execution until operation is finished. To do that apps perform polling using `container.Get` (see pool package in SDK). Polling starts right after `container.Delete` execution which basically reverts invalidation.

Can we do something with it from the Storage side? I guess it would be really nice to avoid cache update of invalidated container for some time, but it looks like overhead, to be honest.

/cc @KirillovDenis

**Comment by alexvanin** [comment]
I admit that there is no better way to handle than we have it now, but maybe someone have thoughts about this as well.

**Comment by cthulhu-rider** [comment]
So now besides TX approval delay we have node's cache TTL delay. Specifically, I would consider the operation of deleting a container to be almost insensitive to delays.
