### ISSUE TITLE
CLI: Unexpected `object put` command output 

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1315]
_Originally posted by @aprasolova_

Object is stored into private container using NeoFS CLI using private key with `OTHERS` role in terms of Container ACL.

## Expected Behavior
Status error is returned with `access to object operation denied` desc.

## Current Behavior
```
$ neofs-cli --rpc-endpoint <endpoint> --wallet <wallet> object put --cid <cid> --file <file>
Enter password > 
 0 / 1048576 [--------]   0.00%
rpc error: client failure: write request: EOF
```

## Possible Solution
Seems like storage node incorrectly responds on object access violation: it should form status response, and send it into stream instead of closing it. 

## Steps to Reproduce (for bugs)
1. create private container in terms of Container ACL
2. create (if not exists) private key other than container owner's one 
3. exec `object put` command 

## Context
Command works correctly if it's executed using container owner's wallet.

## Your Environment
```
$ neofs-cli --version
Version: v0.27.5-229-g606dfa34 
Build: 2022-04-12T20:08:21[+00:00](https://matrix.to/#/+00:00) 
Debug: false
$ neofs-node --version
Version: v0.28.0-rc.2-44-g923db591 
Build: 2022-04-04T13:19:25[+00:00](https://matrix.to/#/+00:00) 
Debug: false

**Comment by alexvanin** [comment]
@aprasolova I suppose it was a large file (so it is similar to https://github.com/nspcc-dev/neofs-http-gw/issues/146). Small file upload works find in those versions. 

```
# node  version
$ docker ps | grep s01 
1f134088d7f4   nspccdev/neofs-dirty-storage:0.28.0-rc.2-44-g923db591   "neofs-node"             4 minutes ago   Up 4 minutes (healthy)                                  s01

# neofs-cli version
$ neofs-cli --version
Version: v0.28.0-rc.3-4-g606dfa34 
Build: 2022-04-20T14:33:49+00:00 
Debug: false

# test
$ neofs-cli -r s01.neofs.devenv:8080 -w ~/Project/Env/neofs-dev-env/services/http_gate/wallet.json object put --cid 4kxP1oyZHR57wFM4SdqREZu4j4zXAZ1MHYd7GHNT2W7H --file ./Makefile 
Enter password > 
 0 / 3830 [------------]   0.00%
rpc error: client failure: status: code = 2048 message = access to object operation denied: access to operation PUT is denied by basic ACL check

**Comment by alexvanin** [comment]
Yes, it is reproduced in 5 MiB object.

**Comment by carpawell** [comment]
Seems like was fixed. Recheck and close if not actual.

**Comment by cthulhu-rider** [comment]
Bug is not reproduced on `v0.30` and `v0.31`.
