### ISSUE TITLE
Object Tree Service

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1322]
# Description
Object tree service operates with arbitrary trees attached to a container. The implementation maintains a CRDT tree for each container the node is in, based on this article https://martin.klepmann.com/papers/move-op.pdf

Usecase 1: allow to alias objects by path `/path/to/file.txt` and move them without creating new objects.
Usecase 2: support versioning

# TODO
## Functional
- [x] Fully-functional implementation of non-synchronization methods (#1324)
- [x] #1326
- [x] #1328
- [x] #1329
- [ ] #1330
- [ ] #1331
- [ ] #1332
- [x] #1333
- [ ] #1334
- [x] #1401
- [x] #1442
- [ ] #1448
- [x] #1505 
- [x] #1628
- [x] #1630
- [ ] #1530
- [x] #1768

## Optimizations
- [x] #1427
- [ ] #1327
- [x] #1445
- [x] #1446
- [ ] #1447 
- [x] #1456

**Comment by roman-khimov** [comment]
Tree service-related issues are to be blocked because we'll be rethinking meta.

**Comment by roman-khimov** [comment]
Trees will be removed, this issue will never be done.
