### ISSUE TITLE
Implement `GetSubTree` for fetching serialized subtree

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1326]
Implement `GetSubTree` RPC:
1. Describe serialization format. Note that gRPC server-side stream is, probably inevitable, so we can divide the tree in chunks. As an example: send a list of (child-parent) relationships. Ensure that it is easy for a client to do some processing before it receives the full tree.
2. Implement the RPC itself (input: node ID + depth, output: tree)

We probably need to support both getting by ID and by path.

**Comment by cthulhu-rider** [comment]
Closed in #1344
