### ISSUE TITLE
Support sharding for tree storage

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1327]
Each tree for a container is stored on all nodes, so the amount of storage can grow indefinitely. We can't store this on SSD because the service should be available in degraded mode. So some blobovnicza-like structure (multiple bolt-db databases) may be needed. I think we can even restrict ourselves to 1 level of depth here.

**Comment by cthulhu-rider** [comment]
Postponed due to priority.

* should look back at https://github.com/nspcc-dev/neofs-node/issues/1780

**Comment by roman-khimov** [comment]
Trees will be removed, this issue will never be done.
