### ISSUE TITLE
Compress tree service storage in a snapshot

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1331]
Operation log representation is quite costly in terms of storage. The proposal is to compress all operations which are older than 2 epochs. It is not as easy as it sounds:
1. Snapshot creation is a one-way process, so all nodes need to agree on what to include in it.
2. In case node is down, it should be able to invalidate local data and synchronize the latest snapshot + all other operations.
3. If less that 1/3 nodes is malicious, all other nodes should be able to agree on a snapshot. So some interaction with the chain is required.

Describe the approach in a separate document and implement it.

**Comment by roman-khimov** [comment]
Trees will be removed, this issue will never be done.
