### ISSUE TITLE
Potentially redundant deletion of a copy of an object 

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1335]
There is a potential situation when storage node removes the only one local copy of an object:
* `Policer` [routine](https://github.com/nspcc-dev/neofs-node/blob/b74fb2b932cf3cfc2a9b3e652ca2e032f331d635/pkg/services/policer/check.go#L16) builds placement vectors for the object and passes each vector to `processNodes`
* `processNodes` analyzes current placement vector, and if it detects redundant local copy, the corresponding callback is called

If we consider the particular placement for the object:
```
[N1, N2]
[N2]
```
then `Policer` of `N2` node will cause object removal on 1st iteration, while object is still required according to 2nd vector.

Is this placement correct? If so, then `Policer` routine must take this into account.

@fyrchik @realloc @alexvanin

## Possible soluition
Place shortage-check after loop in `checkObject`.

**Comment by alexvanin** [comment]
> If we consider the particular placement for the object:

Is this an example of a placement policy with two `SELECT` statements, so we have placement of two lists?

**Comment by cthulhu-rider** [comment]
@alexvanin I guess so, e.g. (simplified)
```
REP 2 SELECT N1|N2
REP 1 SELECT N1
```

This question-case is just for clarification, `Policer` routine must be protected from these situations anyway. The problem arose when moving from a one-dimensional placement vector to a two-dimensional one.

**Comment by alexvanin** [comment]
Current implementation of network map allows that. Try interoperability test down below.

For me it is quite unexpected behavior. When I specify rule with `REP 2` and `REP 1` I would expect three object copies, but I receive only two. Any other thoughts? /cc @realloc @fyrchik @carpawell 

```json
{
  "name": "repeating node in placement result",
  "nodes": [
    {
      "attributes": [
        { "key": "City", "value": "Tokyo" },
        { "key": "Foo", "value": "Bar" }
      ]
    },
    {
      "attributes": [
        { "key": "City", "value": "Tokyo" },
        { "key": "Foo", "value": "Bar" }
      ]
    }
  ],
  "tests": {
    "test": {
      "policy": {
        "replicas": [
          { "count": 2, "selector": "TWO_NODES" },
          { "count": 1, "selector": "ONE_MORE" }
        ],
        "containerBackupFactor": 1,
        "selectors": [
          { "name": "TWO_NODES", "count": 2, "clause": "SAME", "attribute": "City", "filter": "*" },
          { "name": "ONE_MORE", "count": 1, "clause": "CLAUSE_UNSPECIFIED", "attribute": "", "filter": "FOO_FILTER" }
        ],
        "filters": [
          { "name": "FOO_FILTER", "key": "Foo", "op": "EQ", "value": "Bar", "filters": [] }
        ],
        "subnetId": null
      },
      "result": [
        [ 0, 1 ],
        [ 0 ]
      ]
    }
  }
}
```

**Comment by fyrchik** [comment]
Currently uniqueness is achieved with properly written `SELECT` statements and HRW sorting.
`REP N` means distribute `N` copies over nodes from this `SELECT` irregardless of what other `REP`s do.

The desired behaviour (no intersections) can be achieved with compound filters, provided there are enough nodes in the netmap.

**Comment by cthulhu-rider** [comment]
Lets fix it then as described in Possible solution.
