### ISSUE TITLE
Restart services after switching to another neo-go RPC node 

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1337]
After #1170 node connects to the Morph via WS connection only and it supports node switching without application restart. However, during the switching process, it could lose some notifications that may change the node's state. We can implement some syncing callback [call](https://github.com/nspcc-dev/neofs-node/blob/v0.28.0-rc.3/pkg/morph/client/multi.go#L142) but it is not fully clear what that callback should do and do we really need that sync (may the node be placed in a totally incorrect state because of losing some morph notifications?).

**Comment by alexvanin** [comment]
> it is not fully clear what that callback should do

As the simplest robust solution, node needs to update internal state of remote contracts as it does at application start. In InnerRing application you may look at [initConfigFromBlockchain()](https://github.com/nspcc-dev/neofs-node/blob/b74fb2b932cf3cfc2a9b3e652ca2e032f331d635/pkg/innerring/innerring.go#L1002-L1040) method. Something similar happens in Storage as well, when it reads current network map.

But we need to do that carefully to avoid some parallel execution of state synchronization and new event processing.

**Comment by roman-khimov** [comment]
What should be done in fact is service restart for everything tied to blockchain state. Consider storage node, it has a local store that doesn't care about blockchain state, it can be reused, but any other data is potentially outdated by the time we reconnect, so a complete service restart is needed.
