### ISSUE TITLE
Support storing binary objects

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1338]
Currently there is no way to store the binary object using NeoFS CLI. This feature can be useful for users which want to store object in container again or restore it after accidental loss.

**Comment by alexvanin** [comment]
Maybe it also worth to add a flag to `object get` command to receive binary object. Therefore binary object upload will have one more use case besides `neofs-lens` dump.

**Comment by acid-ant** [comment]
With flag `--binary` of the commands `neofs-cli object get/put/delete` user can point to the file with serialized object structure(id + signature + header + payload)
Planning to use for development purposes.
