### ISSUE TITLE
Undefined behaviour on duplicated container attributes when using neofs-cli

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-node#1339]
It's not allowed to create a container with duplicated attributes.
When using neofs-cli, I noticed that it reports about this constraint from time to time. It depends on the attribute kind.

## Current Behavior
Below I try to create two containers with duplicated attributes. In the first snippet, the attributes are custom, and I immediately get an error. In the second snippet, the attribute `Timestamp` is added by the neofs-cli "under the hood". I believe it is also the case of attributes duplications, but neofs-cli sends a container creation request into the node. (In this case the command failed after 60sec timeout.)
```
$ neofs-cli --rpc-endpoint s01.neofs.devenv:8080 --wallet L58r7pn31wvBAECxPPo96AM4fH3JHfUrfGRyo9pQoa13KMfP3QEJ \
container create --policy "REP 2 IN X CBF 1 SELECT 4 FROM * AS X"  --attributes Size=small, Size=big  --await

invalid container attribute
```
```
$ neofs-cli --rpc-endpoint s01.neofs.devenv:8080 --wallet L58r7pn31wvBAECxPPo96AM4fH3JHfUrfGRyo9pQoa13KMfP3QEJ \
container create --policy "REP 2 IN X CBF 1 SELECT 4 FROM * AS X"  --attributes Timestamp=new  --await

container ID: HaEweDDwUWZbcC5t97dUk34svexgr8q27c6PHTgsKSNQ
awaiting...
```
## Expected Behavior
I'm not sure what is the expected behaviour because it is undefined. If a user duplicates a "well-known" attribute, like `Timestamp`, it will be redefined OR it is considered as an error?

## Your Environment
```
$ neofs-cli --version
Version: v0.27.5-229-g606dfa34 
Build: 2022-04-12T20:08:21+00:00 
Debug: false
```

**Comment by alexvanin** [comment]
We do have `--disable-timestamp` flag, so I would try to make use of it. 

```
$ neofs-cli container cerate -r [..] -w [..] --policy [..] --attributes Timestamp=now
You are trying to override default timestamp attribute set by CLI. To do that, use '--disable-timestamp' flag.

$ neofs-cli container cerate -r [..] -w [..] --policy [..] --attributes Timestamp=now --disable-timestamp
container ID: HaEweDDwUWZbcC5t97dUk34svexgr8q27c6PHTgsKSNQ
```

Also we have two default object attributes:
- FileName
- Timestamp

Chosen behavior should be applied to them as well.

**Comment by aprasolova** [comment]
I have the same question about empty attribute. Actual CLI tries to create the container but exceeds the timeout (I've made three retries)
```
$ neofs-cli --rpc-endpoint s01.neofs.devenv:8080 container create --wallet <some_wallet> --config <some_config> --policy "REP 2 IN X CBF 1 SELECT 4 FROM * AS X"  --attributes NoAttribute=   --await
container ID: 4et5sWpM4WYqJVxVcUG4KWa4GuGo1F3TtaqrsKXnm11P
awaiting...
timeout: container has not been persisted on sidechain
```
I suppose the empty attrubute is not allowed, but CLI doesn't report it.

**Comment by alexvanin** [comment]
> My question is not how to redefine the timestamp from CLI. I wonder what behaviour should I expect when I use the Timestamp attribute.

In the comment above I suggested the behavior: throw an error message `You are trying to override default timestamp...`

> I suppose the empty attribute is not allowed, but CLI doesn't report it.

This is definitely a bug.
