### ISSUE TITLE
Unify lifetime process of gRPC servers

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1342]
Currently `control`/`tree` service is created separately from other services. It would be nice to handle all gRPC services in a similar fashion.

**Comment by fyrchik** [comment]
Also we might want tree service to listen on the same API as the other serivces.

**Comment by realloc** [comment]
For the tree service this has to be done.
However, the control service is a bit different beast and must listen on a separate endpoint with API definition not being a part of the main NeoFS API.

**Comment by roman-khimov** [comment]
Control service should not be touched, it's prioritized now to start early.

**Comment by roman-khimov** [comment]
And tree service is to go away soon, so NOBUG.
