### ISSUE TITLE
connection closed before server preface received

### ISSUE THREAD

**Issue by tasselsd** [nspcc-dev/neofs-node#1351]
I got unexpected output when I use `neofs-cli`
```
# ./neofs-cli-amd64 accounting balance -r grpcs://st2.storage.fs.neo.org:8082 -w my-wallet-path/wallet.json
Enter password > 
rpc error: write request: rpc error: code = Unavailable desc = connection closed before server preface received
```

## Expected Behavior

Can communicate correctly with storage node
## Current Behavior

rpc error: write request: rpc error: code = Unavailable desc = connection closed before server preface received

## Your Environment
```
# ./neofs-cli-amd64 --version
Version: v0.28.0 
Build: 2022-04-29T16:17:25+00:00 
Debug: false
```

**Comment by cthulhu-rider** [comment]
@tasselsd thanks 4 ur report :smile_cat: 
There was a bug with TLS connections in NeoFS CLI. Expect a patch soon.
