### ISSUE TITLE
Transfer TXs devour Inner Ring GAS in Testnet

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1360]
There is a rapid loss of GAS from Inner Ring in the NeoFS Testnet. @alexvanin has found that one of the reasons is multiple transfer transactions for the distribution of basic income.

## Possible solution
Get a solution from https://github.com/nspcc-dev/neofs-node/pull/1011: customize transfer fees in config.

**Comment by alexvanin** [comment]
One can see multiple transfer transaction in T4 network in block `1223510`.
27 transfers invocations per alphabet node, each tx costs more than 15.0 GAS (see additional fee), total >400.0 GAS spend by one alphabet node. This is too much.

**Comment by cthulhu-rider** [comment]
@alexvanin so there are two ways to explore:

1. decreasing per-TX fee
2. decreasing number of TXs

Proposed solution touches 1), and 2) is needed to be researched (im not sure if it's even possible).

**Comment by roman-khimov** [comment]
Settlements transactions are paid for by the Proxy now and it has a lot of GAS. Otherwise duplicates #898.
