### ISSUE TITLE
neofs-node: connection closed before server preface received

### ISSUE THREAD

**Issue by tasselsd** [nspcc-dev/neofs-node#1361]
Related issue #1351 ,  `neofs-node`  has a similar issue:
```
May 05 18:57:48 debian neofs-node[2590220]: 2022-05-05T18:57:48.716+0800        error        replicator/process.go:84        could not replicate object        {"component": "Object Replicator", "node": "xxx", "object": "xxxx/aaaa", "error": "(*putsvc.RemoteSender) could not send object: (*putsvc.remoteTarget) could not put object to [/dns4/xxxxx/tcp/xxx]: init object writing on client: open stream: rpc error: code = Unavailable desc = connection closed before server preface received"}
```
## Your Environment
```
# neofs-node --version
Version: v0.28.1 
Build: 2022-05-05T09:07:54+00:00 
Debug: false
```

**Comment by cthulhu-rider** [comment]
@tasselsd thanks 4 the report! I can't reproduce a bug.

Some details would help: 
- replication target's version (is it `v0.28.1` too?)
- is network address in your example public? If so, could you let me know, I'll try to connect work with it from CLI
- do you have an access to node's config (at least `grpc` section)?

**Comment by tasselsd** [comment]
> @tasselsd thanks 4 the report! I can't reproduce a bug.
> 
> Some details would help:
> 
> * replication target's version (is it `v0.28.1` too?)
> * is network address in your example public? If so, could you let me know, I'll try to connect work with it from CLI
> * do you have an access to node's config (at least `grpc` section)?

@cthulhu-rider it's my configuration's issue:
```
node:
  addresses:
    - <domain>:<port>
```
Since I have `tls` turned on, the correct configuration should be like this:
```
node:
  addresses:
    - /dns4/<domain>/tcp/<port>/tls
```

But I think I should report a issue about `neofs-adm`.
https://github.com/nspcc-dev/neofs-node/blob/d99800ee93bbe9b0699313ba7a5ecab85699731c/cmd/neofs-adm/internal/modules/storagecfg/root.go#L153

The validation here prevents me from filling in the correct `Publicly announced address` format when I generate the storageconfig

**Comment by cthulhu-rider** [comment]
@tasselsd and what's the final network address which has been announced in netmap? `v0.28.1` should work correctly with mentioned address.

> a issue about neofs-adm

This is definitely an incorrect behavior from adm tool, your format is absolutely correct `/dns4/<domain>/tcp/<port>/tls`. We'll fix it.

**Comment by tasselsd** [comment]
@cthulhu-rider  Now I changed `<domain>:<port>` to `/dns4/<domain>/tcp/<port>/tls` and it already works fine.

Thanks.

**Comment by alexvanin** [comment]
> @cthulhu-rider Now I changed `<domain>:<port>` to `/dns4/<domain>/tcp/<port>/tls` and it already works fine.

I guess you can also use `grpcs://<domain>:<port>` to announce address with TLS.

**Comment by tasselsd** [comment]
@alexvanin yep
