### ISSUE TITLE
Unable to set correct network address in config interactive

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1363]
Originally posted by @tasselsd in #1361.

It's impossible to compose storage config with `/dns4/<domain>/tcp/<port>/tls` network address in `neofs-adm` tool.

## Expected Behavior
Adm should accept addresses in mentioned format.

## Current Behavior
Adm denies an address with `Address must have form A.B.C.D:PORT` report.

## Possible Solution
Use `network` package to parse and verify the announced address.

## Your Environment
* Version used: v0.28.1

**Comment by carpawell** [comment]
@cthulhu-rider, was it solved in #1368?
