### ISSUE TITLE
Add doc generation command to all our CLIs

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-node#1396]
We need to add a command for generating CLI documentation in Markdown format or using a template specified.

Something like:
```
$ neofs-cli gendoc <outdir> [custom.template]
```

Related info: 
- https://github.com/spf13/cobra/blob/master/doc/md_docs.md
- https://github.com/spf13/cobra/tree/master/doc

**Comment by fyrchik** [comment]
I hasn't been able to find templates for generating documentation, only for help/usage messages. Could you give an example of what is expected? We can just use go-style templates, but it is a separate task (not an easy one) to write them properly.
