### ISSUE TITLE
eACLs based on object attributes don't control the access

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-node#1399]
An eACL set for these object attributes: `creationEpoch`, `homomorphicHash`, `payloadHash` and `version` don't control the access.

## Expected Behavior
I create an eACL table which DENIes GET for OTHERS when object's `creationEpoch` is equal to X. When I try to GET object created on X epoch I expect "access denied by eacl check" error.

## Current Behavior
I successfully get the object.

## Steps to Reproduce (for bugs)
Log of test runs with all object attributes is attached.
[log.tar.gz](https://github.com/nspcc-dev/neofs-node/files/8728372/log.tar.gz)

## Regression
Yes

## Your Environment
```
$ neofs-cli --version
Version: v0.28.1 
Build: 2022-05-05T09:07:45+00:00 
Debug: false
```
neofs-dev-env: `0ba3eebc5ea513769a3dd183603dd12ef5e366e4`

**Comment by fyrchik** [comment]
Do they have `$Object:` prefix?

**Comment by aprasolova** [comment]
Yes, they have. You may check the tests log.

**Comment by fyrchik** [comment]
May be related to https://github.com/nspcc-dev/neofs-sdk-go/pull/266
