### ISSUE TITLE
test: Avoid hard-coding blobovnicza tree dir in `corruptSubDir` func

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1407]
After #1400 function ignores `blobovnicza` directory. Its name is hard-coded since dir organization in `BlobStor` is package-closed. We need:

1. partially export dir info from `blobstor` package, or
2. reconsider `BlobStor` corruption (???)

**Comment by fyrchik** [comment]
`corruptSubDir` was written the way it is because the intention was to have tests that ensure file from other (non-corrupted) folders can still be read.

**Comment by fyrchik** [comment]
This can be easily done after #1522 .

**Comment by roman-khimov** [comment]
Obsoleted by #2453.
