### ISSUE TITLE
service/tree AddByPath problem

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-node#1419]
In seems the `AddByPath` method in tree service works wrong (at least not as s3-gw expected).
It wold be nice to have separate intermediate nodes when we use `AddByPath` rather than using created by client.

![image](https://user-images.githubusercontent.com/11478618/169786331-3e585af1-53df-4af2-930a-b4006fd1ad12.png)

@alexvanin @realloc @fyrchik

**Comment by fyrchik** [comment]
Actually, the first diagram is the expected one. `obj/sub` leaf shouldn't create a new `obj` node if it already exists.

**Comment by KirillovDenis** [comment]
That's a problem. We have no simple way to remove node without its children. Also it's not easy to know which node is intermediate (to find some nodes by prefix)

**Comment by fyrchik** [comment]
We can't remove a node without it's children, because each node should have a parent. Even then there is no obvious way to have "internal" nodes, because `AddByPath` can use any attribute.

What problem are you trying to solve?

**Comment by KirillovDenis** [comment]
> What problem are you trying to solve?

1. I want to find the "intermediate" node to list objects by prefix in s3-gw. (We must remember that there are nodes with the same path as the "itermediate" node and such nodes can also have children)
2. I want to delete some node with specific attribute (e.g. `OID`) but if this node is "itermediate" I don't want to remove its children. (This can happen when I add `obj/` and `obj/sub` objects into s3-gw and want to delete `obj/` (it's an object name rather than prefix in this case))

**Comment by KirillovDenis** [comment]
Closed by #1421
