### ISSUE TITLE
More detailed logging of application launch steps

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1429]
`neofs-node` app writes some launch stages into log. We encountered a startup hang, the cause of which could not be traced. I propose to describe in detail each stage of the application launch up to `application started`:

- `starting <stage>`
- `<stage> successfully done`

I suggest to use `INFO` log level.

**Comment by fyrchik** [comment]
We could duplicate some config parameters in log with debug level, like `initializing local storage metabase_path=x blobobnicza_depth=8`. This is similar to #1121 (see https://github.com/nspcc-dev/neofs-node/issues/1121#issuecomment-1028969699), but for `neofs-node`.

Can be done separately and in the components themselves.

**Comment by fyrchik** [comment]
BTW, this has already been useful to quickly identify the reason of the long node startup in #1463 .
