### ISSUE TITLE
Batch operations in the tree service

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1447]
After #1431 we started to use bolt batches for optimizing concurrent operations execution.
However the can gain even more benefit if we also do some batching one level above.
Consider operations with the following timestamps: 4, 3, 5, 2.
Right now it will be like this:
1. do 4
2. undo 4, do 3, do 4
3. do 5
4. undo 5, undo 4, undo 3, do 2, do 3, do 4, do 5

After this PR we should behave as follows (assuming 2 values are in a single batch):
1. do 3, do 4
2. undo 4, undo 3, do 2, do 3, do 4, do 5

**Comment by roman-khimov** [comment]
Trees will be removed, this issue will never be done.
