### ISSUE TITLE
Allow to revive dead object via control service

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1450]
1. Check if the object was removed (probably via `neofs-lens`)
2. Allow to forcefully revive the object via `neofs-cli control` service.

cc @cthulhu-rider

**Comment by carpawell** [comment]
> Allow to forcefully revive the object via neofs-cli control service.

What behavior is expected? Just removing GCMark/Tombstone records in the corresponding buckets? Should that command do any related routine (e.g. returning the status of the "restored" object (e.g. we have cleared removing marks but the object is not found in SE anyway), trying to fill meta base with updated object state)? Or is it just about removing metabase "removed" state?

**Comment by cthulhu-rider** [comment]
@carpawell when I did it once there was a need to just remove all removal marks from all metabases. We can think about the behavior deeper.

**Comment by carpawell** [comment]
My recent removing experience says that removing MUST be done really carefully. So I just want to know who a future user of that command is: a developer who *knows* what he does or some kind of system administrator?

I am afraid of that command misusing and potential infinite object storing.

**Comment by cthulhu-rider** [comment]
The command is intended for the node administrator. The rest of the network is not insured against this regardless of the command.
