### ISSUE TITLE
synchronize common make targets across all projects

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#1457]
There should be a list of common make targets that should be the same for all projects.
For example:
- `make bin` makes binaries using host env
- `make docker/bin` -- makes binaries using clean docker env.

**Comment by 532910** [comment]
https://github.com/nspcc-dev/neo-go/issues/2529
https://github.com/nspcc-dev/neofs-s3-gw/issues/471
https://github.com/nspcc-dev/neofs-http-gw/issues/159

**Comment by 532910** [comment]
It depends on other repos.

**Comment by realloc** [comment]
Done for all relevant repos.
