### ISSUE TITLE
How much endpoints will listen the node with the example config?

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#1459]
https://github.com/nspcc-dev/neofs-node/blob/cc6209e8a011974ef25a5be53ccac8c59ff0414e/config/example/node.yaml#L45-L62

**Comment by cthulhu-rider** [comment]
Exactly `num: 2` ones. Config parser currently ignores tail endpoints outside of `num`. This allows not to delete the last endpoints after decreasing `num`.

**Comment by fyrchik** [comment]
See if we can remove `num`. The problem is array handling when environment variables are used.
