### ISSUE TITLE
Unexpected `access to object operation denied`

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-node#1471]
Using current [master](https://github.com/nspcc-dev/neofs-node/commit/da3ae202f07d2148f57074d777bbc51111a97754) and bearer token (with all allowed operations). I've got a little unexpected error during head object (that doesn't  exist or that is removed):
```
status: code = 2048 message = access to object operation denied 
details: access to operation HEAD is denied by extended ACL check: can't parse headers: status: code = 2049
```

Doing the same without bearer token the errors are the following:
* `status: code = 2049 message = object not found` if object doesn't exist
* `status: code = 2052 message = object already removed` if object is removed

Is this the expected behavior?

**Comment by fyrchik** [comment]
Maybe related to #1392 .
