### ISSUE TITLE
Deleting containers doesn't seem to work but no errors

### ISSUE THREAD

**Issue by amlwwalker** [nspcc-dev/neofs-node#1478]
## Expected Behavior

When deleting container they should after some amount of time no longer appear when listing out all containers or searching their content of objects

## Current Behavior

When attempting to delete a container there seems to be no error, however when listing the containers afterwards (any amount of time in the future) the containers still seem to exist. I.e deleting is not working

## Possible Solution

Not sure...

## Steps to Reproduce (for bugs)

1.
```go
    ownerID := owner.NewID()
    ownerID, err = wallet.OwnerIDFromPrivateKey(key)
    if err != nil {
        log.Fatal("cant retrieve ownerID:", err)
    }
    for _, v := range list {
        cntID := cid.ID{}
        cntID.Parse(v.String())

	ni, err := cli.NetworkInfo(ctx, client.PrmNetworkInfo{})
	if err != nil {
		return 0
	}

	expire := ni.Info().CurrentEpoch() + roughEpochs // valid for 10 epochs (~ 10 hours)
	return expire

    var prmSessionCreate client.PrmSessionCreate
    prmSessionCreate.SetExp(expire)
    res, err := cli.SessionCreate(ctx, prmSessionCreate)
    addr := address.NewAddress()
    addr.SetContainerID(&containerID)
    cntContext := session.NewContainerContext()
    cntContext.ForDelete()
    cntContext.ApplyTo(&containerID)
    stoken := session.NewToken()
    stoken.SetSessionKey(res.PublicKey())
    stoken.SetID(res.ID())
    stoken.SetExp(expiry)
    stoken.SetOwnerID(ownerID)
    stoken.SetContext(cntContext)
    err = stoken.Sign(key)

        if err != nil {
            log.Fatal(err)
        }
        res, err := container2.Delete(ctx, cli, cntID, stoken)
        if err != nil {
            log.Fatal("could not delete containers", err)
        }
        fmt.Printf("delete response %+v\r\n", res.Status())

//now wait any amount of time and list containers with response, err := cli.ContainerList(ctx, l) and the deleted container will still exist 
```

## Context

Cant delete containers...

## Your Environment

* Version used:
* `github.com/nspcc-dev/neo-go v0.98.1`
* `github.com/nspcc-dev/neofs-sdk-go v1.0.0-rc.2`
* Operating System and version (`uname -a`):
`Darwin AW-RD-MBP-20 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64`

**Comment by fyrchik** [comment]
Can this still be reproduced?

**Comment by roman-khimov** [comment]
@amlwwalker, do you have this issue with the current testnet?

**Comment by roman-khimov** [comment]
Container-related tests are fine here (and there are deletions there): https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/490-1692002283/index.html#suites/838ebe8e9830cc0d30e44fefa0a45f73

So I'm assuming this is outdated.
