### ISSUE TITLE
Provide timeout when opening bbolt databases

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1503]
Bolt invokes `flock` after opening a file, and can hang indefinitely if the timeout is not explicitly provided.
This happens, for example, if 2 equal paths are provided in the config.
Add some reasonable timeout and, possibly, allow to override it.

**Comment by carpawell** [comment]
> possibly, allow to override it

One more config value? Isnt overhead for that purpose?

**Comment by fyrchik** [comment]
Closed via #1504.
