### ISSUE TITLE
Ignore or log errors on resync metabase

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1520]
It is impossible to start a node.
```
июн 15 14:31:28 yu neofs-node[2482370]: 2022/06/15 14:31:28 could not initialize shard YAwBKiTu1Q4Bvo7MFw9LUT: could not initialize func() error: fs tree iterator failure: could not decompress object data: unexpected EOF
июн 15 14:31:28 yu systemd[1]: neofs-storage.service: Main process exited, code=exited, status=1/FAILURE
```

The object in case is 6-bytes only (and 522k on another node), so the node was most likely shutdown during the replication. This is an expected scenario, we should:
1. Log more descriptive error (object address, for example)
2. Continue metabase resync.

**Comment by fyrchik** [comment]
We can also mark such objects and process them with some priority (delete or redownload).

**Comment by carpawell** [comment]
> Metabase can store such "bad" objects in a special place.

Inspecting that place functionality could be added to some of our CLIs.
