### ISSUE TITLE
Add a policy for filtering objects by type

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1525]
```
policy:
    object_type:
       - Tombstone
       - Lock
       - !Regular
```

`object_type` is an array which contains possible object types to be put in this blobstor.
May be `!` in prefix can be used for excluding some types.

**Comment by roman-khimov** [comment]
This doesn't have any practical use, objects are objects and special objects are just treated specially when being processed. Separating their storage doesn't give any benefit.
