### ISSUE TITLE
Allow tree structure modification during network upgrade

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1530]
Tree service client applications, like S3 Gateway, might develop over time and produce some incompatible changes:
- rename key in the node meta (see https://github.com/nspcc-dev/neofs-s3-gw/issues/533),
- update value format in the node meta,
- split one node into several nodes,
- merge several nodes into one,
- many more.

Client applications don't want to break compatibility during update, so they want to make changes in tree structure. 

This is applicable for private installations with manual software update. Client side may prepare a transition app / script that will update tree structure. To do that, tree service should allow tree service operations for network admin, like `Add`, `GetSubTree`, `Remove`, and, probably, extra method to list all trees in the storage node (maybe it is available in control service for tree sync?). 

I see two options there:
1. Tree service pass auth check (bearer token) if request is signed by storage node wallet
2. Tree service pass auth check (bearer token) if request is signed by multi-signature wallet of Alphabet nodes

Maybe there are better options for that.

**Comment by fyrchik** [comment]
So we need to do two things:
1. Extend access control checks with local node key
2. Allow to list/drop arbitrary trees via the control service in addition to sync.

RIght?

**Comment by alexvanin** [comment]
In this proposal yes and yes.

Maybe you find out better solution on how to manage trees for system admin.

**Comment by roman-khimov** [comment]
Trees will be removed, this issue will never be done.
