### ISSUE TITLE
Check contract versions during inner ring start

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1540]
IR depends on particular contract versions, it should fail if either contracts or IR are too old.

**Comment by cthulhu-rider** [comment]
I thought about the exact solution. Lets try to gather all the breaking and compatible contract changes.

### Compatible

- new method(s)
- new parameter of existing method (is it really compatible to call contract method w/o some last parameter(s) @fyrchik @AnnaShaleva ?)
- compatible change of parameter type (can it be?)

### Breaking

- method removal
- behavior restriction (like container removals in https://github.com/nspcc-dev/neofs-contract/issues/247)

Overall Inner Ring application will check if version number of the contract is compatible with the maximum served version of the build. If any contract is incompatible, IR exits.

**Comment by fyrchik** [comment]
New parameter of existing method is incompatible, unless the older version is also present.
Parameter type changes can or can not be compatible, usually it is about the semantics.

I propose to have the oldest version number stored in neofs-ir source code. The current version number is fetched from the `neofs-contract dependency`. If we make some incompatible change, the number stored in it is increased and the dependency is updated. The innerring then checks if the actual version number is between these 2 numbers.

**Comment by cthulhu-rider** [comment]
What if:
* contract was changed compatibly (e.g. we added new method)
* IR supports new version of the contract
* IR starts with an older deployed version of the contract

In this scenario I guess we need to determine if new method call is needed or not. It can lead to one of the approaches:

1. double num version (major and patch)
2. increase contract version on each contract API change and track the compatibility table more smart

**Comment by AnnaShaleva** [comment]
> is it really compatible to call contract method w/o some last parameter(s)

I agree with @fyrchik, it can be both compatible and not, depends on the way how you provide this parameter and how it is used by the contract. If the caller is aware of this change, then he can decide about the current contract version by loocing inside the ABI.

> However is doesn't cover the case of contract hotfix, without IR update, so need to think further.

I'm out of the problem scope and not sure whether it suits your purposes, but how about using built-in versioning with addition to manual contract versioning? For each contract we nave an `UpdateCounter`, it is incremented each time the contract is updated. `UpdateCounter` is included into both JSON-RPC `getcontract` responce and stack item result.

**Comment by roman-khimov** [comment]
May become irrelevant after #2195.
