### ISSUE TITLE
Initialize shards properly

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1549]
During node start we currently fail if the metabase cannot be initialized.
The behaviour should be the following:
1. Try opening the metabase. On failure start shard in the degraded mode.
2. Try initializing blobovniczas. On failure:
2.1. If there is only 1 shard, shutdown the node.
2.2. If there are more shards, start as usual with the shard disabled.

**Comment by cthulhu-rider** [comment]
About 2: may be we want to continue working in mode without blobovnicza tree? Seems like we can just store all objects in `FSTree` which is non-optimal but possible.

**Comment by cthulhu-rider** [comment]
In current implementation `ModeDegraded` on shard doesn't work as we expected when metabase is completely dead. For example, some operations are executed on metabase regardless of opening/init failures. I propose to pre-discuss changing behavior in `ModeDegraded` mode.

**Comment by fyrchik** [comment]
Closed via #1552.

**Comment by fyrchik** [comment]
Let it be opened for the actual master implementation with a lower priority.
