### ISSUE TITLE
profiler and metrics addresses should be localhost by default without timeout

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#1562]
https://github.com/nspcc-dev/neofs-node/blob/57200e18cd0b264d5a86977556ed62acbd0f60c3/cmd/neofs-ir/defaults.go#L40-L44

**Comment by alexvanin** [comment]
In this case profiler and metrics are going to be enabled by default. Is it the goal of this issue? If yes, then what default ports should profiler and metrics use? Should it be the same for storage nodes?

**Comment by 532910** [comment]
No, they should not be enabled by default. But being enabled, I'd expect them to listen on localhost, w/o timeout.

> You specified ir config, should it be the same for storage nodes?

It looks like they use the same config. I've not found other `shutdown_timeout` definitions and there is no `neofs-node/cmd/neofs-ir/defaults.go'

**Comment by alexvanin** [comment]
> No, they should not be enabled by default.

It is not possible in current configuration. But as we internally discussed, it can be synced with neo-go where config has explicit `enable` flag.

If @nspcc-dev/neofs-core  team adopts this change, we will adopt it in the service applications as well.

**Comment by fyrchik** [comment]
After #1602 all services are disabled by default.
