### ISSUE TITLE
Add new issues to the NeoFS Core project automatically

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1566]
It looks like it is possible #1545 , #1547, but doesn't work currently #1564.
We need to test this in a separate repo. Possible problems in the last implementation:
1. A separate secret is needed.
2. Something is missing from config.
3. This action doesn't work, use another.

**Comment by fyrchik** [comment]
Looks like it is about the token rights https://github.com/actions/add-to-project/issues/97

**Comment by roman-khimov** [comment]
No project --- no problem.
