### ISSUE TITLE
Blockchain data backup-restore for a particular height

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-node#1571]
In `neofs-adm` we need a command to get the data diff between two heights, extract it and be able to inject back later. This should cover at least Containers, eACL and NNS records. The extracted data has to be checked for consistency at both extraction and restoration stages.

Being a destructive action for emergency cases, it must require Alphabet multisignature.

Use case example:

Because of some tragic incident, a fork appears in the Sidechain. The operations person isolates a "wrong" CNs, saves useful data and restores it after chain is harmonized again.
This may or may not imply resetting the chain to some height in the past.

**Comment by roman-khimov** [comment]
Not needed. If a fork happens and we have enough CNs to continue then the longest chain obviously wins. If a fork happens and there are not enough CNs to continue any of the branches then it doesn't matter much which branch is chosen.

But forks don't happen.
