### ISSUE TITLE
IR morph endpoints priority

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-node#1572]
Let's consider adding priority to the morph_rpc client pool, the same way it's done for neofs storage node endpoints in S3 and HTTP gateways.

In on-prem environment, IR node needs a way to use local Neo RPC node and switch to nearest neighbour in case of local node malfunction or overload.

**Comment by realloc** [comment]
The same may be also relevant for the storage nodes.

**Comment by fyrchik** [comment]
https://github.com/nspcc-dev/neofs-s3-gw/blob/master/config/config.yaml#L15
