### ISSUE TITLE
Unify epoch expiration flag for CLI's commands

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1574]
Some of them are named `expires-at/on`, and some of them are named `lifetime` (mb there are more options).
Some of them support relative epochs and some do not.

Examples: 
- `storagegroup put`;
- `object put`;
- `bearer create`;
- etc.

**Comment by carpawell** [comment]
@fyrchik, do you mean `expires-at` is about the exact expiration epoch and `lifetime` is about the period? Or is it just about the naming convenience?

**Comment by fyrchik** [comment]
I meant, that it is ok to have different flags for tokens and objects, but object-related flags should be the same.
However, I like your sugesstion, we could remove `+X` syntax in favour of the `lifetime` flag.
