### ISSUE TITLE
config: Make node attributes a map

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1580]
_Inspired by @532910_

Maybe it's worth to make node attributes in storage node's configuration a map string->string instead of string array.

**Comment by fyrchik** [comment]
It would make harder to provide configuration via ENV:
1. Attribute key can be any valid UTF-8 string
2. On windows environment variables are case-insensitive.

I think we could support both options, without any guarantees in case both are used.

**Comment by fyrchik** [comment]
We decided to stay with the current implementation because of the reasons above.
Also, maps are impossible to encode in ENV variables and we don't want to have 2 different config sections.
