### ISSUE TITLE
Consider automatic swtich to the morph RPC with the highest priority

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1615]
After our main endpoint has gone down, we would like to eventually switch back to it even if there are no errors with the other endpoint.

**Comment by carpawell** [comment]
What should be the criteria for the switch? Just time duration? Should it be configured?

If the client has a few endpoints with the same (highest) priority, should it try to connect to the first one after internal sorting? Or all the endpoints with the highest priority should be considered equal?
