### ISSUE TITLE
Move `list-object` CLI command to the `object` sub command

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1626]
`container` command does not work with objects and it seems that `list-objects` is more expected as a sub command of the `object`.

**Comment by alexvanin** [comment]
I don't have strong opinion about having `list-objects` in `object` or `container` section. Just want to highlight the idea behind original decision.

When you want to list container objects, you don't look for exact objects, you want to observe the content of the _container_, what _container_ has inside. So it feels like the list of content is a _container_ property, not the object property.

When you are interested in exact _object_, you know it's properties: object ID or object attributes. And then you go into `object` section to search, get, head or delete these exact _objects_.

**Comment by carpawell** [comment]
None of us has a strong opinion about moving/keeping that cmd. So let's keep it as it is. At least for now.
