### ISSUE TITLE
Improve tree service access control

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1628]
#1328 implemented tree service access control. However there is an issue with such approach: tree service allows access only if request is made by container owner or it contains bearer token. This limits S3 Gateway use cases.

S3 Gateway operates with bearer tokens of the client's buckets/containers. If client tries to access someone else's bucket/container, then it produces request without bearer token. If the object is public, then extended ACL table allows to return object to S3 Gateway without bearer token, which is expected behaviour. 

Tree service doesn't work this way and won't return response to S3 Gateway without bearer token.

We should consider the same access control rules for both object service and tree service.
Or provide additional rules in extended ACL specifically for tree service.

It is blocking https://github.com/nspcc-dev/neofs-s3-gw/issues/505 and https://github.com/nspcc-dev/neofs-s3-gw/issues/504

**Comment by fyrchik** [comment]
We could store the list of public keys in the tree service configuration, for which every operation is allowed.
