### ISSUE TITLE
Sometimes `ContainerList` does not see the newly created container

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-node#1632]
Sometimes `ContainerList` does not see the newly created container in first seconds

## Expected Behavior
Listing can find a new container (from different nodes) after container creation with some node (with await).  

## Current Behavior
Sometimes listing doesn't see new container.

## Steps to Reproduce (for bugs)
See the following code (it use some code from sdk [1](https://github.com/nspcc-dev/neofs-sdk-go/blob/90255e9efa82ac94d479e59e289210fa6afa88a5/pool/pool.go#L2202),[2](https://github.com/nspcc-dev/neofs-sdk-go/blob/90255e9efa82ac94d479e59e289210fa6afa88a5/pool/pool.go#L936)):
```golang

func TestListing(t *testing.T) {
	ctx := context.TODO()
	key, err := keys.NewPrivateKeyFromHex("1dd37fba80fec4e6a6f13fd708d8dcb3b29def768017052f6c930fa1c5d90bbb") // dev-env private key
	require.NoError(t, err)
	var owner user.ID
	user.IDFromKey(&owner, key.PrivateKey.PublicKey)
	clients := initClients(t, &key.PrivateKey)

	var prmList sdkClient.PrmContainerList
	prmList.SetAccount(owner)
	list, err := clients[0].ContainerList(ctx, prmList)
	require.NoError(t, err)
	fmt.Println("number of containers before creating a new one: ", len(list.Containers()))

	var prmPut sdkClient.PrmContainerPut
	prmPut.SetContainer(formCnr(t, owner))
	cnrRes, err := clients[0].ContainerPut(ctx, prmPut)
	require.NoError(t, err)
	cnrID := cnrRes.ID()

	var prmGet sdkClient.PrmContainerGet
	prmGet.SetContainer(*cnrID)
	var wp WaitParams
	wp.setDefaults()
	err = waitFor(ctx, &wp, func(ctx context.Context) bool {
		_, err := clients[0].ContainerGet(ctx, prmGet)
		return err == nil
	})
	require.NoError(t, err)

	var wg sync.WaitGroup
	for i := range clients {
		wg.Add(1)
		go func(j int) {
			defer wg.Done()
			cl := clients[j]

			listRes, err2 := cl.ContainerList(ctx, prmList)
			require.NoError(t, err2)
			li := listRes.Containers()
			fmt.Printf("node: %d, number of containers: %d, found expected: %v\n", j, len(li), containsCnr(li, *cnrID))
		}(i)
	}

	wg.Wait()
}

func containsCnr(list []cid.ID, cnrID cid.ID) bool {
	for _, id := range list {
		if id.Equals(cnrID) {
			return true
		}
	}
	return false
}

func initClients(t *testing.T, key *ecdsa.PrivateKey) []*sdkClient.Client {
	addresses := []string{
		"s01.neofs.devenv:8080",
		"s02.neofs.devenv:8080",
		"s03.neofs.devenv:8080",
		"s04.neofs.devenv:8080",
	}
	res := make([]*sdkClient.Client, len(addresses))
	for i, address := range addresses {
		var prmInit sdkClient.PrmInit
		prmInit.SetDefaultPrivateKey(*key)
		prmInit.ResolveNeoFSFailures()
		var cl sdkClient.Client
		cl.Init(prmInit)
		var prmDial sdkClient.PrmDial
		prmDial.SetServerURI(address)
		err := cl.Dial(prmDial)
		require.NoError(t, err)
		res[i] = &cl
	}
	return res
}
```

This test expected output:
```
number of containers before creating a new one:  42
node: 1, number of containers: 43, found expected: true
node: 0, number of containers: 43, found expected: true
node: 3, number of containers: 43, found expected: true
node: 2, number of containers: 43, found expected: true
```
Sometimes output looks like:
```
number of containers before creating a new one:  41
node: 1, number of containers: 41, found expected: false
node: 3, number of containers: 41, found expected: false
node: 2, number of containers: 41, found expected: false
node: 0, number of containers: 42, found expected: true
```

## Context
It seems this is the reason of https://github.com/nspcc-dev/neofs-s3-gw/issues/628

## Your Environment
* Version used: `v0.30.0`
* Server setup and configuration: [dev-env](https://github.com/nspcc-dev/neofs-dev-env/commit/e904506e3d569c4190031826ab9e05350ff276a6) 
* Operating System and version (`uname -a`): Linux denis-nspcc 5.15.0-41-generic # 44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by anatoly-bogatyrev** [comment]
Looks like related issue: https://github.com/nspcc-dev/neofs-s3-gw/issues/628

**Comment by fyrchik** [comment]
We cache container lists too https://github.com/nspcc-dev/neofs-node/blob/master/cmd/neofs-node/cache.go#L239

**Comment by fyrchik** [comment]
1. Allow to configure cache parameters.
2. Support manual cache invalidation (should be triggered on certain events).

**Comment by carpawell** [comment]
> Allow to configure cache parameters.

Always a good point.

> Support manual cache invalidation (should be triggered on certain events).

An expensive operation. On the other hand, a delay is smth that we always have in a decentralized system.

**Comment by fyrchik** [comment]
> An expensive operation
Why so? It is not about the whole cache invalidation (I doubt we have such events), just a specific entry. Like delete the container -> receive the event -> remove the entry from the container and eacl cache.

**Comment by carpawell** [comment]
> not about the whole cache invalidation

Oh, well, then we should check (guarantee) that it could be done without any conflicts from more than one goroutine. Currently, we do just [full removal](https://github.com/nspcc-dev/neofs-node/blob/cd71de69a08d87a63fedd7bc4ead54c4ddac8791/cmd/neofs-node/cache.go#L285).

**Comment by cthulhu-rider** [comment]
Container listing cache maps `owner -> []container_id`, so to update the cache on successful creation/removal we need to know the owner of just created/removed container. Currently [PutSuccess](https://github.com/nspcc-dev/neofs-contract/blob/564f147ea1ada9582f9e91f430100ee3598d25e9/container/config.yml#L17-L22)/[DeleteSuccess](https://github.com/nspcc-dev/neofs-contract/blob/564f147ea1ada9582f9e91f430100ee3598d25e9/container/config.yml#L31-L34) notifications don't carry owner. I propose to add owner parameter to these notifications (currently they are calculated in calls anyway).

@carpawell @realloc
