### ISSUE TITLE
neofs-cli: list-containers and list-objects should show its attributes

### ISSUE THREAD

**Issue by tasselsd** [nspcc-dev/neofs-node#1649]
it's common to use attributes to create containers or objects, although sometimes only `--name` is used, thats make it easier for humans to read.

it would be cool to be able to display attributes directly when listing them.

roughly like this:
```
neofs-cli container list-objects --cid 8y8BmXckTq2GikSQ6x5MKyj7jEb6uGRm2JmsWheWi9Fp
AXfU1xrxNE7GvxyuZFZMYbMHRwSwJNULiRgYxdLJRZdt
  Attributes: Key1=Value1,Key2=Value2
BZHjjcA6J5Dp7XEV6gNH6QEek7hQYCwSSNnyDnUbDe9q
  Attributes: Key1=Value3,Key2=Value4
```

**Comment by carpawell** [comment]
That could be done via a separate flag. The current behavior could be kept for compatibility.
@tasselsd, what do you think?

**Comment by tasselsd** [comment]
> That could be done via a separate flag. The current behavior could be kept for compatibility. @tasselsd, what do you think?

good idea! more details?

**Comment by cthulhu-rider** [comment]
@tasselsd pls check it out #1677.
