### ISSUE TITLE
neofs-lens reports version into stderr

### ISSUE THREAD

**Issue by e7506c** [nspcc-dev/neofs-node#1665]
Hi!

I'm using neofs-lens in automation scrips and faced with issue that it reports version into stderr instead of stdout.

```
admin@az:~$ neofs-lens --version >out.log 2>error.log
admin@az:~$ cat out.log
admin@az:~$ cat error.log
NeoFS Lens
Version: v0.30.0
GoVersion: go1.17.11
```

I guess this is because 

```
command.SetOut(os.Stdout)
```
is missed here https://github.com/nspcc-dev/neofs-node/blob/master/cmd/neofs-lens/root.go#L33

**Comment by cthulhu-rider** [comment]
We also need to double-check the same case in other Cobra-based apps.

**Comment by carpawell** [comment]
> We also need to double-check the same case in other Cobra-based apps.

I've checked, other commands are ok.
