### ISSUE TITLE
Support optional preferred way of external interaction with a Node

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1667]
Related and blocked by https://github.com/nspcc-dev/neofs-api/issues/235.

- Add configuration for that and bootstrap with a new attribute.
- Listen to the new endpoint(s) and respond to them.

**Comment by fyrchik** [comment]
Listening endpoints should be explicitly provided in `grpc` section. `ExternalAddr` attribute is supported. I think we may close this now.
