### ISSUE TITLE
neofs-adm: Add possibility to declare contract hash ids in the config file

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#1669]
Add possibility to declare contract hash ids in the neofs-and config file:
- to update contracts with declared hashes, instead of request to NNS
- to tick epoch with request to declared hashes, instead of request to NNS

**Comment by fyrchik** [comment]
We could do this for most commands. Some sanity checks are desireable.

**Comment by roman-khimov** [comment]
Doesn't seem to be useful right now.
