### ISSUE TITLE
Object is prematurely treated as expired (expiration occurs on epoch __NEOFS__EXPIRATION_EPOCH)

### ISSUE THREAD

**Issue by vdomnich-yadro** [nspcc-dev/neofs-node#1670]
## Steps to Reproduce (for bugs)
Let's say current epoch is 100.
1. Create an object via http gate and specify expiration attribute as current epoch: `"X-Attribute-Neofs-Expiration-Epoch": "100"`
2. Get object via http gate (before the next epoch occurs).

## Expected Behavior
Object should be returned, because [by design](https://github.com/nspcc-dev/neofs-api/blob/master/object/types.proto#L123) `__NEOFS__EXPIRATION_EPOCH` defines epoch after which object expires.

## Current Behavior
Http gateway returns the "404 Object not found" response.

## Possible Solution
The bug started to occur after [these changes](https://github.com/nspcc-dev/neofs-node/pull/1634)

## Regression
Yes.

## Your Environment
DevEnv

**Version:**
```
neofs-node v0.31.0
neofs-http-gw v0.23.0
```

**Comment by cthulhu-rider** [comment]
IMO attribute name and description slightly conflict in semantics: the name occurs becoming garbage in epoch `E` while the description in `E+1`. Description prevails anyway.

Looking at the docs, one might get confused whether expiration occurs at the onset of an epoch or at its end. I'd clarify the behavior.

**Comment by alexvanin** [comment]
In gateway apps we have to check expiration setter behavior, considering that `__NEOFS__EXPIRATION_EPOCH` specifies last epoch when object is still available (according to specification).

**Comment by alexvanin** [comment]
Service application now treat `__NEOFS__EXPIRATION_EPOCH` according to specification.
