### ISSUE TITLE
Add the attribute inheritance system well-known attribute support

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1676]
If a node is splitting a "big" object it *should* look for the well-known system attribute. If it found such an attribute, all the child objects *should* also contain it and all the attributes that were provided via that system attribute.

Other nodes do not validate inheritance.

Blocked by:
- [x] https://github.com/nspcc-dev/neofs-api/issues/236
- [ ] https://github.com/nspcc-dev/neofs-sdk-go/issues/313

**Comment by roman-khimov** [comment]
I think it's obsoleted by split version 2.
