### ISSUE TITLE
Add Netmap structure display to neofs-cli

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#168]
Neofs-cli operation to implement:
- Netmap request to  dump latest netmap

**Comment by alexvanin** [comment]
Right now there is no RPC call to fetch netmap from node in `neofs-api`. We should either:
* fetch data from `netmap` contract (with `neofs-cli` or with script that makes requests to neo RPC node)
* create RPC service that is not part of `neofs-api` protocol and support it in `neofs-cli`.

**Comment by alexvanin** [comment]
Do after #311
