### ISSUE TITLE
Add ability to list all containers in the system

### ISSUE THREAD

**Issue by alexchetaev** [nspcc-dev/neofs-node#1689]
Now administrators of neofs installation don't have ability to show full list of containers in the system for audit of another aim. We can use --owner key in neofs-cli in case then we know all containers owner but it doesn't work in case when we create containers with -g key creating key on the fly.

**Comment by fyrchik** [comment]
We can add it to `neofs-adm`, it already can communicate with morph.
Must be able to dump it in file.

**Comment by acid-ant** [comment]
Blocked by #1946

**Comment by acid-ant** [comment]
Blocked by https://github.com/nspcc-dev/neofs-dev-env/pull/229
