### ISSUE TITLE
 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alexchetaev** [nspcc-dev/neofs-node#1690]
Steps: 
* Run four storage node
* create preset for 24kb objects 100 containers x 1000 objects in each
* run load with params 100 threads / r/w = 70/30 / objects size = 24kb, sleep for write 0.25s, sleep for read 0.1s from three servers in parallel.

Expected behaviour: node working properly

Current behaviour: node crashed after 10 seconds of load. 

Config and node loge in attachments.

root@az:~# neofs-node --version
NeoFS Storage node
Version: v0.31.0 
GoVersion: go1.18.4

root@az:~# neo-go --version
NeoGo
Version: 0.99.1
GoVersion: go1.18.4

**Comment by alexchetaev** [comment]
[panic-logs-and-config.zip](https://github.com/nspcc-dev/neofs-node/files/9350069/panic-logs-and-config.zip)

**Comment by fyrchik** [comment]
Closed via #1718 .
