### ISSUE TITLE
Shard is going to degraded mode under load 

### ISSUE THREAD

**Issue by alexchetaev** [nspcc-dev/neofs-node#1691]
Steps:
* Run four storage node
* create preset for 24kb objects 100 containers x 1000 objects in each
* run load with params 100 threads / r/w = 70/30 / objects size = 24kb, sleep for write 0.25s, sleep for read 0.1s from three servers in parallel.

Expected behaviour: load work properly.

Current behaviour: after 10 seconds we see that errors on shards is getting more that threshold and shard is going to degraded. After some time, the node restarts.

root@az:~# neofs-cli --endpoint localhost:8091 -w /etc/neofs/storage/wallet.json control shards list | grep Mode 
Enter password > 
Mode: degraded-read-only
Mode: degraded-read-only
Mode: read-write
Mode: degraded-read-only

Logs and node config and attachments.

[logs + config.zip](https://github.com/nspcc-dev/neofs-node/files/9351137/logs.%2B.config.zip)

root@az:~# neofs-node --version
NeoFS Storage node
Version: v0.31.0
GoVersion: go1.18.4

root@az:~# neo-go --version
NeoGo
Version: 0.99.1
GoVersion: go1.18.4

**Comment by fyrchik** [comment]
In logs:
```
Aug 16 12:29:11 az neofs-node[3751]: 2022-08-16T12:29:11.145Z        warn        engine/engine.go:44        could not get object from shard        {"shard_id": "GdSTiGYYLMRfd3L7XMmnYR", "error count": 11, "error": "could not open blobovnicza 4/8/0: timeout"}
...
Aug 16 12:29:11 az neofs-node[3751]: 2022-08-16T12:29:11.163Z        warn        engine/engine.go:44        could not get object from shard        {"shard_id": "8hiZtY4Drd1GRQLq7qs5mF", "error count": 24, "error": "could not open blobovnicza 4/1/0: timeout"}
```

We should recheck that blobovniczatree doesn't try to open an already opened blobovnicza.

**Comment by fyrchik** [comment]
Reproduced this in a simple scenario: `opened_cache_size = 1, depth = 1, width = 2`, put some objects (10 should be enough) then try to get them all.

The problem is that we have separate caches for `opened` and `active` blobovniczas, but for `get` we check only the first one.
