### ISSUE TITLE
There is some default range for `neofs-cli object hash`

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-node#1693]
When I run `neofs-cli object hash` with no range specified, I get some hash
```
$ neofs-cli object hash --rpc-endpoint s01.neofs.devenv:8080 --wallet wallets/wallet.json --cid <cid> --oid <oid>
Enter password > 
0d29545d312dfa77ffe7a94415955db74cc8fbdb9a1ca5b6d54342efd2b2de31
```
while it's not clear from the help message what is the range
```
...
--range string          Range to take hash from in the form offset1:length1,...
...
```
## Expected Behavior
I'd expect either the exact reasonable default mentioned in the help message OR the `--range` key to be obligatory.
By the way, in the `neofs-cli object range` the `--range` key is obligatory
```
$ neofs-cli object range --rpc-endpoint s01.neofs.devenv:8080 --wallet wallets/wallet.json --cid <cid> --oid <oid>
exactly one range must be specified, got: 0
$ echo $?
1
```

**Comment by cthulhu-rider** [comment]
The command requests full range of the object payload in this case. This is needed to be clarified in the docs.

**Comment by aprasolova** [comment]
I'd propose to clarify the default range in CLI help message as well
