### ISSUE TITLE
services/tree: support GetNodeByPath with empty FileName

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-node#1698]
Currently I can add a new node to the tree with empty `FileName` attribute or with `FileName: path/dir/` (We have an empty filename  for leaf node anyway). But I cannot then find such nodes using `GetNodeByPath`. 

When I use `[]string{"dir", "path"}` as arg in the request it returns nothing.
https://github.com/nspcc-dev/neofs-node/blob/4e361e2ab41602e369edd4feb1dafad99269664c/pkg/services/tree/service.pb.go#L1414

When I use `[]string{"dir", "path", ""}` I get the error:
```
rpc error: code = Unknown desc = invalid signature
```

## Describe the solution you'd like
It would be nice to support finding such nodes.

## Additional context
This can help with handling object keys like `path/to/some/dir/`in [nspcc-dev/neofs-s3-gw.](https://github.com/nspcc-dev/neofs-s3-gw)

**Comment by fyrchik** [comment]
Empty attributes are explicitly prohibited by neofs-api https://github.com/nspcc-dev/neofs-api/blob/f233a2fd6784b696b41741b4bcbb3bedaef2b066/object/types.proto#L110 , it make sense to use the same convention for the tree service API.
Why do you need to use empty path?

**Comment by KirillovDenis** [comment]
We have to handle object names like `some/name/that/emulate/dir/` and be able to differ it from `some/name/that/emulate/dir`

**Comment by fyrchik** [comment]
I wrote some tests and it is already supported, at least in the pilorama itself. `invalid signature` seems to be related to https://github.com/nspcc-dev/neofs-api-go/pull/413
