### ISSUE TITLE
Blobstor may "lose" objects on config changes

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1707]
## Context

`blobovnicza` stores objects in its buckets according to object sizes: it chooses the minimum number (the power of 2) that satisfies the [object limit](https://github.com/nspcc-dev/neofs-node/blob/4e361e2ab41602e369edd4feb1dafad99269664c/config/example/node.yaml#L133). It creates buckets for objects starting from `32<<10` = 32kb, e.g. if the size limit is `100kb`, tree buckets gonna be created: [0:32kb), [32kb:64kb), [64kb:128kb). That buckets will be used for storing and searching objects. Searching will try to iterate buckets according to the [*current* configuration](https://github.com/nspcc-dev/neofs-node/blob/4e361e2ab41602e369edd4feb1dafad99269664c/pkg/local_object_storage/blobovnicza/iterate.go#L31) of the blobovnicza.

## Problem

Consider situation:
1. A Node was configured to store objects with `size<=N`, `N%2==0`
2. It gets objects with `N/2 < size <= N` and stores them in the last of the supported buckets
3. The node goes offline
4. Its config changes and now it gonna store "small" objects only if their `size<=N/2`
5. It gets `Get` with the object from `2.` and could not return it since it does not know about the last bucket it has

Problems:
1. Current implementation could not return object
2. Object is stored but does not satisfy object placement (seems like such objects should be migrated to the FSTree with corresponding metabase changes)

## Ideas
1. Could be solved by just iterating all the buckets it has (but somehow logic with the defined bucket names were implemented, mb it has some nuances, /cc @cthulhu-rider)
2. We could migrate or not migrate objects. If some objects are expected to be stored in a bolt base it could be unexpected to find them in FSTree after the config change (/cc @realloc)

**Comment by cthulhu-rider** [comment]
* `2` will be handled within https://github.com/nspcc-dev/neofs-node/issues/1780
