### ISSUE TITLE
Access denied while eACL allows it

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-node#1710]
In an eacl-public-read-write container I set the below eACL
```
{
    "records": [
        {
            "operation": "DELETE",
            "action": "ALLOW",
            "filters": [],
            "targets": [
                {
                    "role": "OTHERS"
                }
            ]
        },
        {
            "operation": "PUT",
            "action": "DENY",
            "filters": [],
            "targets": [
                {
                    "role": "OTHERS"
                }
            ]
        },
        {
            "operation": "HEAD",
            "action": "DENY",
            "filters": [],
            "targets": [
                {
                    "role": "OTHERS"
                }
            ]
        }
    ]
}
```
Then I try to delete the previously put object on OTHER's behalf. I get the error
```
$ neofs-cli --rpc-endpoint s01.neofs.devenv:8080 --wallet other.json object delete /
    --cid HxqGZknKVNeb1nfHtgfzJBiRYWrc2SmCerrQxG8EFTVr /
    --oid 2wVVUvDMk2tZmDQXUyWWtPFvpTfgyTZ7ddqde4UHiv9T  /
    --config empty_passwd.yml

rpc error: remove object via client: status: code = 1024 message = incomplete object PUT by placement: could not close object stream: (*putsvc.remoteTarget) could not put object to [/dns4/s02.neofs.devenv/tcp/8080]: write object via client: status: code = 2048 message = access to object operation denied
```
The issue isn't stable, sometimes I get another error.

## Expected Behavior
I expect the DELETE is allowed according to eACL.

## Steps to Reproduce (for bugs)

1. Create `eacl-public-read-write` container
2. Put an object
3. Set eACL mentioned above
4. Create another wallet and try to DELETE the object on its behalf

[This test](https://github.com/nspcc-dev/neofs-testcases/blob/master/robot/testsuites/integration/acl/acl_extended_compound.robot) fails

## Your Environment
NeoFS 0.31.0

**Comment by cthulhu-rider** [comment]
Currently you have to allow `PUT` operation too, see the spawn-request table https://github.com/nspcc-dev/neofs-spec/blob/master/01-arch/07-acl.md#extended-acl.

**Comment by roman-khimov** [comment]
Works as intended, changing intentions is #2261.
