### ISSUE TITLE
Simplify neofs-adm code after neo-go v0.99.2 update

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1711]
`actor` package can be useful.
See https://github.com/nspcc-dev/neofs-node/pull/1705#discussion_r949013572

**Comment by fyrchik** [comment]
Morph code can use it too.

**Comment by carpawell** [comment]
Do not forget https://github.com/nspcc-dev/neofs-node/pull/1736#discussion_r957750999.
Use notary actors after https://github.com/nspcc-dev/neo-go/pull/2665.

**Comment by roman-khimov** [comment]
I think we can just create another issue to update again with 0.99.3 release, while here concentrate on 0.99.2 features (that probably solve 80% of problems).
