### ISSUE TITLE
The network map is updated on one of the four nodes only

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#1721]
An unspecified problem with updating the network map on different nodes.
The network map is processed by only one node out of four. 
In this case, after restarting the storage nodes, all nodes receive the current network map.

Step 1:
All nodes have been starter.
Netmap in all nodes:
```
root@az:/etc/neofs/storage# neofs-cli control netmap-snapshot --endpoint localhost:8091 --wallet wallet.json
Enter password > 
Epoch: 926
Node 1: 2A38rHJ982uLUnaj1BHUGHRzAGB7FNnE9DZpXPrHjJUKd ONLINE [/dns4/node4.neofs/tcp/8080]
	Continent: Europe
	Country: Russia
	CountryCode: RU
	Deployed:  NSPCC
	Location: Sheremetyevo Apt/Moscow
	Price: 10
	UN-LOCODE: RU SVO
```

Step 2:
Tick epoch:
```
$ neofs-adm morph force-new-epoch -c configuration/config.yaml
Current epoch: 926, increase to 927.
Waiting for transactions to persist...
```

Step 3:
Nodes 1-3 - Netmap has not been updated.
```
root@az:/etc/neofs/storage# neofs-cli control netmap-snapshot --endpoint localhost:8091 --wallet wallet.json
Enter password > 
Epoch: 926
Node 1: 2A38rHJ982uLUnaj1BHUGHRzAGB7FNnE9DZpXPrHjJUKd ONLINE [/dns4/node4.neofs/tcp/8080]
	Continent: Europe
	Country: Russia
	CountryCode: RU
	Deployed:  SBER
	Location: Sheremetyevo Apt/Moscow
	Price: 10
	UN-LOCODE: RU SVO
```
Node 4 - Netmap has been updated as expected:
```
root@glagoli:/etc/neofs/storage# neofs-cli control netmap-snapshot --endpoint localhost:8091 --wallet wallet.json
Enter password > 
Epoch: 927
Node 1: wfGE7cCjrD7rPRLsoRum6uYDvT8Eohr1zKCHz6rkRbBJ ONLINE [/dns4/node3.neofs/tcp/8080]
	Continent: Europe
	Country: Russia
	CountryCode: RU
	Deployed:  NSPCC
	Location: Sheremetyevo Apt/Moscow
	Price: 10
	UN-LOCODE: RU SVO
Node 2: 21RKdRABDGB8Jpcr7o4yYZ9rum9WSrisfZtge7hJsGcRC ONLINE [/dns4/node1.neofs/tcp/8080]
	Continent: Europe
	Country: Russia
	CountryCode: RU
	Deployed:  NSPCC
	Location: Sheremetyevo Apt/Moscow
	Price: 10
	UN-LOCODE: RU SVO
Node 3: 24uRSr6i1RHcbZTosCjiLU7kS3pbmmpC3xDKqAxZWLdNk ONLINE [/dns4/node2.neofs/tcp/8080]
	Continent: Europe
	Country: Russia
	CountryCode: RU
	Deployed:  SBER
	Location: Sheremetyevo Apt/Moscow
	Price: 10
	UN-LOCODE: RU SVO
Node 4: 2A38rHJ982uLUnaj1BHUGHRzAGB7FNnE9DZpXPrHjJUKd ONLINE [/dns4/node4.neofs/tcp/8080]
	Continent: Europe
	Country: Russia
	CountryCode: RU
	Deployed:  SBER
	Location: Sheremetyevo Apt/Moscow
	Price: 10
	UN-LOCODE: RU SVO

```

If rpc endpoint will be changed in one of the regressed nodes, netmap will not be updated as in case of default rpc endpoints list.
```
  rpc_endpoint:
  - address: ws://node4.neofs:40332/ws
    priority: 1
```

Previously, the cluster was subjected to destructive changes:
- filled up to 150TB 
- blobovnizas and metabases have been removed
- rebuilt the depth of blobovnizas
- 50% metabase recovery (resync) done
- write cache parameters (size limits) have been changed

The problem has not been reproduced before. 
Changing the storage node version to earlier releases does not solve the problem.

Versions:
neo-go - 0.99.1
neofs storage - v0.31.0-10-g5139dc98
neofs ir - v0.31.0-10-g5139dc98

Logs: https://http.t5.fs.neo.org/5EupjhZfG7KqjtsXLkvzySAk94xhHJipENR3faC4vKQ6/logs.tar.gz

UPD: The problem did not reproduce after storage node update up to the latest master head .

**Comment by cthulhu-rider** [comment]
Netmap cache stores values by epoch key. It also stores the last epoch which node received from `NewEpoch` Sidechain event. Processor of `netmap-snapshot` command request reads last epoch value and then read the netmap by the value. There is some delay on notification delivery and handling.

@anatoly-bogatyrev was there some delay between epoch tick command and subsequent healthcheck? Did you try to wait a bit, or state just stucked on `926` epoch?

**Comment by cthulhu-rider** [comment]
Exploration of code responsible for netmap caching refuted the expired cache hypothesis: node responds with the network map by its local epoch value, and latter is synchronized with Sidechain notifications.

Based on this, as well as the analysis of the attached logs, another hypothesis arose: the problem nodes simply did not receive the `NewEpoch` event.

**Comment by cthulhu-rider** [comment]
* similar to https://github.com/nspcc-dev/neofs-node/issues/1755

and according to
> UPD: The problem did not reproduce after storage node update up to the latest master head

the problem is considered irreproducible for now.
