### ISSUE TITLE
Allow to get raw object data from blobstor components, without unmarshaling

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1723]
It can affect stability, thus postpone this until after v0.32.0 is released.
Related #1718.

**Comment by roman-khimov** [comment]
Seems to be a part of #2317.

**Comment by cthulhu-rider** [comment]
> Seems to be a part of https://github.com/nspcc-dev/neofs-node/issues/2317.

definitely. Ive already done this https://github.com/nspcc-dev/neofs-node/commit/2b069f6a8bbc8d193e8a74df968bc09709ad1e8a

missed this issue until now, will open PR
