### ISSUE TITLE
Set neofs-adm timeout values based on protocol settings

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1741]
Currently we hardcode timeout in `awaitTx` https://github.com/nspcc-dev/neofs-node/blob/180e5e938f55a54393c84404f6ea2a9ce1dd270c/cmd/neofs-adm/internal/modules/morph/n3client.go#L80

It would be nice to set it depending on the protocol settings.

**Comment by roman-khimov** [comment]
In fact, any wait loops should use VUB value, that's exactly why it's returned from transaction senders.
