### ISSUE TITLE
Update `neo-go` to `v0.99.3`

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1747]
It will contain (when released) notary actors that should simplify the code.

See #1736 for details (especially https://github.com/nspcc-dev/neofs-node/pull/1736#issuecomment-1233106754 and https://github.com/nspcc-dev/neofs-node/pull/1736#discussion_r957750999).

**Comment by carpawell** [comment]
`v0.99.4` has been released.

**Comment by roman-khimov** [comment]
Long obsolete.
