### ISSUE TITLE
Handle already registered NNS hashed correctly

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1749]
If contract hashes are not equal to the expected ones we just call `AddRecord` that seems like not expected action in our deploys but anyway.

https://github.com/nspcc-dev/neofs-node/blob/17059b34eaa2267752ec0f31de71a97dbd463be6/cmd/neofs-adm/internal/modules/morph/initialize_nns.go#L168-L179

**Comment by fyrchik** [comment]
I think we can remove the logic of checking and just set the record. The checking was done to avoid spending more GAS than needed, but in on-prem installations this is not a problem. Also, the code should become much simpler.
