### ISSUE TITLE
Failed add one node to cluster

### ISSUE THREAD

**Issue by karmadim** [nspcc-dev/neofs-node#1755]
## Steps to Reproduce (for bugs)
1. checking  nodes in the network map. `neofs-cli control netmap-snapshot`. Status of all nodes online and ready 
2. move node s02 to offline status  `neofs-cli control set-status --status offline`
3. forced epoch switch `neofs-adm morph force-new-epoch`
4. stop neofs storage service on node s2
 `sudo systemctl stop neofs-storage.service`. Service in state `inactive (dead)`
5. сreate a new container `neofs-cli container create`. Container created.
6. performing a PUT operation to create an object. Object header validation - successful
7. start neofs-storage service on node s2 `systemctl start neofs-storage.service`. Service in state `active (running)`
8. move node s02 to online status `neofs-cli control set-status --status online`
9. forced epoch switch `neofs-adm morph force-new-epoch`
10. checking  nodes in the network map.

log:
[fd508ae58268233.zip](https://github.com/nspcc-dev/neofs-node/files/9491240/fd508ae58268233.zip)

## Expected Behavior
Node s2 has online and ready statys

## Current Behavior
```
Network status of s2 node is OFFLINE:
`admin@vedi:~$ sudo /usr/bin/neofs-cli control healthcheck --endpoint localhost:8091 --wallet /tmp/s02-wallet.json --config /tmp/s02-config.yaml
Network status: OFFLINE
Health status: READY`
```

## Regression
not sure but looks like

## Your Environment

* Version used:
```
neo-go 0.99.2-2-g536303ef
neofs-cli v0.31.0-85-g17059b34
neofs-authmate v0.23.0-60-g272c485
neofs-node v0.31.0-85-g17059b34
```

* Server setup and configuration: 
cloud, 4 VMs, 4 SN, 4 http qw, 4 s3 gw

* Operating System and version (`uname -a`):
`linux vedi 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux`

**Comment by carpawell** [comment]
@karmadim, have you waited for 1 epoch b/w `7` and `8` steps? `neofs-adm` support epoch tick if you have all the Alphabet wallets.

**Comment by karmadim** [comment]
Hi @carpawell 
Sorry for delay Pavel,
Yes.
Today the issue repeated, here is the fresh log with timestamps regarding online/offline processes:

1. checking nodes in the network map
 `22:50:33 [INFO] HOST: 172.26.161.84
COMMAND:
 sudo /usr/bin/neofs-cli control netmap-snapshot --endpoint localhost:8091 --wallet /tmp/s04-wallet.json --config /tmp/s04-config.yaml
RC:
 0
STDOUT:
 Epoch: 4
 Node 1: jaj2QsRmnvszHwqiKW3uaaK8iwCxSkURHgtUWzz3eGL7 ONLINE [/dns4/node2.neofs/tcp/8080]
 	Continent: Europe
 	Country: Russia
 	CountryCode: RU
 	Deployed: YACZROKH
 	Location: Saint Petersburg (ex Leningrad)
 	Price: 10
 	SubDiv: Sankt-Peterburg
 	SubDivCode: SPE
 	UN-LOCODE: RU LED
 Node 2: k1xwprNYnHXAQ8ybRjTsDdBwpiA3rEwjiLTfdaTQ2k5Z ONLINE [/dns4/node4.neofs/tcp/8080]
 	Continent: Europe
 	Country: Finland
 	CountryCode: FI
 	Deployed: YACZROKH
 	Location: Helsinki (Helsingfors)
 	Price: 10
 	SubDiv: Uusimaa
 	SubDivCode: 18
 	UN-LOCODE: FI HEL
 Node 3: o17E212pCpiMJtyu1bJ15Rq33ESDv9WfzkhozDqVPkR6 ONLINE [/dns4/node3.neofs/tcp/8080]
 	Continent: Europe
 	Country: Sweden
 	CountryCode: SE
 	Deployed: YACZROKH
 	Location: Stockholm
 	Price: 10
 	SubDiv: Stockholms l�n
 	SubDivCode: AB
 	UN-LOCODE: SE STO
 Node 4: vPfgbPVFmezNC3Waudbyk8htSbuTgZir7pkJkcxLNXjF ONLINE [/dns4/node1.neofs/tcp/8080]
 	Continent: Europe
 	Country: Russia
 	CountryCode: RU
 	Deployed: YACZROKH
 	Location: Moskva
 	Price: 10
 	SubDiv: Moskva
 	SubDivCode: MOW
 	UN-LOCODE: RU MOW

STDERR:
`

2. move node s02 to offline
 `22:50:35 [INFO] Execute command "sudo /usr/bin/neofs-cli control set-status --status offline --endpoint localhost:8091 --wallet /tmp/s03-wallet.json --config /tmp/s03-config.yaml" on "172.26.162.31"
22:50:35 [INFO] HOST: 172.26.162.31
COMMAND:
 sudo /usr/bin/neofs-cli control set-status --status offline --endpoint localhost:8091 --wallet /tmp/s03-wallet.json --config /tmp/s03-config.yaml
RC:
 0
STDOUT:
 Network status update request successfully sent.

STDERR:
`

3. forced epoch switch 
`22:50:36 [INFO] Executing shell command: neofs-adm morph force-new-epoch -c /.setup/config.yaml
22:50:47 [INFO] Command completed with output: Current epoch: 4, increase to 5.
Waiting for transactions to persist...

`

3. check nodes in the network map
`22:50:48 [INFO] HOST: 172.26.161.84
COMMAND:
 sudo /usr/bin/neofs-cli control netmap-snapshot --endpoint localhost:8091 --wallet /tmp/s04-wallet.json --config /tmp/s04-config.yaml
RC:
 0
STDOUT:
 Epoch: 5
 Node 1: jaj2QsRmnvszHwqiKW3uaaK8iwCxSkURHgtUWzz3eGL7 ONLINE [/dns4/node2.neofs/tcp/8080]
 	Continent: Europe
 	Country: Russia
 	CountryCode: RU
 	Deployed: YACZROKH
 	Location: Saint Petersburg (ex Leningrad)
 	Price: 10
 	SubDiv: Sankt-Peterburg
 	SubDivCode: SPE
 	UN-LOCODE: RU LED
 Node 2: k1xwprNYnHXAQ8ybRjTsDdBwpiA3rEwjiLTfdaTQ2k5Z ONLINE [/dns4/node4.neofs/tcp/8080]
 	Continent: Europe
 	Country: Finland
 	CountryCode: FI
 	Deployed: YACZROKH
 	Location: Helsinki (Helsingfors)
 	Price: 10
 	SubDiv: Uusimaa
 	SubDivCode: 18
 	UN-LOCODE: FI HEL
 Node 3: vPfgbPVFmezNC3Waudbyk8htSbuTgZir7pkJkcxLNXjF ONLINE [/dns4/node1.neofs/tcp/8080]
 	Continent: Europe
 	Country: Russia
 	CountryCode: RU
 	Deployed: YACZROKH
 	Location: Moskva
 	Price: 10
 	SubDiv: Moskva
 	SubDivCode: MOW
 	UN-LOCODE: RU MOW

STDERR:
`

4. stop neofs storage service on node 
`22:50:48 [INFO] Execute command "sudo systemctl stop neofs-storage.service" on "172.26.162.31"
COMMAND:
 sudo systemctl stop neofs-storage.service
RC:
 0
STDOUT:

STDERR:
`

5. start neofs-storage service on node 
`22:51:25 [INFO] HOST: 172.26.162.31
COMMAND:
 sudo systemctl start neofs-storage.service
RC:
 0
STDOUT:

STDERR:
`

6. move node s02 to online status 
`22:51:27 [INFO] HOST: 172.26.162.31
COMMAND:
 sudo /usr/bin/neofs-cli control set-status --status online --endpoint localhost:8091 --wallet /tmp/s03-wallet.json --config /tmp/s03-config.yaml
RC:
 0
STDOUT:
 Network status update request successfully sent.

STDERR:
`

7. forced epoch switch 
`22:51:28 [INFO] Executing shell command: neofs-adm morph force-new-epoch -c /.setup/config.yaml
22:51:35 [INFO] Command completed with output: Current epoch: 5, increase to 6.
Waiting for transactions to persist...

`

8. check nodes in the network map
`22:51:36 [INFO] HOST: 172.26.161.84
COMMAND:
 sudo /usr/bin/neofs-cli control netmap-snapshot --endpoint localhost:8091 --wallet /tmp/s04-wallet.json --config /tmp/s04-config.yaml
RC:
 0
STDOUT:
 Epoch: 6
 Node 1: jaj2QsRmnvszHwqiKW3uaaK8iwCxSkURHgtUWzz3eGL7 ONLINE [/dns4/node2.neofs/tcp/8080]
 	Continent: Europe
 	Country: Russia
 	CountryCode: RU
 	Deployed: YACZROKH
 	Location: Saint Petersburg (ex Leningrad)
 	Price: 10
 	SubDiv: Sankt-Peterburg
 	SubDivCode: SPE
 	UN-LOCODE: RU LED
 Node 2: k1xwprNYnHXAQ8ybRjTsDdBwpiA3rEwjiLTfdaTQ2k5Z ONLINE [/dns4/node4.neofs/tcp/8080]
 	Continent: Europe
 	Country: Finland
 	CountryCode: FI
 	Deployed: YACZROKH
 	Location: Helsinki (Helsingfors)
 	Price: 10
 	SubDiv: Uusimaa
 	SubDivCode: 18
 	UN-LOCODE: FI HEL
 Node 3: vPfgbPVFmezNC3Waudbyk8htSbuTgZir7pkJkcxLNXjF ONLINE [/dns4/node1.neofs/tcp/8080]
 	Continent: Europe
 	Country: Russia
 	CountryCode: RU
 	Deployed: YACZROKH
 	Location: Moskva
 	Price: 10
 	SubDiv: Moskva
 	SubDivCode: MOW
 	UN-LOCODE: RU MOW

`

Full log: 
[b3bc4759391ad7a7.zip](https://github.com/nspcc-dev/neofs-node/files/9495646/b3bc4759391ad7a7.zip)

**Comment by cthulhu-rider** [comment]
I couldn't reproduce in `neofs-dev-env` with mentioned versions.

First thought was that the request to go `online` could be denied by the Inner Ring. @karmadim can you provide/see `ir` logs?

Example of successful switch:
```
2022-09-06T14:46:39.839Z	info	netmap/handlers.go:48	notification	{"type": "add peer"}
2022-09-06T14:46:39.841Z	info	netmap/process_peers.go:65	approving network map candidate	{"key": "022bb4041c50d607ff871dec7e4cd7778388e0ea6849d84ccbd9aa8f32e16a8131"}
2022-09-06T14:46:39.844Z	debug	client/notary.go:522	notary request invoked	{"method": "addPeerIR", "valid_until_block": 400, "fallback_valid_for": 40, "tx_hash": "29ab031776e5e3a1002283358b900f6ee84f46c7ef81a67a48b39d9a44c4a095"}
```

Other thought (again if problem is on Inner Ring side) is that Inner Ring didn't approve going `online` because of the condition:
https://github.com/nspcc-dev/neofs-node/blob/cd71de69a08d87a63fedd7bc4ead54c4ddac8791/pkg/innerring/processors/netmap/process_peers.go#L62-L64
If `updated == false` - node can't appear in the network map. This case should be considered after if we won't see any errors in logs.

**Comment by cthulhu-rider** [comment]
* possibly related to #1721.

**Comment by karmadim** [comment]
Hi @cthulhu-rider !
the attached logs contain the full output logs from all nodes, and yes, the log from node s03() not all contains the lines you mentioned. When we forced epoch switch on step 7, next ir messages we get from log:

vedi neofs-ir[5129]: 2022-09-05T22:50:45.528Z        info        settlement/calls.go:19        new audit settlement event        {"epoch": 5}
vedi neofs-ir[5129]: 2022-09-05T22:50:45.528Z        info        settlement/handlers.go:14        process audit settlements        {"epoch": 5}
vedi neofs-ir[5129]: 2022-09-05T22:50:45.528Z        info        audit/calculate.go:65        calculate audit settlements        {"current epoch": 5}
vedi neofs-ir[5129]: 2022-09-05T22:50:45.530Z        info        audit/process.go:40        select containers for audit        {"epoch": 5, "amount": 3}
vedi neofs-ir[5129]: 2022-09-05T22:50:45.530Z        info        settlement/handlers.go:18        audit processing finished        {"epoch": 5}
vedi neofs-ir[5129]: 2022-09-05T22:50:45.531Z        info        audit/process.go:70        can't build placement for container, ignore        {"epoch": 5, "cid": "Fk31STfE4Gsm2pxYYkUrWEdQLsisu9sp815ocUdTpoaM", "error": "not enough nodes to SELECT from: 'X'"}
vedi neofs-ir[5129]: 2022-09-05T22:50:45.532Z        info        audit/process.go:70        can't build placement for container, ignore        {"epoch": 5, "cid": "GcFZ2CagGirGQ27dwioXaoXv7jGoLM64p4RT1Ak3Juve", "error": "not enough nodes to SELECT from: 'X'"}
vedi neofs-ir[5129]: 2022-09-05T22:50:45.532Z        info        audit/process.go:70        can't build placement for container, ignore        {"epoch": 5, "cid": "GsEijC5CA5EWnrvb3qjD8SKYQZoT7rhjoHAWgNWGKCPw", "error": "not enough nodes to SELECT from: 'X'"}
сен 05 22:50:49 vedi neofs-ir[5129]: 2022-09-05T22:50:49.609Z        info        container/handlers.go:16        notification        {"type": "container put", "id": "Gc9cHGyyuUtBik2QnYMkJZYRXBC8TCvB95HjwNWiyMDT"}
сен 05 22:51:25 vedi neofs-ir[5129]: 2022-09-05T22:51:25.901Z        info        netmap/handlers.go:48        notification        {"type": "add peer"}
сен 05 22:51:25 vedi neofs-ir[5129]: 2022-09-05T22:51:25.902Z        info        netmap/process_peers.go:65        approving network map candidate        {"key": "02ab80a2f875dab0885be3fa1df8846e0a59d49e623b00cc865d8848534784e931"}
сен 05 22:51:25 vedi neofs-ir[5129]: 2022-09-05T22:51:25.909Z        info        netmap/handlers.go:48        notification        {"type": "add peer"}
сен 05 22:51:33 vedi neofs-ir[5129]: 2022-09-05T22:51:33.552Z        info        netmap/handlers.go:29        notification        {"type": "new epoch", "value": 6}
сен 05 22:51:33 vedi neofs-ir[5129]: 2022-09-05T22:51:33.553Z        info        netmap/handlers.go:48        notification        {"type": "add peer"}
сен 05 22:51:33 vedi neofs-ir[5129]: 2022-09-05T22:51:33.558Z        info        netmap/handlers.go:91        tick        {"type": "netmap cleaner"}
сен 05 22:51:33 vedi neofs-ir[5129]: 2022-09-05T22:51:33.558Z        info        audit/handlers.go:13        new round of audit        {"epoch": 6}
сен 05 22:51:33 vedi neofs-ir[5129]: 2022-09-05T22:51:33.558Z        info        settlement/calls.go:19        new audit settlement event        {"epoch": 6}
сен 05 22:51:33 vedi neofs-ir[5129]: 2022-09-05T22:51:33.558Z        info        settlement/handlers.go:14        process audit settlements        {"epoch": 6}
сен 05 22:51:33 vedi neofs-ir[5129]: 2022-09-05T22:51:33.558Z        info        audit/calculate.go:65        calculate audit settlements        {"current epoch": 6}
сен 05 22:51:33 vedi neofs-ir[5129]: 2022-09-05T22:51:33.558Z        info        audit/process.go:40        select containers for audit        {"epoch": 6, "amount": 3}
сен 05 22:51:33 vedi neofs-ir[5129]: 2022-09-05T22:51:33.558Z        info        settlement/handlers.go:18        audit processing finished        {"epoch": 6}
сен 05 22:51:33 vedi neofs-ir[5129]: 2022-09-05T22:51:33.559Z        info        audit/process.go:70        can't build placement for container, ignore        {"epoch": 6, "cid": "GsEijC5CA5EWnrvb3qjD8SKYQZoT7rhjoHAWgNWGKCPw", "error": "not enough nodes to SELECT from: 'X'"}
сен 05 22:51:33 vedi neofs-ir[5129]: 2022-09-05T22:51:33.560Z        info        audit/process.go:70        can't build placement for container, ignore        {"epoch": 6, "cid": "H5QhgKEM6hDpaABaxp3oLnBEkxvuykiWQHqzhtUD8F74", "error": "not enough nodes to SELECT from: 'X'"}
сен 05 22:51:33 vedi neofs-ir[5129]: 2022-09-05T22:51:33.560Z        info        audit/process.go:70        can't build placement for container, ignore        {"epoch": 6, "cid": "J79wRAD3o5FTk5XLocTPifYzPq2zXJZCQmysqnu999Gm", "error": "not enough nodes to SELECT from: 'X'"}
сен 05 22:51:33 vedi neofs-ir[5129]: 2022-09-05T22:51:33.562Z        info        netmap/handlers.go:48        notification        {"type": "add peer"}


And nothing about addPeerIR:
$ grep "addPeerIR" s03-172.26.162.31:8080-log.txt 
$

**Comment by cthulhu-rider** [comment]
Oh, I've actually missed the attached log :disappointed:  Thanks @karmadim I'll try to find smth :mag:

**Comment by cthulhu-rider** [comment]
I've found log message about approving the status switch request:
```
сен 05 22:51:25 az neofs-ir[5159]: 2022-09-05T22:51:25.867Z        info        netmap/process_peers.go:65        approving network map candidate        {"key": "02ab80a2f875dab0885be3fa1df8846e0a59d49e623b00cc865d8848534784e931"}
``` 
This is exactly the `s03` node which status has been switched.

Right after that we can see epoch tick:
```
сен 05 22:51:33 az neofs-ir[5159]: 2022-09-05T22:51:33.516Z        info        netmap/handlers.go:29        notification        {"type": "new epoch", "value": 6}
```

**Comment by cthulhu-rider** [comment]
@karmadim could you please set Inner Ring log level to `debug` and try to reproduce the problem again.
https://github.com/nspcc-dev/neofs-node/blob/4354359aed86b050ff1138e05ec9e782a3c21363/config/example/ir.yaml#L3-L4

**Comment by karmadim** [comment]
Hi @cthulhu-rider!
Unfortunately or fortunately, on a new build, I also cannot reproduce the issue in our environment. So I'm closing this request as "Not reproduced".
Version used:
ENVIRONMENT
neo-go	0.99.2-2-g536303ef
neofs-authmate	v0.23.0-73-g67b01a30
neofs-cli	v0.31.0-115-g8e8265d5
GoVersion	go1.18.4
AWS		2.2.0

**Comment by anikeev-yadro** [comment]
It replroduced twice on last 2 builds in cloud environment in autotests.

2022-09-10 -  [d9a88fb6393d13dd.zip](https://github.com/nspcc-dev/neofs-node/files/9557086/d9a88fb6393d13dd.zip)
neo-go 0.99.2-2-g536303ef
neofs-authmate v0.23.0-73-g67b01a30
neofs-adm 0.31.0-115-g8e8265d5
neofs-cli 0.31.0-115-g8e8265d5
neofs-http-gw 0.23.0-16-g56e08965
neofs-ir 0.31.0-115-g8e8265d5
neofs-lens 0.31.0-115-g8e8265d5
neofs-node 0.31.0-115-g8e8265d5
neofs-s3-authmate 0.23.0-73-g67b01a30
neofs-s3-gw 0.23.0-73-g67b01a30

2022-09-13 - [a51c8e8ef7e9067a.zip](https://github.com/nspcc-dev/neofs-node/files/9557091/a51c8e8ef7e9067a.zip)
neo-go 0.99.2-2-g536303ef
neofs-authmate v0.23.0-73-g67b01a30
neofs-adm 0.31.0-130-g4083a626
neofs-cli 0.31.0-130-g4083a626
neofs-http-gw 0.23.0-16-g56e08965
neofs-ir 0.31.0-130-g4083a626
neofs-lens 0.31.0-130-g4083a626
neofs-node 0.31.0-130-g4083a626
neofs-s3-authmate 0.23.0-73-g67b01a30
neofs-s3-gw 0.23.0-73-g67b01a30

But unfortunately it didn't reproduce in manual test. 
I think it can possible if we run commands with some timeouts between it. Maybe it is related to something go async.

**Comment by cthulhu-rider** [comment]
@anikeev-yadro thanks for the report.
Inner Ring logs and command list is also required for problem exploration. Could you please attach them?

**Comment by anikeev-yadro** [comment]
I have attached the full logs (journalctl) of all nodes. What do you mean "Inner Ring logs "?
Steps were the same because it was the same autotest.
**Steps to reproduce of 2022-09-10:**
1. checking nodes in the network map. neofs-cli control netmap-snapshot. Status of all nodes online and ready
2. move node s02 to offline status neofs-cli control set-status --status offline
3. forced epoch switch neofs-adm morph force-new-epoch
4. stop neofs storage service on node s2: sudo systemctl stop neofs-storage.service. Service in state inactive (dead)
5. сreate a new container neofs-cli container create. Container created.
6. performing a PUT operation to create an object. Object header validation - successful
7. start neofs-storage service on node s2: systemctl start neofs-storage.service. Service in state active (running)
8. move node s02 to online status neofs-cli control set-status --status online
9. forced epoch switch neofs-adm morph force-new-epoch
10. checking nodes in the network map.

**Steps to reproduce of 2022-09-13:**
1. checking nodes in the network map. neofs-cli control netmap-snapshot. Status of all nodes online and ready
2. move node s03 to offline status neofs-cli control set-status --status offline
3. forced epoch switch neofs-adm morph force-new-epoch
4. stop neofs storage service on node s3: sudo systemctl stop neofs-storage.service. Service in state inactive (dead)
5. сreate a new container neofs-cli container create. Container created.
6. performing a PUT operation to create an object. Object header validation - successful
7. start neofs-storage service on node s3: systemctl start neofs-storage.service. Service in state active (running)
8. move node s03 to online status neofs-cli control set-status --status online
9. forced epoch switch neofs-adm morph force-new-epoch
10. checking nodes in the network map.

**Comment by karmadim** [comment]
after adding the node check for ready to the online status in the test, the problem was solved
