### ISSUE TITLE
Synchronize printing string format of storage node ID

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1765]
Currently we print storage node ID (which is actually its public key) in different formats. For example:
https://github.com/nspcc-dev/neofs-node/blob/cd71de69a08d87a63fedd7bc4ead54c4ddac8791/pkg/innerring/processors/netmap/process_peers.go#L60-L66
https://github.com/nspcc-dev/neofs-node/blob/cd71de69a08d87a63fedd7bc4ead54c4ddac8791/cmd/neofs-cli/modules/control/snapshot.go#L64-L65

While both formats can be casted to each other, it's not really convenient to compare the values visually. I propose to work out for this case and others like it a string format at the convention level. Why conventions? For example, for object/container IDs, a string format is declared at the protocol level.

To conveniently follow the convention, it is proposed to create a special function in the SDK, which will be used whenever it is required to comply with the generally accepted format.

Btw which format do you prefer? For me its hex :sheep:. @fyrchik @carpawell

**Comment by acid-ant** [comment]
Reopened because #1880 still in progress
