### ISSUE TITLE
Killed node doesn't change status to OFFLINE and still presented in network map over 4 epochs

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-node#1767]
After we manually kill the node it doesn't change status to OFFLINE and still presented in network map over 4 epochs.

## Expected Behavior
Killed node change status to OFFLINE in the n+1 epoch
Killed node not presented in map in the n+2 epoch

## Steps to Reproduce (for bugs)
1. Stop VM of node BUKY in cloud (current 133 epoch)
2. Tick epoch
```
anikeev@NB-1670:~/neofs/tatlin-object-sber-tfstate/a_anikeev/configuration$ sudo /home/anikeev/neofs/neofs-testcases/neofs-adm morph force-new-epoch -c config.yaml
Current epoch: 133, increase to 134.
Waiting for transactions to persist...
```
3. Show the network map. Network map dosn't changed.
```
admin@glagoli:~$ sudo neofs-cli --endpoint 127.0.0.1:8091 -w /etc/neofs/storage/wallet.json control netmap-snapshot
Enter password >
Epoch: 134
Node 1: qWygg5EQNf247B7KAL7a8XowpRsm7FKchgJ6KaFxiGYK ONLINE [/dns4/node3.neofs/tcp/8080]
        Continent: Europe
        Country: Sweden
        CountryCode: SE
        Deployed: YACZROKH
        Location: Stockholm
        Price: 10
        SubDiv: Stockholms l�n
        SubDivCode: AB
        UN-LOCODE: SE STO
Node 2: rCNa2Wis4PT8V3ADVgjuzdjeK5UEoAEiua4RSUAbfyz8 ONLINE [/dns4/node2.neofs/tcp/8080]
        Continent: Europe
        Country: Russia
        CountryCode: RU
        Deployed: YACZROKH
        Location: Saint Petersburg (ex Leningrad)
        Price: 10
        SubDiv: Sankt-Peterburg
        SubDivCode: SPE
        UN-LOCODE: RU LED
Node 3: 21EoJZ5ifb6yzYHbrPYiMCaz7de37BbfhjhgCnUYG1fDb ONLINE [/dns4/node1.neofs/tcp/8080]
        Continent: Europe
        Country: Russia
        CountryCode: RU
        Deployed: YACZROKH
        Location: Moskva
        Price: 10
        SubDiv: Moskva
        SubDivCode: MOW
        UN-LOCODE: RU MOW
Node 4: 21W4qGtdumLmswdYmYNfmqmAAUULnMysVGiU7dffjvW3B ONLINE [/dns4/node4.neofs/tcp/8080]
        Continent: Europe
        Country: Finland
        CountryCode: FI
        Deployed: YACZROKH
        Location: Helsinki (Helsingfors)
        Price: 10
        SubDiv: Uusimaa
        SubDivCode: 18
        UN-LOCODE: FI HEL
```
5. Repeat previuos step 3 times. Network map dosn't changed.
6. On the 4th time the node BUKY doesn't present in network map on epoch 138
```
admin@glagoli:~$ sudo neofs-cli --endpoint 127.0.0.1:8091 -w /etc/neofs/storage/wallet.json control netmap-snapshot
Enter password >
Epoch: 138
Node 1: qWygg5EQNf247B7KAL7a8XowpRsm7FKchgJ6KaFxiGYK ONLINE [/dns4/node3.neofs/tcp/8080]
        Continent: Europe
        Country: Sweden
        CountryCode: SE
        Deployed: YACZROKH
        Location: Stockholm
        Price: 10
        SubDiv: Stockholms l�n
        SubDivCode: AB
        UN-LOCODE: SE STO
Node 2: 21EoJZ5ifb6yzYHbrPYiMCaz7de37BbfhjhgCnUYG1fDb ONLINE [/dns4/node1.neofs/tcp/8080]
        Continent: Europe
        Country: Russia
        CountryCode: RU
        Deployed: YACZROKH
        Location: Moskva
        Price: 10
        SubDiv: Moskva
        SubDivCode: MOW
        UN-LOCODE: RU MOW
Node 3: 21W4qGtdumLmswdYmYNfmqmAAUULnMysVGiU7dffjvW3B ONLINE [/dns4/node4.neofs/tcp/8080]
        Continent: Europe
        Country: Finland
        CountryCode: FI
        Deployed: YACZROKH
        Location: Helsinki (Helsingfors)
        Price: 10
        SubDiv: Uusimaa
        SubDivCode: 18
        UN-LOCODE: FI HEL
```

## Regression
maybe

##Logs
[map_bug_glagoli.log.gz](https://github.com/nspcc-dev/neofs-node/files/9524413/map_bug_glagoli.log.gz)
[map_bug_vedi.log.gz](https://github.com/nspcc-dev/neofs-node/files/9524414/map_bug_vedi.log.gz)
[map_bug_az.log.gz](https://github.com/nspcc-dev/neofs-node/files/9524415/map_bug_az.log.gz)

## Your Environment
Product versions:
```
tatlin-object-v0.1.1-nb-20220901.2

NeoFS Storage node
Version: v0.31.0-66-gd8a00c36
GoVersion: go1.18.4

NeoFS Adm
Version: v0.31.0-3-ge07921fc
GoVersion: go1.18.4
```
Server setup and configuration:
```cloud, 4 VMs, 4 SN, 4 http qw, 4 s3 gw```

Operating System and version (uname -a):
```linux vedi 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux```

**Comment by fyrchik** [comment]
Looks similar to #1755 and #1721 .

**Comment by cthulhu-rider** [comment]
Hey @anikeev-yadro :hand:

Nodes don't go `offline` after https://github.com/nspcc-dev/neofs-node/pull/514/commits/b114aebd562fc7f430cee178b22b771d707a331d.

Regarding exclusion from the network map: Inner Ring tracks heartbits from each storage node (sent during application lifetime). Node is considered stale if it hasn't sent heartbit for a certain number of NeoFS epochs. The number is configured on each IR app:
https://github.com/nspcc-dev/neofs-node/blob/cd71de69a08d87a63fedd7bc4ead54c4ddac8791/config/example/ir.yaml#L103 

In the scenario you describe, the behavior is expected. Can you please provide your configuration value mentioned above?

I'm going to re-check the mechanism of node exclusion from the network.

**Comment by cthulhu-rider** [comment]
@anikeev-yadro , everything seems OK.

_If last epoch when node sent heartbit was `E`, and net-exclusion threshold is `T`, then node should be excluded not earlier than `E+T+1` epoch._

Actually node is expected to be excluded in `E+T+2`. One another epoch :thinking:? It is a delay for network map update. Let me explain with an example.

Let exclusion interval be `3`. Let node last showed signs of life in epoch `#10`.
- at epochs `#11-13` node seems to be still alive according to threshold
- starting from epoch `#14` the Inner Ring considers the node to be "dead" :skull: 
- according to this the Inner Ring votes for the node exclusion :ballot_box: (let it happen immediately in epoch `#14`)
- node will disappear from the network map at the time of the release of its next version, that is, in epoch `#15` :bomb:

**Comment by anikeev-yadro** [comment]
> In the scenario you describe, the behavior is expected. Can you please provide your configuration value mentioned above?
> I'm going to re-check the mechanism of node exclusion from the network.
My environment has the default value (3)

**Comment by cthulhu-rider** [comment]
> My environment has the default value (3)

Behavior is expected then.
