### ISSUE TITLE
Tree service discovery

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1768]
Tree service is an optional service. Not sure it will stay optional, but now it is. Clients want to discover if tree service is enabled on remote node for early failures (see https://github.com/nspcc-dev/neofs-s3-gw/issues/699). Clients can't rely on `Dial` invocations, because tree service lives on the same socket as NeoFS API. 

I see such options how tree service can be discovered
1) Provide dummy RPC to check if server returns error
2) Use existing RPC as dummy to check if server returns error
3) Enable [server reflection](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md).

I think (3) is an overhead and more suitable for debug purposes rather than using it in production.
(1) looks better than (2) for me, but requires protocol update.

**Comment by fyrchik** [comment]
Let's implement a separate healthcheck method.
