### ISSUE TITLE
neofs-cli search operation with --filter does not operate with object id

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#177]
neofs-cli search operation with --filter does not operate with object id.

For example for object FM4vHDMDGN2ESBwFgK9cBfrgp2F26xPfA8ysBgtnaVjS with headers:
`{"objectID":{"value":"1Sep9/aMFvx9y/kn4x+vy29sWpqPYLzVBd8iM7L5tiU="},"signature":{"key":"AgsHtCnrUUyZDtJMMUXqDuSNl1pNNaqjVgJ8fJ9kme2N","signature":"BIXS1CLrPUlsmot96xory2o0fBxTMBU62ULcenlgcffzJ3H3wl/CxlJygdm7QDAL2cf6ECl3TqTUix72rLBopJg="},"header":{"version":{"major":2,"minor":0},"containerID":{"value":"5UCvtrxiFLRZshssllLlzYJL8LPLAv8ubJDMTcnaUZ4="},"ownerID":{"value":"NeMOrwz/s6pJpbz3iuxvjRAb2ulLdNSB4w=="},"creationEpoch":"46","payloadLength":"20000000","payloadHash":{"type":"SHA256","sum":"4uAFRMGh+kff29mO/rbFPmfqz7bBxkVN/xAxZvJv+cY="},"objectType":"REGULAR","homomorphicHash":{"type":"TZ","sum":"frFCPV2/1YDrABHsg3maDn061aCbbXK1+AhK6cP5jeooYqGYV/O72FxTMBkQjj+rUpeksQIc6mPrZpsC/ePQnQ=="},"sessionToken":{"body":{"id":"6DreJiJBTzqW0gbt9ZdYew==","ownerID":{"value":"NeMOrwz/s6pJpbz3iuxvjRAb2ulLdNSB4w=="},"lifetime":{"exp":"0","nbf":"0","iat":"0"},"sessionKey":"AgsHtCnrUUyZDtJMMUXqDuSNl1pNNaqjVgJ8fJ9kme2N","object":{"verb":"PUT","address":{"containerID":{"value":"5UCvtrxiFLRZshssllLlzYJL8LPLAv8ubJDMTcnaUZ4="},"objectID":null}}},"signature":{"key":"AkfmbTvwi++QggnbMcifHtQpW4fkaB1KlblI0/scf6gC","signature":"BL1y0JgSD6BJdBQqth1mvFXeHbMWB2vAiqpkAuS6/njfXlk6f3p6puRgyFXl8yaw48B9lxh+kniivbQsB9V6hng="}},"attributes":[{"key":"key1","value":"1"},{"key":"key2","value":"abc"},{"key":"FileName","value":"b8c2cbc8-48db-418e-ab25-438553013bb8"},{"key":"Timestamp","value":"1605657650"}],"split":null},"payload":""}`

```
neofs-cli --rpc-endpoint s03.neofs.devenv:8080 --key L2GseHKsbhXZFa9xXaUPXErhxPRQs2vgnH5ie6aFVP1kG2keNCHV  --ttl 1 object search --root --cid GRuaANbC7pyiG7qEsyK1odTAnk1qN4muTECRPJeogV6u --filters objectID=9uk6MGNQ87LiH2JhtEyLYrTGR3keGj2NZtC1roVyEsjP
Found 0 objects.
```

```
neofs-cli --rpc-endpoint s03.neofs.devenv:8080 --key L2GseHKsbhXZFa9xXaUPXErhxPRQs2vgnH5ie6aFVP1kG2keNCHV  --ttl 1 object search --root --cid GRuaANbC7pyiG7qEsyK1odTAnk1qN4muTECRPJeogV6u --filters key1=1
Found 1 objects.
FM4vHDMDGN2ESBwFgK9cBfrgp2F26xPfA8ysBgtnaVjS
```

**Comment by cthulhu-rider** [comment]
This is a bug on the node side.

**Comment by cthulhu-rider** [comment]
@anatoly-bogatyrev, `objectID=XXX` usage in your scenario is incorrect since object ID filter key is `$Object:objectID`.
