### ISSUE TITLE
Storage node was not started because it has not enough gas

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-node#1779]
I have restarted storage node service after I added new shard to config.

## Expected Behavior
Storage node restarted successfully.

## Current Behavior
Storage node was not started because it has not enough gas.

## Steps to Reproduce (for bugs)
Restart storage node service.

[node_not_start.log.gz](https://github.com/nspcc-dev/neofs-node/files/9549545/node_not_start.log.gz)

**Versions:**
```
tatlin-object-v0.1.1-nb-20220912.1
NeoFS Storage node
Version: v0.31.0-115-g8e8265d5
GoVersion: go1.18.4
```
**Server setup and configuration:**
cloud, 4 VMs, 4 SN, 4 http qw, 4 s3 gw

**Operating System and version (uname -a):**
linux vedi 5.10.0-16-amd64 https://github.com/nspcc-dev/neofs-node/issues/1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux

**Comment by fyrchik** [comment]
The problem exists, but I wasn't able to reproduce it on a dev-env: GAS distributes much faster that I am able to restart container manually. I will try this with 8-sec block.

**Comment by roman-khimov** [comment]
This hasn't reproduced for a long time and we'll fix some GAS leakages soon anyway.
