### ISSUE TITLE
ACL - Inner Ring PUT/GET operation to the private container 

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#178]
In the previous NeoFS version attempt to PUT/GET an object into a private container from the Inner Ring key was impossible.

In the current version of the NeoFS ACL, it is possible to PUT not only for the container nodes (SYS group) but also for the inner ring nodes.

Do we think this behavior is correct for the current version of NeoFS?

For example for container with basic ACL 0x1C8C8CCC:

```
$ neofs-cli --rpc-endpoint s01.neofs.devenv:8080 --key <INNER RING KEY> object put --file 31bec1f6-9d84-4d92-b9ca-1ed97b91319a --cid 6fWrinptxkQWfNr7qFExmHViz4Wb5ctVMdZFBQ1QhAVy 
[31bec1f6-9d84-4d92-b9ca-1ed97b91319a] Object successfully stored
  ID: 4mo44oJ4KeG6w3YM7HA9XmrLXBoEaT8mN8wAqgabCbi6
  CID: 6fWrinptxkQWfNr7qFExmHViz4Wb5ctVMdZFBQ1QhAVy

```

**Comment by alexvanin** [comment]
Indeed, there is no such check in the node right now. Don't think we need to change this behavior since we already agreed on it and implemented in previous version.

However it would be great to have a comment about this in ACL specification when it will be ready.
/cc @realloc

**Comment by realloc** [comment]
InnerRing check has to be implemented in nearest releases.

IR is part of System class, but it doesn't require access to object's payload, so it must be limited to operations required for Data Audit.
