### ISSUE TITLE
Add neofs-cli GetRange operation

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#179]
It would be great to add a neofs-cli GetRange operation with --range flag for neofs-cli get command.

**Comment by alexvanin** [comment]
What about output of this command? There are a few options:
- dump binary range to a file (pretty much like get),
- print hex encoded output,
- print binary output.

**Comment by anatoly-bogatyrev** [comment]
Any option is suitable, iа it will be a part of the `neofs-cli object get` command, then the option with saving to a file looks more logical.
