### ISSUE TITLE
Storage node can register in the network with any status

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1796]
Storage nodes register in the NeoFS network via sending the bootstrap requests. Alphabet (subset of Inner Ring) validates the information provided by each storage node and decides access to the network. Network map consists of online storage nodes only. 

## Expected Behavior
* Inner Ring allows storage nodes to join the network with `ONLINE` state
* Inner Ring disallows storage nodes to join the network any state other than `ONLINE`

## Current Behavior
Inner Ring accepts storage nodes with any state.

## Possible Solution
Check the state during validation.

## Steps to Reproduce (for bugs)
1. cut/comment the instruction https://github.com/nspcc-dev/neofs-node/blob/d6fef68a62ad26cf9d7a7824b16768bedc571395/cmd/neofs-node/config.go#L565
2. build dirty image of storage node app `make bin/neofs-node && make image-dirty-storage`
3. run NeoFS Developer [Environment](https://github.com/nspcc-dev/neofs-dev-env) with the built version using `make up/basic`
4. exec `$ neofs-cli --endpoint s01.neofs.devenv:8081 --wallet services/storage/wallet01.json control netmap-snapshot`
5. see offline nodes in the network map
```
Epoch: 2
Node 1: eQEUoc2DRn4oNnNUxs8iviWJYrYS4mTBsgQqjJ44aFyJ OFFLINE [/dns4/s01.neofs.devenv/tcp/8080]
	Continent: Europe
	Country: Russia
	CountryCode: RU
	Location: Moskva
	Price: 22
	SubDiv: Moskva
	SubDivCode: MOW
	UN-LOCODE: RU MOW
	User-Agent: NeoFS\/0.26
Node 2: o5H2uGUa7cwBvb1GSx62SUL8Mkpp4PbgB1oUstPgnfo8 OFFLINE [/dns4/s03.neofs.devenv/tcp/8080]
	Continent: Europe
	Country: Sweden
	CountryCode: SE
	Location: Stockholm
	Price: 11
	SubDiv: Stockholms l�n
	SubDivCode: AB
	UN-LOCODE: SE STO
	User-Agent: NeoFS\/0.26
Node 3: 249VqsrQDNv8X7bYHTUH86ZqRJKogJnAeovMmCqMqM3u6 OFFLINE [/dns4/s04.neofs.devenv/tcp/8082/tls /dns4/s04.neofs.devenv/tcp/8080]
	Continent: Europe
	Country: Finland
	CountryCode: FI
	Location: Helsinki (Helsingfors)
	Price: 44
	SubDiv: Uusimaa
	SubDivCode: 18
	UN-LOCODE: FI HEL
	User-Agent: NeoFS\/0.26
Node 4: 2Bsv2nitVMDi9S77fuYNqDeYtRHcxAmp1J6Q7Hx79Wwem OFFLINE [/dns4/s02.neofs.devenv/tcp/8080]
	Continent: Europe
	Country: Russia
	CountryCode: RU
	Location: Saint Petersburg (ex Leningrad)
	Price: 33
	SubDiv: Sankt-Peterburg
	SubDivCode: SPE
	UN-LOCODE: RU LED
	User-Agent: NeoFS\/0.26
```

## Regression
No. Bug is very old.

## Your Environment
* NeoFS Storage node: `neofs-node@v0.32.0`
* NeoFS CLI: `neofs-cli@v0.32.0` 
* NeoFS Developer Environment: `neofs-dev-env@c4ceb1c5854816cebcf23580853fda294c2d2c60`

**Comment by fyrchik** [comment]
What about MAINTENANCE status?
