### ISSUE TITLE
Improve `make image-dirty-storage`

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1799]
I have encountered an interesting issue:
```
dzeta@wpc ~/r/neofs-node (shard-evacuate-network)> make image-dirty-storage
⇒ Build NeoFS dirty-storage docker image
Sending build context to Docker daemon  7.406GB
```

I had a 10GB file in the root repo. I am not sure we can avoid this, because untracked files can take part in the build, but let's at least discuss.

**Comment by carpawell** [comment]
Does the agreement about temporary files in [docker](https://github.com/nspcc-dev/neofs-node/blob/bb02913c3915dfb2c58866c802e202c1e77ad8a5/.dockerignore#L6) and [git](https://github.com/nspcc-dev/neofs-node/blob/3df98ce7ba67da83631e36c2e52c7f5f85b850f7/.gitignore#L13-L14) help with that?

**Comment by fyrchik** [comment]
I guess you are right, missed that, just was unexpected.
