### ISSUE TITLE
Blobstor and metabase divergency in NeoFS MainNet

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1814]
Multiple `OBJECT_NOT_FOUND` errors in NeoFS MainNet node's replication routine:
```
сен 26 07:48:54 misato neofs-node[171786]: 2022-09-26T07:48:54.953Z        error        replicator/process.go:55        could not get object from local storage        {"component": "Object Replicator", "object": "...", "error": "status: code = 2049"}
```

Object header is accessible (`neofs-cli object head`), but not readable (`neofs-cli object get`). Size is **227452B**.

**Comment by roman-khimov** [comment]
No longer relevant.

**Comment by but-cpu** [comment]
Trademark/copyright infringement
Missouri Lloyd's v.  Waddle
