### ISSUE TITLE
Provide writing of a single object to the metabase

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1816]
## Is your feature request related to a problem? Please describe.
I can't add single object (e.g. stored in file) to the metabase using CLI. The only thing I can do is to re-sync the metabase with the blobstor on `neofs-node` startup.

## Describe the solution you'd like
```
$ neofs-lens meta write --obj $OBJ_PATH --path $META_DST
Object has been successfully written to the metabase.
```

## Describe alternatives you've considered
Not yet.

## Additional context
I tried to push an object into a node by writing it into the node's FSTree. That wasn't enough since I also needed to add a record to the metabase. I could also turn any shard to degraded mode, but that wasn't an option in my case.  So the only thing I could do is to restart storage node with metabase re-sync.

**Comment by carpawell** [comment]
How about a new RPC to the `control` service? It could check the correctness of the object (marshaling, required fields check, etc) and put that according to Storage Engine rules (correct shard, correct indexing, correct notification/lock/removal flows).

Looks weird but anyway we already allow dropping *any* object if you **control** the node despite any policy/logic/other thoughts.

**Comment by carpawell** [comment]
And, moreover, that CLI has been called "lens" for some reason.

**Comment by cthulhu-rider** [comment]
> And, moreover, that CLI has been called "lens" for some reason.

`lens` name does not block the application to perform writing operations. The name was chosen as pretty short and laconic, but not to limit functionality.

**Comment by cthulhu-rider** [comment]
> How about a new RPC to the control service?

@carpawell `Control` service LGTM to prevent application shutdown (its process locks all metabases). What about "offline" cases? I think simple read-write command can also be useful.

**Comment by carpawell** [comment]
> lens name does not block the application to perform writing operations

Well, i was not thinking about naming only: the general purpose for that CLI looked as read-only for me but i could be wrong.

> What about "offline" cases?

If we are possible to face such cases, `neofs-lens meta write` could be useful of course. But generally speaking, do not know when it could happen.
