### ISSUE TITLE
Some nodes don't return an objects list after the network of 4 nodes is splitted into 2x2

### ISSUE THREAD

**Issue by ikovalev1** [nspcc-dev/neofs-node#1826]
## Steps to Reproduce (for bugs)

0) there is 4 nodes network
1) create an container
`root@az:~# neofs-cli --rpc-endpoint node1.neofs:8080 --wallet //home/admin/wallet.json container create --policy "REP 2 IN X  SELECT 2 FROM * AS X" --await
Enter password >
container ID: BUBeo2CRW5YkLRVA8MYpLp8BhCEKDekVzwqhc846P6U3
awaiting...
container has been persisted on sidechain
`

2) put an object
`root@az:~# neofs-cli --rpc-endpoint node1.neofs:8080 -w /home/admin/wallet.json  object put --file /home/admin/file1.txt --no-progress  --cid  BUBeo2CRW5YkLRVA8MYpLp8BhCEKDekVzwqhc846P6U3
Enter password >
[/home/admin/file1.txt] Object successfully stored
  OID: J2rnZKeJuyJSn4cW1A8kz1r9cHEpejGP3k4YECfCAykN
  CID: BUBeo2CRW5YkLRVA8MYpLp8BhCEKDekVzwqhc846P6U3
`

3) get the object list on all 4 nodes (ok on all nodes)
`
root@az:~# neofs-cli --rpc-endpoint node1.neofs:8080 -w /home/admin/wallet.json  container list-objects --cid BUBeo2CRW5YkLRVA8MYpLp8BhCEKDekVzwqhc846P6U3
Enter password >
J2rnZKeJuyJSn4cW1A8kz1r9cHEpejGP3k4YECfCAykN
root@az:~#
`

4) split the network into 2 parts:
on node 1 & 2: run
`
root@az:~# route add  node3 reject; route add  node4 reject
root@buky:~# route add  node3 reject; route add  node4 reject
`

5) get the object list on all nodes
node 1&2 - ok
node3&4 - error:
`
root@vedi:/home/admin#  neofs-cli --rpc-endpoint node3.neofs:8080 -w /home/admin/wallet.json  container list-objects --cid BUBeo2CRW5YkLRVA8MYpLp8BhCEKDekVzwqhc846P6U3
Enter password >
rpc error: read object list: context deadline exceeded
`
## My envorenment 

Server setup and configuration:
cloud, 4 VMs, 4 SN, 4 http qw, 4 s3 gw

### Versions:

root@az:~# neofs-node -version
NeoFS Storage node
Version: v0.32.0
GoVersion: go1.18.4

root@az:~# neofs-cli  --version
NeoFS CLI
Version: v0.32.0
GoVersion: go1.18.4

**Comment by fyrchik** [comment]
The problem is in the CLI itself -- the timeout is less than the one used by node.
I think 2 things are worth doing here:
1. Allow to set timeout in the CLI (should be global flag for all commands).
2. Parallelize search operation, so that the actual time spent waiting is less.
