### ISSUE TITLE
Block or transaction validation failed. (-504) - fallback transaction is valid after deposit is unlocked: ValidUntilBlock is 348900, deposit lock expires at 347724

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#1828]
On attempt to create container operation the error occurs periodically:

$ neofs-cli -r st1.t5.fs.neo.org:8080 -w client.json container create --policy 'REP 2 IN X CBF 2 SELECT 2 FROM F AS X FILTER "Deployed" EQ "NSPCC" AS F' --basic-acl public-read --await
Enter password > 
put container rpc error: status: code = 1024 message = Block or transaction validation failed. (-504) - fallback transaction is valid after deposit is unlocked: ValidUntilBlock is 348900, deposit lock expires at 347724

**Comment by mike-petrov** [comment]
I may have noticed a behavior that causes this error: creating containers from one wallet at the same time from two different terminals

<img width="851" alt="image" src="https://user-images.githubusercontent.com/32885629/196987961-a72e6e5c-d9ba-4403-baff-8a7aa5c9d8f1.png">

**Comment by carpawell** [comment]
Closed via #2121.
