### ISSUE TITLE
Add config fields for node well-known attributes

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1850]
Stringified format is cumbersome to specify.

As an example, we recently introduced `ExternalAddr` which should contain comma-delimited list of multiaddresses.
I think a nicer way to do this is as follows:
```
external_addr:
  - endpoint1:12345
  - endpoint2:54321
attribute_0: ...
```

The node should:
1. Validate fields present in this manner (`attribute_*` fields can remain unvalidated).
2. Transform this addresses to a multiaddresses and pack them into a single attribute.
3. Raise an error if an attribute is specified via both fields.

We already do this for subnets, let's think of what else we can implement here.

**Comment by cthulhu-rider** [comment]
>  let's think of what else we can implement here

@fyrchik what do you mean? Is there anything else that can be done?

**Comment by roman-khimov** [comment]
Not likely.
