### ISSUE TITLE
Add IR control service call for node removal

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-node#1866]
For testing purposes and for on-prem installations it may be useful to quickly remove a storage node from Netmap.
This must be done via Control API call and produce a notary type Tx invocation of corresponding contract method.

Technically it could be a temporary in-memory list of nodes marked for removal on each IR node so that required IR majority could collect the multisig.

**Comment by carpawell** [comment]
Why not `neofs-adm`?

**Comment by realloc** [comment]
This feature has to work without access to all IR keys. For example, as a reaction from some external monitoring system.
Possible use case:
- Some IR companion daemon detects a Storage Node misbehaving or dead
- If it makes no sense to wait for the timeout, it adds that node to the removal list using local IR control API
- Subjected node gets removed. Maybe with optional Epoch change.

**Comment by carpawell** [comment]
What that Call is expected to do? Just send a notary request? So we do not know all the alphabet keys but are able to send n*2/3+1 control calls to the Alphabet nodes (in practice -- with using their keys), right?

**Comment by realloc** [comment]
In practice this should be a collective effort. Each IR manages its local list and then the IR majority can do the force removal.

**Comment by roman-khimov** [comment]
Similar to #2661 in many ways.

**Comment by roman-khimov** [comment]
Depends on #2088.

**Comment by roman-khimov** [comment]
Done
