### ISSUE TITLE
'flush cache' command reported OK, but actually cache was not flushed because it was in READ-ONLY mode.

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-node#1905]
Now we have I hidden write-cache mode. From the system administrator side it is not correclty. Because the admin cannot see the overall status of the system. And he have not obviously errors in log

## Expected Behavior
If write-cache is in READ-ONLY mode we should report somethink like this "Operation not possible in write-cache READ-ONLY mode".

## Current Behavior
We returned ```Write-cache has been flushed```, but actually write-cache was in READ-ONLY mode and we got a lot of errors in log.

## Steps to Reproduce (for bugs)
1. Run the command to flush cache while it is in READ-ONLY mode:
```
root@az:/srv/neofs# sudo neofs-cli --endpoint 127.0.0.1:8091 -w /etc/neofs/storage/wallet.json control shards flush-cache --id MnaJVa2bAqANyXabcajLWQ,KNqV3sT3nSFQKMan7w54QH
Enter password >
Write-cache has been flushed.
```
2. See the rrros in log:
```
Oct 17 08:49:42 az sudo[1559]:     root : TTY=pts/0 ; PWD=/srv/neofs ; USER=root ; COMMAND=/usr/bin/neofs-cli --endpoint 127.0.0.1:8091 -w /etc/neofs/storage/wallet.json control shards flush-cache --id MnaJVa2bAqANyXabcajLWQ,KNqV3sT3nSFQKMan7w54QH
Oct 17 08:49:45 az neofs-node[644]: 2022-10-17T08:49:45.312Z        error        shard/delete.go:43        can't delete object from write cache        {"shard_id": "MnaJVa2bAqANyXabcajLWQ", "error": "write-cache is in read-only mode"}
Oct 17 08:49:45 az neofs-node[644]: 2022-10-17T08:49:45.313Z        error        shard/delete.go:43        can't delete object from write cache        {"shard_id": "MnaJVa2bAqANyXabcajLWQ", "error": "write-cache is in read-only mode"}
Oct 17 08:49:45 az neofs-node[644]: 2022-10-17T08:49:45.313Z        error        shard/delete.go:43        can't delete object from write cache        {"shard_id": "MnaJVa2bAqANyXabcajLWQ", "error": "write-cache is in read-only mode"}
Oct 17 08:49:45 az neofs-node[644]: 2022-10-17T08:49:45.313Z        error        shard/delete.go:43        can't delete object from write cache        {"shard_id": "MnaJVa2bAqANyXabcajLWQ", "error": "write-cache is in read-only mode"}
Oct 17 08:49:45 az neofs-node[644]: 2022-10-17T08:49:45.313Z        error        shard/delete.go:43        can't delete object from write cache        {"shard_id": "MnaJVa2bAqANyXabcajLWQ", "error": "write-cache is in read-only mode"}
...
```

**Versions:**
```
NeoFS Storage node
Version: v0.32.0-121-gade19077
GoVersion: go1.18.4
```
## Your Environment
Server setup and configuration:
cloud, 4 VMs, 4 SN, 4 http qw, 4 s3 gw

Operating System and version (uname -a):
linux vedi 5.10.0-16-amd64 https://github.com/nspcc-dev/neofs-node/issues/1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux

**Comment by fyrchik** [comment]
Flushing is possible if write-cache is read-only because we only read objects.
Error messages in logs are unrelated -- it is GC worker who tries to delete objects. I suggest lowering the error level here and also check if an object exists first.
