### ISSUE TITLE
Add support visibility of Session Service activity in logs

### ISSUE THREAD

**Issue by vkarak1** [nspcc-dev/neofs-node#1930]
## Is your feature request related to a problem? Please describe.

Could you please add ability to check SessionService activity in logs, it will help at least to sort [this](https://github.com/nspcc-dev/neofs-node/issues/1865) issue out

## Describe the solution you'd like
It would be great to see SessionService activity in journalctl neofs-storage.service

**Comment by cthulhu-rider** [comment]
Of course, we can add logs without any problems. However, if you want to rely on messages for any checks, the message format should be fixed and documented. Currently, application logging does not guarantee this. How can we link a log entry to a specific `neofs-cli` command being executed?

**Comment by fyrchik** [comment]
I think we can (1) add `--verbose` flag for cli and (2) DEBUG logs in the service itself.
