### ISSUE TITLE
Allow removing all trees by container ID

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1940]
[Cleaning line](https://github.com/nspcc-dev/neofs-node/blob/7d456cb4d0c5381020b4bd76bfc9c5ab5683f90a/cmd/neofs-node/tree.go#L58) looks buggy. I doubt the `pilorama` [removes](https://github.com/nspcc-dev/neofs-node/blob/7d456cb4d0c5381020b4bd76bfc9c5ab5683f90a/pkg/local_object_storage/pilorama/boltdb.go#L611) all existing trees.

**Comment by fyrchik** [comment]
Closed via #2027
