### ISSUE TITLE
Adopt `neo-go@v0.99.4` changes

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1955]
* `neo-go` was bumped in #1947.

There were fixed some breakages which didn't allow project to compile. New version also deprecated some of the approaches. We should adopt the deprecated code according to the suggestions.

P.S. I've tried to do this on the fly, but realized that deeper sight is needed.

**Comment by roman-khimov** [comment]
This one seems to be fixed to me (NeoFS compiles with 0.100.1 and work), there are just two pre-0.99.4 APIs in neofs-adm, but that's #2217/#2218 and also a bunch of things in `morph/client`, but those are post-0.99.4 (#2219).
