### ISSUE TITLE
cli: `PrintVerbose` writes to stdout instead of command out

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1962]
https://github.com/nspcc-dev/neofs-node/blob/41f93dcc1dea5001a5674c37847fdca4d6280ab1/cmd/neofs-cli/internal/common/verbose.go#L18
Is it expected? I think we should write all the data to commands' streams.

**Comment by carpawell** [comment]
IMO, that is a bug, @fyrchik.
