### ISSUE TITLE
Complex object sometimes can't be deleted when bearer token is attached

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1970]
I am trying to upload and delete object with bearer token. I use wallets from neofs-dev-env:
- `wallets/wallet.json` as container owner,
- `services/s3_gate/wallet.json` as request sender.

**Sometimes** I can't delete object in the container with `object not found` error. I think it is related to object placement somehow. Logs of storage node when it was reproduced attached below.

## Expected Behavior
Object is being removed.

## Current Behavior
Node returns 2049 code:
```                                                                                                                                
rpc error: remove object via client: status: code = 2049 message = object not found
```

If I try to remove object **without** bearer token, it works fine.

```
neofs-cli object delete --cid GAkzy37rmSyzvdseMQ1Qu2m1D5wbYtTBtNxNghN9DXUd \
  --oid 9kAbNrV8v7a1PJ2rYiuouo62pJjDB63L4jmmap8CndxG \
  -w services/s3_gate/wallet.json \
  -r s01.neofs.devenv:8080
Enter password > 
Object removed successfully.
  ID: E7s2x5d7pg8pwNJwZguzvaWU7VrwctrcDnCYsuzE5Mw
  CID: GAkzy37rmSyzvdseMQ1Qu2m1D5wbYtTBtNxNghN9DXUd
```

## Steps to Reproduce (for bugs)
1) Start dev-env. I also reduce max object size to 1MB so it works faster 

```
make up/basic && make update.max_object_size val=1000000 && make prepare.ir
```

2) Create container of 4 nodes with allowing basic ACL.

```
neofs-cli container create -p "REP 1 IN X CBF 1 SELECT 4 FROM * AS X" \
  --basic-acl eacl-public-read-write \
  -r s01.neofs.devenv:8080 \
  -w wallets/wallet.json
```

3) Sign bearer token for all containers. Bearer token for `services/s3_gate/wallet.json` is attached to this issue.

```
neofs-cli util sign bearer-token --from b.json --to b.signed.json --json -w wallets/wallet.json
```

4) Upload complex object into container
```
neofs-cli object put --cid GAkzy37rmSyzvdseMQ1Qu2m1D5wbYtTBtNxNghN9DXUd \
  --file ./10m \
  -w services/s3_gate/wallet.json \
  -r s01.neofs.devenv:8080 \
  --bearer ./b.signed.json
```

5) Try to delete complex object from container

```
neofs-cli object delete --cid GAkzy37rmSyzvdseMQ1Qu2m1D5wbYtTBtNxNghN9DXUd \
  --oid 9kAbNrV8v7a1PJ2rYiuouo62pJjDB63L4jmmap8CndxG \
  -w services/s3_gate/wallet.json \
  -r s01.neofs.devenv:8080 \
  --bearer ./b.signed.json                               
```

## Context
It seems it causes https://github.com/nspcc-dev/neofs-s3-gw/issues/727 when S3 gateway can't delete multipart if it is complex object.

## Your Environment
neofs-node: v0.33.0-68-g9a082476
neofs-dev-env: 86a36a3ff430ae17845564c0c5f6ee6fa312ce34

[s01-delete-logs.txt](https://github.com/nspcc-dev/neofs-node/files/9862068/s01-delete-logs.txt)
[b.json](https://github.com/nspcc-dev/neofs-node/files/9862070/b.json.txt)

**Comment by anikeev-yadro** [comment]
https://github.com/nspcc-dev/neofs-node/issues/1978

**Comment by carpawell** [comment]
Could not reproduce on some _general_ scenarios (`...SELECT 4...`, big objects, different combinations of the nodes to send requests to).

**Comment by alexvanin** [comment]
Seems like it was fixed with https://github.com/nspcc-dev/neofs-node/pull/1989.
