### ISSUE TITLE
Tree-service issue on unplug disk operation (object not found response from target s3-gw)

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#1983]
There is a suspicion that disabling the data disk leads to the death of the local tree-service.

- the load has been applied to the cluster (read / write) on s3-gw
- data disk (hdd) has been disabled (emulates disk death)
- all GET requests to s3-gw on the node where the disk was disabled return object not found error.
- at the same time, similar requests to other nodes pass without any issues and the objects are found.

Versions:
node - v0.33.0-62-g713fdab1 
s3-gw - v0.24.0-23-g821df3d6

Logs:
- first the disk was disabled on buky, then on vedi.
- [Link to log.tar](https://drive.google.com/file/d/1Lq8SP1TzJ7t0t1af8p6UtPHJ2fpewACI/view?usp=sharing)

**Comment by fyrchik** [comment]
Was the pilorama also on this disk?

**Comment by anatoly-bogatyrev** [comment]
No, pilarama was on the meta (ssd disk)

**Comment by anikeev-yadro** [comment]
It was not reproduced on the last builds.
