### ISSUE TITLE
PUT operations hang on disabled/dead hdd disk

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#1985]
When unplug/disabled a disk and generating a load flow through k6, there is a strong drop in performance on the PUT operation. 

When errors accumulate, the disk (data, hdd) goes into the "Mode: degraded-read-only" state.
At the same time, some of the requests from k6 end up on the target node and, apparently, the requests begin to hang for a very long time before the timeout occurs. Which leads to the fact that more and more k6 workers hang with such requests. At the same time, the performance for PUT requests drops to almost zero.

It is necessary to correctly handle disk death or shard mode.

Versions:
node - v0.33.0-62-g713fdab1
s3-gw - v0.24.0-23-g821df3d6

![image](https://user-images.githubusercontent.com/45566606/198039473-f3b7e68f-ab71-4860-a115-5cdd97891b6c.png)

Container policy - REP 2 CBF 2 SELECT 2 FROM *
- [Link to log.tar](https://drive.google.com/file/d/1Lq8SP1TzJ7t0t1af8p6UtPHJ2fpewACI/view?usp=sharing)

Can be related to https://github.com/nspcc-dev/neofs-node/issues/1983

**Comment by fyrchik** [comment]
Do you have `put_duration` metric saved for the same period?

**Comment by anatoly-bogatyrev** [comment]
![image](https://user-images.githubusercontent.com/45566606/198280135-65cab973-e934-4b7c-863c-fb94527ed26f.png)

**Comment by anatoly-bogatyrev** [comment]
![image](https://user-images.githubusercontent.com/45566606/198281011-47fd0e5c-c828-4009-ba83-ecd9987777df.png)

**Comment by fyrchik** [comment]
Closed via #2032
