### ISSUE TITLE
evacuate command move objects within the same node while node is under maintenance

### ISSUE THREAD

**Issue by vkarak1** [nspcc-dev/neofs-node#1995]
When you run `evacuate` command and specify the shard that is in RO state while node is under maintenance in a result objects move from one shard to another within the same node. 

## Expected Behavior
From my point of view it would be better at least to try to move objects to a different node (if it's possible). As far as I know maintenance mode assumes shard replacements or at least any operations with shards, and it would be safer to evacuate objects to a different node.

## Current Behavior
Objects are moved to different shard within the same node.

## Your Environment
NeoFS Storage node
Version: v0.33.0-78-g846ff515
GoVersion: go1.18.4

**Comment by cthulhu-rider** [comment]
Currently this fits the declared behavior. @fyrchik correct me if I'm wrong. Switch all shards to the read-only mode to move shard data to the remote node.

**Comment by fyrchik** [comment]
Yes, this is expected for us, but can be not the thing user wants. This issue is for discussion.

**Comment by roman-khimov** [comment]
Works as intended and easy to override already.
