### ISSUE TITLE
`ExternalAddr` and main netmap addresses mutual exclusion

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#2017]
On the one hand, mentioning the same endpoints in the attribute and in the main netmap addresses is useless: a client just could take the main ones if a node's admin does not mind using the same interfaces for all kinds of communications. But on the other hand, after the #1817 node's client also tries to connect to "external" addresses as the best effort, so the same addresses == double dial attempts to unreachable endpoints.

If the discussion leads to accepting the mutual exclusion, I would expect validation not only on the SN's side but on the IR's side too.

**Comment by realloc** [comment]
Maybe, it could be better to cache a list of recently failed endpoints on client side?

**Comment by carpawell** [comment]
@realloc, duplication is not a problem at all, but the reason that leads to it is. Just could not understand if there is any use case for having an address both in external and internal sets.

**Comment by realloc** [comment]
Technically it is ok to have same address in both netmap addresses and external addresses attribute. The issue you mention with wasting time on dialing dead endpoints, as I suppose should be covered in client code.

Possible use-cases:
- Office 1 and Office 2 nodes use internal LAN addresses in network map and declare in attributes both external and internal addresses. This leads to  duplication, but allows clients to choose the "closest" address from LAN.

**Comment by carpawell** [comment]
> Maybe, it could be better to cache a list of recently failed endpoints on client side?

Now it works that way.

**Comment by roman-khimov** [comment]
Seems like existing behavior is OK already.
