### ISSUE TITLE
Object service does not verify eACL signature

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#202]
`acl` sub-service of `object` service receives eACL table directly from morph storage:

`table, _, err := s.w.GetEACL(cid)`

Is it correct to ignore the table signature or service must verify it?

**Comment by alexvanin** [comment]
As for me, I don't think node should check signatures when getting eACL directly from NEO RPC node for internal purposes (like checking eACL rules).

I think node _can_ do that if smart contract returns both signature and public key, but in general it looks like overhead for me. NeoFS node relies on its NEO RPC node as it is source of truth.

/cc @realloc

**Comment by alexvanin** [comment]
We've decided to check signatures if they are available. For object service it is possible to do after https://github.com/nspcc-dev/neofs-node/pull/317 

However `GetEACL` may return signature without public key if this public key was revoked by container owner.
