### ISSUE TITLE
When a container is created, it appears in the listing before it is available

### ISSUE THREAD

**Issue by mike-petrov** [nspcc-dev/neofs-node#2052]
The creation of the container takes time. At the moment of creation we already get the id of the container in the listing, but command `get --cid` is not available since the container has not been created yet.

Is it ok that we already see the container in the listing, but cannot get it?

In my case, it happens in [panel-fs-neo-org](https://github.com/nspcc-dev/panel-fs-neo-org): the user creates a container, reloads the page and sees an error. It repeats every time, because creation container takes approximately 20 sec to create a container.

**Comment by fyrchik** [comment]
It can be related to caching. Do you perform `get --cid` before container listing? We may cache error response for some time.
I think this is a reasonable thing to expect, so we may try to invalidate `get` cache on each `list` command.
