### ISSUE TITLE
Rertact v1.22.0

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#2060]
## Issue

One day we accidentally pushed v1.22.0 tag. It is removed from GitHub Repository but still available in goproxy

```
$ curl -s https://proxy.golang.org/github.com/nspcc-dev/neofs-node/@v/list | grep v1
v1.22.0
```

As the result, when developer imports packages from latest neofs-node, it gets outdated code from v1.22.0.

```
$ go get -u github.com/nspcc-dev/neofs-node@latest
go: downloading github.com/nspcc-dev/neofs-node v1.22.0
go: added github.com/nspcc-dev/neofs-node v1.22.0
```

## How to solve

We can [retract](https://go.dev/ref/mod#go-mod-file-retract) this version. We did this with neofs-api-go in the past: https://github.com/nspcc-dev/neofs-api-go/commit/18a31bc68e57d44e29a25dc3b1fb90eb048f61f8

There is a difference, though. To retract v1.22.0 tag we need to push new tag with bigger value.

> The new version must be higher than other release or pre-release versions; that is, the @latest [version query](https://go.dev/ref/mod#version-queries) should resolve to the new version before retractions are considered.

However we can retract new tag in the same commit, so **both new tag** and **v1.22.0** tag will not be used in the versioning scheme. 

> As an example, consider a case where the author of module example.com/m publishes version v1.0.0 accidentally. To prevent users from upgrading to v1.0.0, the author can add two retract directives to go.mod, then tag v1.0.1 with the retractions.

I suggest to update `go.mod` and push v1.22.1 tag.

```
retract (
	v1.22.0
	v1.22.1
)
```

I did some tests in https://github.com/alexvanin/go-redacted-lib. Go modules use `v0.4.0` as latest version, even though `v1.22.*` tags are present.

**Comment by fyrchik** [comment]
@alexvanin have you checked whether everything works properly if we also delete `v1.22.1` tags after they are fetched by goproxy?

**Comment by alexvanin** [comment]
@fyrchik I did some checks in my sandbox repo. I deleted all `v1` tags: https://github.com/alexvanin/go-redacted-lib/tags
They are still available in proxy:
```
$ curl -s https://proxy.golang.org/github.com/alexvanin/go-redacted-lib/@v/list
v0.3.0
v1.22.2
v0.4.0
v1.22.0
v1.22.1
v0.1.0
v0.2.0
```

Latest tag works as expected:
```
go get -u github.com/alexvanin/go-redacted-lib@latest
go: downloading github.com/alexvanin/go-redacted-lib v0.4.0
``` 

 Don't think it is recommended to delete retracted tags. But as long as it is cached in public go proxy we are fine, I suppose.

> Retracted versions should remain available in version control repositories and on [module proxies](https://go.dev/ref/mod#glos-module-proxy) to ensure that builds that depend on them are not broken.

**Comment by fyrchik** [comment]
Should work now:
```
> go get github.com/nspcc-dev/neofs-node@latest
go: added github.com/nspcc-dev/neofs-node v0.34.0
```
