### ISSUE TITLE
It's possible to delete complementary objects of locked complex object

### ISSUE THREAD

**Issue by abereziny** [nspcc-dev/neofs-node#2093]
Let say we have complex object `123`, it will produce children objects `123-1`, `123-2` and link object `123-link`

1. Lock main object `123`
```
neofs-cli --config wallet_config.yml object lock --rpc-endpoint '<endpoint>' --wallet '81c420b9-500f-4ee3-8fce-267b8629f0c2.json' --cid '<container_id>' --oid '123' --lifetime 5
Lock object ID: 3x3Fq6JYX4UL8jbf8AqxWczASEKNrdcwLV2svncBuUjH
Objects successfully locked.
```
3. Try to delete link object
4. Try to delete children object

## Expected Behavior
Complemetary objects should be protected from deletion by lock on main object

## Current Behavior
It is possible to delete link and children objects while main object have lock

## Tests
test_link_object_of_complex_object_should_also_be_protected_from_deletion
https://github.com/nspcc-dev/neofs-testcases/blob/master/pytest_tests/testsuites/object/test_object_lock.py#L654
test_complex_object_chunks_should_also_be_protected_from_deletion
https://github.com/nspcc-dev/neofs-testcases/blob/master/pytest_tests/testsuites/object/test_object_lock.py#L608

**Comment by carpawell** [comment]
Currently, we put only a root object's ID in a LOCK's payload so nothing can stop SE from removing any child/link object. It could be solved:

#### Client side

Attaching the full child object list to the LOCK object on the client side (`neofs-cli`) as we do for [SG](https://github.com/nspcc-dev/neofs-node/blob/42554a9298a32cff2669039e21c44293587200ce/cmd/neofs-cli/modules/storagegroup/put.go#L91). It requires making additional RPC requests and should be validated by a node (#1659 for SGs) but is definitely a client's desire and requires only session on `PUT` with a node (finish object creation).

#### Server side
Allow a node to change LOCK's object payload (add child objects). It requires attaching unexpected session tokens like we already [do](https://github.com/nspcc-dev/neofs-node/blob/42554a9298a32cff2669039e21c44293587200ce/cmd/neofs-cli/modules/object/util.go#L261-L264) for TSs. And, well, it requires _changing the payload by a node_ on a protocol level. (object removal does not work like that, you say what object to delete, and a node collects TS for you; the locking mechanism does not have a separate verb and RPC for that, only create+put object actions by the client side).

#### Alternative
Expand our verbs with `LOCK` operation and do locking the same way we delete objects. Then any problems with locks are solved as we solve them for TS objects (we already have them) just cause it will works similarly.

**Comment by roman-khimov** [comment]
Relates to nspcc-dev/neofs-testcases#535.

**Comment by cthulhu-rider** [comment]
@roman-khimov should we w8 4 #2729 to be merged/released? Or postpone to the later release?

**Comment by roman-khimov** [comment]
I'd wait for it, but pushing to 0.42.0 is a bit too much (at least if we're expecting #2729 to land soon).
