### ISSUE TITLE
Locked complex object with expiration epoch was removed despite of lock

### ISSUE THREAD

**Issue by abereziny** [nspcc-dev/neofs-node#2096]
Let say we have
1. Current epoch is `100`
2. Complex object with `__NEOFS__EXPIRATION_EPOCH=101`
3. Complex object locked by lock with expiration at epoch `103`

Tick epochs couple times and check object availability each epoch

## Expected Behavior
Complex object should be removed at epoch 103

## Current Behavior
Complex object was removed at epoch 102 (ignoring locks)

## Tests
in branch [feature-abereziny-add-lock-tests-2](https://github.com/abereziny/neofs-testcases/tree/feature-abereziny-add-lock-tests-2)

- pytest_tests/testsuites/object/test_object_lock.py#test_expired_object_should_be_deleted_after_locks_are_expired

**Comment by fyrchik** [comment]
Current lock implementation always contains a single object ID. When we split object in parts, `ExpirationEpoch` is inherited. Because of #2093 object parts are not locked and thus can easily be removed.

**Comment by roman-khimov** [comment]
Do we have an appropriate test?

**Comment by roman-khimov** [comment]
Looks like https://github.com/nspcc-dev/neofs-testcases/issues/535.

**Comment by carpawell** [comment]
@roman-khimov, I think it was planned in some private branch that has been deleted. I think [this part](https://github.com/nspcc-dev/neofs-testcases/blob/ab7048ee6879b9614af8cc234d708c31ea56b34f/pytest_tests/tests/object/test_object_lock.py#L307) for complex object can be considered as an expiration save check and [this (skipped) part](https://github.com/nspcc-dev/neofs-testcases/blob/ab7048ee6879b9614af8cc234d708c31ea56b34f/pytest_tests/tests/object/test_object_lock.py#L525) can be considered as a user deletion save check.
