### ISSUE TITLE
Locked object can be deleted on one extra epoch away from lock expiration

### ISSUE THREAD

**Issue by abereziny** [nspcc-dev/neofs-node#2097]
Let say we have:
1. Current epoch is `100`
2. Object is put to the container
3. Object is locked with lock with expiration at epoch `101`

Steps:
1. Tick epoch, current epoch becomes `101`
2. Try to delete object

## Expected Behavior
Object should be removed since lock expired at current epoch

## Current Behavior
Object cannot be removed and treated as locked object until next extra epoch is ticked

## Tests
- [pytest_tests/testsuites/object/test_object_lock.py#test_after_lock_expiration_with_expire_at_user_should_be_able_to_delete_object](https://github.com/nspcc-dev/neofs-testcases/blob/master/pytest_tests/testsuites/object/test_object_lock.py#L506)
- [pytest_tests/testsuites/object/test_object_lock.py#test_after_lock_expiration_with_lifetime_user_should_be_able_to_delete_object](https://github.com/nspcc-dev/neofs-testcases/blob/master/pytest_tests/testsuites/object/test_object_lock.py#L464)

**Comment by acid-ant** [comment]
Blocked by:
- https://github.com/nspcc-dev/neofs-api/issues/253
- https://github.com/nspcc-dev/neofs-sdk-go/issues/370

**Comment by acid-ant** [comment]
@abereziny it works as expected. Fixed help message for parameter here #2169. I've added one extra epoch tick and test passed.
