### ISSUE TITLE
Simple object with lock and expiration time not removed after locks are expired

### ISSUE THREAD

**Issue by abereziny** [nspcc-dev/neofs-node#2099]
Let say we have:
1. Current epoch is `100`
2. Simple object with `__NEOFS__EXPIRATION_EPOCH=101`
3. Simple object is locked with lock until epoch `103`

Steps:
Tick epochs until current epoch = 103
Check object availability

## Expected Behavior
Simple object should be removed since locks are gone and object expired

## Current Behavior
Simple object continues to present in storage even if we wait additional extra epochs

## Tests
in branch [feature-abereziny-add-lock-tests-2](https://github.com/abereziny/neofs-testcases/tree/feature-abereziny-add-lock-tests-2)

- pytest_tests/testsuites/object/test_object_lock.py#test_expired_object_should_be_deleted_after_locks_are_expired

**Comment by acid-ant** [comment]
Blocked by:
- https://github.com/nspcc-dev/neofs-api/issues/253
- https://github.com/nspcc-dev/neofs-sdk-go/issues/370

**Comment by acid-ant** [comment]
it works as expected. Fixed help message for parameter here #2169. I've added one extra epoch tick and test passed.

**Comment by abereziny** [comment]
Currently it's not working as expected because objects got removed despite of locks
![image](https://user-images.githubusercontent.com/116558828/209701901-8001d472-ffe7-43fe-bfe8-b6b1d8bc0438.png)

**Comment by acid-ant** [comment]
@abereziny it works as expected. It is ok to get `not found` error in your case, because expiration epoch in lock blocks any action with data, but do not affect presence of the object on file system. Now it is impossible to test.
In other words, it is possible create object with expiration epoch N and lock with M where M > N.

**Comment by abereziny** [comment]
@acid-ant I do not agree with that because current behavior have no real practical use case.
Why do we need to lock object which will be unavailable? What's the point?

for example: we have document with expiration, court need this document in the process so it must not be deleted and must be available until process is complete, so lock is assigned. If the document is not available - it practically means that lock doesn't work from user point of view.

**Comment by abereziny** [comment]
Logged and issue for API to further elaboration

**Comment by roman-khimov** [comment]
@evgeniiz321, do we have any test scenario like this?

**Comment by evgeniiz321** [comment]
@roman-khimov yes, we do - https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1784-1722447068/index.html#suites/295ed2e000f8fa6f3ade59cc13b98615/9a75854013e7509b/
