### ISSUE TITLE
Metrics: container space usage

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#2116]
Need a new metric from storage nodes to collect container space usage.
If it is possible to indicate the owner of the container with a label in this metric, then this will simplify further use.

**Comment by fyrchik** [comment]
1. Use full object size for calculation, not only payload.
2. Track physically stored objects (if it is inhumed but not deleted, the metric doesn't decrease)
3. Tombstone and locks should also be tracked.

**Comment by fyrchik** [comment]
The least invasive way is to track regular objects and their payload size now.

**Comment by fyrchik** [comment]
Container size example:
```
# HELP neofs_node_engine_container_size Accumulated size of all objects in a container
# TYPE neofs_node_engine_container_size gauge
neofs_node_engine_container_size{cid="7hsjMpkHJWqJUZ6AWzHXfDCrBpywvLSv2tx9x16Mc8R5"} 1024
```
