### ISSUE TITLE
Tree-service sync after splitbrain failover

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#2127]
Incorrect tree-service sync after splitbrain failover.

Synchronization occurs only from one node. 
In this case, the node could synchronize data with a node from the same part of the cluster. 
The order for the container is fixed.

Need to fix this:
- get not fixed node to sync (can be selected sequentially or in random)
- sync not only after new epoch event

**Comment by fyrchik** [comment]
Let's add randomization for now and discuss other ways to improve the syncronization.

**Comment by alexchetaev** [comment]
Need to create issue for discussion
