### ISSUE TITLE
RANGEHASH with static session sometimes can't find object

### ISSUE THREAD

**Issue by abereziny** [nspcc-dev/neofs-node#2144]
Steps:
1. Have 2 wallets: owner and user
2. Create container using owner wallet
```
neofs-cli --config owner_wallet_config.yml container create --rpc-endpoint '<endpoint>' --wallet owner_wallet.json --await --policy 'REP 2 IN X CBF 1 SELECT 4 FROM * AS X'

STDOUT:
container ID: 4jxFyPEzcEAz2wNcMSz3SUDdQvcaDy7z2UeooR2Asu8M
```

4. Put object to a node to a container using owner wallet 
```
neofs-cli  --config owner_wallet_config.yml object put --rpc-endpoint '<endpoint>' --wallet owner_wallet.json --cid '4jxFyPEzcEAz2wNcMSz3SUDdQvcaDy7z2UeooR2Asu8M' --file '1000.txt' --no-progress

STDOUT:
Object successfully stored
  OID: APQPiqPdtKPZWhfs8D5W5uYkFrRcfkYZMc3nQenXCD4V
  CID: 4jxFyPEzcEAz2wNcMSz3SUDdQvcaDy7z2UeooR2Asu8M
```
5. Create and sign static session for user wallet with RANGEHASH verb for this container and this object (note base58 -> base64 conversions)
6. Do rangehash request
```
neofs-cli --config user_wallet_config.yml object hash --rpc-endpoint '<endpoint>' --wallet 'user_wallet.json' --cid '4jxFyPEzcEAz2wNcMSz3SUDdQvcaDy7z2UeooR2Asu8M' --oid 'APQPiqPdtKPZWhfs8D5W5uYkFrRcfkYZMc3nQenXCD4V' --range '0:10' --session 'signed_session_token.json'

```

## Expected Behavior
Rangehash returns hash of the object

## Current Behavior
Sometimes object is not found
```
Error:
return code: 1
output: rpc error: read payload hashes via client: status: code = 2049 message = object not found
```

## Tests
https://github.com/nspcc-dev/neofs-testcases/blob/master/pytest_tests/testsuites/session_token/test_static_object_session_token.py#L192

**Comment by fyrchik** [comment]
For `GET_RANGE` we have forwarding and thus can redirect request.
For `RANGE_HASH` we create requests to different nodes, thus no forwarding can be done. Because session is static, token is not stored on the node side and thus `session token not found` can be seen in logs.

I propose to check whether we have a session token locally and forget about it if not in `GetRangeHash`.

**Comment by abereziny** [comment]
Passed via automation on build v1.0.1-nb-20221227.1
![image](https://user-images.githubusercontent.com/116558828/209701036-564d3e7f-9228-4ef2-81e7-a8af333145b5.png)
