### ISSUE TITLE
Some operations with container static session token failed with timeout

### ISSUE THREAD

**Issue by yadro-vavdeev** [nspcc-dev/neofs-node#2153]
Failed with timed out after 30 seconds:

1. neofs-cli container set-eacl with correct rules: `{'container': {'verb': 'SETEACL', 'wildcard': False}}`
```
neofs-cli --config wallet_config.yml container set-eacl --rpc-endpoint 'node:8081' --wallet 'wallet.json' --cid 'FSprnHNXFX8bhyy6MuaATuP2LBySMVNV48PYubANis6T' --await --table '/eacl_table.json' --session 'a7b17c1a-f43b-4482-a6ed-f2cb092c1ebf'
```
2. neofs-cli container create with correct rules, but other wallet
3. neofs-cli container create with other verb rules

## Expected Behavior
1. Container set eacl operation completed successfully
2. Failed with error
3. Failed with error

## Current Behavior
1. Failed with timeout (30s)
2. Failed with timeout (30s)
3. Failed with timeout (30s)

## Steps to Reproduce (for bugs)
1. Wallet1 generate Session Tokens For Container for wallet2
2. Wallet1 sign Session Token
3. Wallet1 create container 
4. Wallet2 try set eacl for container with static session token

## Your Environment
neo-go 1.0.0
neofs-authmate 0.25.0-18-g92a5e092-dirty
neofs-cli 0.34.0-103-gcb43a6ae-dirty
neofs-adm 0.34.0-103-gcb43a6ae-dirty

**Comment by fyrchik** [comment]
@yadro-vavdeev Could you attach session token file?

**Comment by fyrchik** [comment]
Probably related to https://github.com/nspcc-dev/neofs-testcases/pull/475

**Comment by yadro-vavdeev** [comment]
```
{"body":{"id":"qASilkQ8QdOyWyD/qERjVg==", "ownerID":{"value":"NfD3l3xLJnEm1sZAT/eB7pQzAd+nH2Wjsw=="}, "lifetime":{"exp":"100000000", "nbf":"0", "iat":"0"}, "sessionKey":"AscSVYNkQmA51bO5zA33FVV6BMwpVJMxTw3pfEpkGKoD", "container":{"verb":"SETEACL", "wildcard":false, "containerID":{"value":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="}}}, "signature":{"key":"AqsgWJHAkHnf6UKgchvLvAzXw0gqwxjF2qz2MzZZ0mjE", "signature":"BAAgrvPXVMgxV9q2Azo3AOkc2X2BiD3JMTVJ/H3R7pFbOpORQnOHTauylJcVbtHUZebuaex+ypyESjiGJRfFWu4=", "scheme":"ECDSA_SHA512"}}
```

**Comment by fyrchik** [comment]
About the first case: looks like a linked test problem -- `wildcard` should be true if container is not set.
(2) and (3) are different -- storage node creates a transaction, but validation is done in the IR.

**Comment by yadro-vavdeev** [comment]
Thanks!
set eacl work fine with wildcard: true:
```
{
   "body":{
      "id":"PMCj24YiQ++Gy4GKcMwQYQ==",
      "ownerID":{
         "value":"NQd/L38gnTfZImp+nZGTn0TaBx+ffZ74LA=="
      },
      "lifetime":{
         "exp":"100000000",
         "nbf":"0",
         "iat":"0"
      },
      "sessionKey":"AgfcbXkSSYtK840hq++ZJP9KDo88HH8MjhLxkKPW8cPV",
      "container":{
         "verb":"SETEACL",
         "wildcard":true,
         "containerID":null
      }
   },
   "signature":{
      "key":"AruuUedG6BN7ZuSrgNGWD30PIApJ81Hwuq4u2+hMghDh",
      "signature":"BHhV8nHV8Df3pABgj7rQsmNar72DFviPP/2g1d9+udffPuqUl2eCyDmrfAv3gqgZIaOlNElhHt2xuKOU7lbB0QY=",
      "scheme":"ECDSA_SHA512"
   }
}
```

**Comment by fyrchik** [comment]
For 2,3 I have created a https://github.com/nspcc-dev/neofs-node/issues/2168
