### ISSUE TITLE
Remove redundant object copies from container 

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#217]
version: 0.12.1 release

No deletion of redundant copies after replication and node returning with copy unavailable previously.
1. Create a container with the policy "REP 2 IN X CBF 1 SELECT 4 FROM * AS X"
2. Put an object
3. Check that we have 2 copies - on node1 and node4
4. Stop node4
5. Object has been replicated to node2
6. Return node4 
7. After that we have 3 copies of the object in the container permanently (node1, node2, node4)

**Comment by cthulhu-rider** [comment]
Replication mechanism is not specified yet. It's not critical to have redundant copies in container for now.

**Comment by alexvanin** [comment]
It would be nice to check if `policer` detects redundant copies to notificate garbage collector when it will be implemented.
