### ISSUE TITLE
Optimize blobovnicza caching

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#2180]
There are multiple problems with the current scheme:
1. We have separate opened/active cache which leads to a complex implementation (mutexes should be taken in a specific order and we MUST take both if blobovnicza has a chance of being evicted).
2. Because of this separation `opened_cache_size` can actually be violated: actual amount of opened files is `len(active) + opened_cache_size`.
3. We can remove items from blobovnicza thus the property `opened cache contains filled blobovniczas` is no longer true.

I propose to refactor it like this:
1. Have only 1 cache with all blobovniczas.
2. Active map should only contain an index: when we need to put an item we just open blobovnicza if it is not already opened.
3. If `width` and `depth` parameters are very big compared to `opened_cache_size`, print a warning in logs.
4. *After `active` index exceeds width we should start again from 0 and, possibly, perform VACUUM.

**Comment by roman-khimov** [comment]
Obsoleted by #2453.
