### ISSUE TITLE
Deleting object children at once from metabase

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#219]
Related to #199 

If we delete all object's children in one `metabase.Delete` call, then `parentLength` check will be invalid in a single transaction (it will be >1 for both children). Therefore object will stay in secondary indexes after Delete. Possible solutions:
- remove one object at a time (maybe merge it with cleanup then),
- check if `metabase.Delete` arguments contain all addresses from parent index manually,
- remove virtual objects separately (it would be kinda slow to go through all indexes for that).

**Comment by realloc** [comment]
Required GC and internal storage changes, postponed to later releases.
