### ISSUE TITLE
Support for notary-less environments in neofs-adm

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2192]
## Is your feature request related to a problem? Please describe.
Neo mainnet sidechain still has no notary subsystem. neofs-adm is useful to manage contract upgrades (especially wrt alphabet and groups management).

## Describe the solution you'd like
It should be possible to use it. In fact it's very easy to modify it to add support for it.

## Describe alternatives you've considered
But eventually notary-less sidechain will be upgraded and there won't be this problem at all.

## Additional context
This issue is mostly a notepad for a list of changes that can be done to enable neofs-adm for non-notary environments:
 * read all wallets in a `loop` of `openAlphabetWallets`
 * suppress `checkNotaryEnabled`
 * drop `proxyContract` from `contractList`
 * set `notaryDisabled` parameter to `true` in `getContractDeployData` and `getAlphabetDeployItems` (`items[0]`)
 * don't set `items[2]` in getAlphabetDeployItems

But I probably won't create a PR for it because see above, every sidechain will have notary subsystem eventually, so adding some code that will be used once is probably not the way to go.

**Comment by fyrchik** [comment]
We have https://github.com/nspcc-dev/neofs-node/tree/neofs-adm-notary-disabled which is rebased when we need it.

**Comment by roman-khimov** [comment]
Mainnet is notary-enabled now. Obsolete.
