### ISSUE TITLE
Bundle neofs-contracts into IR nodes

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2195]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I have to update NeoFS because we have neofs-contracts that are completely separate thing that no Ansible can help with. neofs-adm can help somewhat, but it still is an additional entity to think about (especially wrt compatibilty, is neofs-contracts X.Y.Z compatible with IR A.B.C?), while it's a completely internal NeoFS thing (implementation detail). It's too easy to forget to update them, it's too easy to make some mistake, it's hard to track these versions and relations to IR/SN versions (what version of the neofs-contracts the network N uses? Ansible doesn't help with that).

## Describe the solution you'd like
IR should have a proper version of neofs-contracts stored internally. It can be used for deployment, but we need to deal with updates first, IR should check contract versions during startup and if it has something newer initialize an update procedure (send appropriate transactions, or rather notary requests). So the end-user experience would be "update IR node binaries, done" (given #2194 is to be implemented).

## Describe alternatives you've considered
Leaving things as is. Doesn't seem to be viable long-term.

**Comment by roman-khimov** [comment]
We've got neofs-contract repo now that is external wrt to neofs-node, moving contracts into the neofs-node is not a good thing to do because we'll use neofs-contract for bindings as well and that can be imported in various projects, so it's better to have them in a more light-weight repo.

We can add them as submodules, but this repo doesn't (and shouldn't) store NEFs/manifests. They can be compiled as a part of neofs-node build procedure, but this will take time and will also require building NeoGo binary (compiler) in the process.

We at the same time have neofs-contract releases that have everything needed, so what I'd do is take them (URL+checksum), unpack them into some "contracts" dir and then add "contracts" into binary internal storage. "contracts" should have some simple storage scheme like `NN-contract.nef + NN-contract.manifest.json` where NN is deployment order number. Except maybe for NNS (which is always the first one) and alphabet (which is more of a template, not a ready to deploy contract).

This scheme theoretically is updatable (you can place a new contract into the directory and rebuild the node) and extendable (additional contracts can be placed there easily as well). We need both for development and extensibility purposes, so it's more of an option 3 in the end.

**Comment by cthulhu-rider** [comment]
There is more data - deployment parameters. I collected all kinds. :writing_hand: :writing_hand: :writing_hand: 

## Contract addresses
Some contracts currently depend on other ones. This will be absorbed by https://github.com/nspcc-dev/neofs-contract/issues/325.

## Unique
* `notaryDisabled bool` - sunk into oblivion, always set to `false` until removed

### Alphabet
* `total int` - Alphabet cardinality, resolved dynamically = commitee size
* `name string` - can be dynamically set depending on `total`: `az`, `buky`, etc.
* `index int` - index of `name` letter

**Comment by cthulhu-rider** [comment]
Talking about

> storage scheme like `NN-contract.nef + NN-contract.manifest.json` where NN is deployment order number

how we gonna deal with https://github.com/nspcc-dev/neofs-contract/issues/325#issuecomment-1486682545?

**Comment by roman-khimov** [comment]
Right now we can precalculate hashes and use them. Then contract names are managed separately from `_deploy` in the current container and netmap contracts and precalculation can be used. Long-term we'll fix nspcc-dev/neofs-contract#327 (and any other similar things, I'd like to clean up `_deploy` methods as much as I can).

**Comment by roman-khimov** [comment]
Seems to be done to me.
