### ISSUE TITLE
"database not open" error after node restarted

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-node#2198]
## Steps to Reproduce (for bugs)
1.Restart neofs-storage service
2.Logs filled a lot of errors:
```
Jan 11 15:08:08 vedi neofs-node[1368627]: 2023-01-11T15:08:08.588Z        info        neofs-node/main.go:76        initializing gRPC service...
Jan 11 15:08:08 vedi neofs-node[1368627]: 2023-01-11T15:08:08.589Z        warn        engine/engine.go:160        could not put object to active blobovnicza        {"shard_id": "FRNsLKdPMxv3yaRtFVyXtJ", "error count": 2, "error": "database not open"}
```
3.Then shard mode changed to ```degraded-read-only```.

**Note:** It was happened after some failover tests (load on AZ and restart BUKI) have run.

## Logs
[journal_az.tar.xz.zip](https://github.com/nspcc-dev/neofs-node/files/10399396/journal_az.tar.xz.zip)
[journal_buki.tar.xz.zip](https://github.com/nspcc-dev/neofs-node/files/10399397/journal_buki.tar.xz.zip)
[journal_glagoli.tar.xz.zip](https://github.com/nspcc-dev/neofs-node/files/10399398/journal_glagoli.tar.xz.zip)
[journal_vedi.tar.xz.zip](https://github.com/nspcc-dev/neofs-node/files/10399399/journal_vedi.tar.xz.zip)

## Versions
```
NeoFS Storage node
Version: v0.34.0-144-g7c3ab4d1-dirty
GoVersion: go1.18.4
```
## Your Environment
Server setup and configuration:
HW, 4 servers, 4 SN, 4 http qw, 4 s3 gw

Operating System and version (uname -a):
linux vedi 5.10.0-16-amd64 https://github.com/nspcc-dev/neofs-node/issues/1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux

**Comment by fyrchik** [comment]
Closed via #2198
