### ISSUE TITLE
storage engine initialization takes too long

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#2215]
```
8:16:39  neofs-node/main.go:76  initializing storage engine service...
8:23:01  writecache/init.go:14  filling flush marks for objects in FSTree        {"shard_id": "YWVQLsdMz451ShJzUUKqD2"}
8:23:01  writecache/init.go:25  filling flush marks for objects in database        {"shard_id": "YWVQLsdMz451ShJzUUKqD2"}
8:23:01  writecache/init.go:60  finished updating flush marks        {"shard_id": "YWVQLsdMz451ShJzUUKqD2"}
8:23:55  writecache/init.go:14  filling flush marks for objects in FSTree        {"shard_id": "XidSLGUWrwRTFALB3tpD6p"}
8:23:55  writecache/init.go:25  filling flush marks for objects in database        {"shard_id": "XidSLGUWrwRTFALB3tpD6p"}
8:23:55  writecache/init.go:60  finished updating flush marks        {"shard_id": "XidSLGUWrwRTFALB3tpD6p"}
8:23:55  neofs-node/main.go:78  storage engine service has been successfully initialized
8:23:55  neofs-node/main.go:76  initializing gRPC service...
```

**Comment by roman-khimov** [comment]
How much data does this node have? Number of shards, sizes, number of files in them?

**Comment by fyrchik** [comment]
It is a known problem with writecache:
1. After hard-reset some objects may be present in cache but not in the main storage.
2. To know which of them can be removed, we must check each of them individually.
3. This check takes time proportional to the amount of objects in a write-cache.

I thought there was an issue, but I cannot find it now. One of the approaches to fix this is to initialize cache asynchronously (start check in a background ->  return `ErrInitializing` for modifying operations during it -> finish check).

**Comment by fyrchik** [comment]
To give you some numbers, it can take ~40 minutes on a dedicated server with ~10 shards and ~100GB cache, so it is worth fixing IMO.

**Comment by 532910** [comment]
this issue is about the first start, when no write-cache exist at all

> How much data does this node have? Number of shards, sizes, number of files in them?

it has no data, 2 shards

**Comment by roman-khimov** [comment]
@fyrchik, I don't see any issue tracking this, do we have it? Because @532910 problem is a different one.

**Comment by fyrchik** [comment]
@532910 has the initialization finished at some point? If not, this can be related to a recent deadlock in the morph client (aka subscribe without channel readers).

**Comment by roman-khimov** [comment]
Is it still an issue? Shouldn't be.

**Comment by vvarg229** [comment]
> Is it still an issue? Shouldn't be.

Looks like fixed at https://github.com/nspcc-dev/neofs-dev-env/pull/251

**Comment by roman-khimov** [comment]
Seems to be obsolete in init part. Write cache is #2337.
