### ISSUE TITLE
NeoGo 0.102.0 update

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2221]
When it's to be released it'll have nspcc-dev/neo-go#2890 fixed and therefore we could remove #2220 kludge. Any other 0.101.1 changes should be tracked here as well.

**Comment by roman-khimov** [comment]
It affects compatibility, so better be done a bit later.

**Comment by cthulhu-rider** [comment]
https://github.com/nspcc-dev/neo-go/releases/tag/v0.102.0 has come, lets grade to it? RPC errors look tasty
