### ISSUE TITLE
Spelling "an operation" should be "the operation"

### ISSUE THREAD

**Issue by abereziny** [nspcc-dev/neofs-node#2240]
[https://github.com/nspcc-dev/neofs-testlib/pull/57#discussion_r1098299081](https://github.com/nspcc-dev/neofs-testlib/pull/57#discussion_r1098299081)

neofs-cli container and object commands have `--timeout` parameter. The spelling of help is incorrect. "an" article should be changed to "the" article

**Comment by carpawell** [comment]
@EliChin, could you probe that, please?

**Comment by EliChin** [comment]
I would stand for "the"
