### ISSUE TITLE
"Could not find right child: (*searchsvc.RelationSearcher) unexpected amount of found objects 2" for complex object (size 20mb)

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#226]
version: 0.12.1-7-g5470d94

command 'neofs-cli --rpc-endpoint s01.neofs.devenv:8080 --key L1TR2KStDi3TfdfWBUNWB3cQR1ZZZd82eZBC9BvPoRpGK7oZgrz3 object get --cid 2e15R6mEWLo575As7qPrL5FhcBrQ12ZqJ7DhRrLGRq5N --oid 8UT3oqkQQ3nXVvMD63DM54ugcmz7f9MPJcAi6dyq1oAB --file s_file_read ' return with error (code 1): Error: can't put object: could not receive Get response: rpc error: code = Unknown desc = could not create message reader: could not create message reader: (*getsvc.Service) could not get object payload range data: (*getsvc.Service) could not get range: (*rangesvc.Service) could not receive Head result: (*headsvc.Service) could not find right child: (*searchsvc.RelationSearcher) unexpected amount of found objects 2

**Comment by alexvanin** [comment]
Master branch is broken for big objects (>1mb in neofs-dev-env right now), so it is expected.

**Comment by cthulhu-rider** [comment]
The bug is expected in 0.12.x. We won't fix until 0.13.0 where GET scheme will be re-implemented.

**Comment by realloc** [comment]
Updated GET scheme is ready, please check if the issue persists.

**Comment by anatoly-bogatyrev** [comment]
The issue has been fixed in the new RC with blob storage.
