### ISSUE TITLE
Perceive `PUT` of `TOMBSTONE` as `DELETE` 

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#2261]
Nothing seems to prevent the system from interpreting saving tombstones as a deletion operation (*). This approach will greatly facilitate the control over operations (sessions, ACL), and it's completely backward compatible.

(*) the only case is a tombstone replication by container nodes which can be treated especially.

Are there any potential problems with that?

**Comment by roman-khimov** [comment]
The "DELETE" we have now is somewhat of a fake, there is no ~~spoon~~ "delete" in our system (at least as it is now). Yet at the same time tombstones are special, so treating "DELETE" as a permission to "PUT" tombstones (and only them) seems to be OK. But maybe it only seems to...

**Comment by cthulhu-rider** [comment]
similar problem is collapse of different PUT and CREATE operations into single PUT. As user, i'd like to grant rights to PUT my objects (e.g. to gateway), but not CREATE them

P.S. maybe we already have related issue, but i didn't find it fast
