### ISSUE TITLE
neofs-cli: object `delete` command should have an option to `delete by attribute`

### ISSUE THREAD

**Issue by rkonfj** [nspcc-dev/neofs-node#2268]
I am using `neofs` to serving my static web pages, and I will update the web page version frequently. Over time, there will be more and more historical versions objects of the same `FileName` attribute.

Currently, I have to compare the `Timestamp` property of the object to delete the old versions.

I hope there is a way to delete objects according to their properties, such as `FileName` (preferably there is an option to keep the last version)

**Comment by roman-khimov** [comment]
You mean like implicitly deleting old objects when a new one is PUT with the same `FileName`? It's not really possible now, what is "the last version" and what is "the old version" is not an easy question.

**Comment by rkonfj** [comment]
Thanks. @roman-khimov 
> You mean like implicitly deleting old objects when a new one is PUT with the same FileName? It's not really possible now,

Oh, that seems a pity. But is it possible to support deleting objects by attribute?  like:
```
neofs-cli object delete --cid AQS1JYt5Zeop3Fbx2v4pfqY1zxVVjUjyagyyMcukWuiy --name rkonfj/about.html
```

> what is "the last version" and what is "the old version" is not an easy question.

Since every object has a `Timestamp` attribute by default, we may be able to judge whether it is an `old version` based on it.

Based on the `Timestamp`, it may be possible to achieve "keep the object with the latest timestamp"
```
neofs-cli object delete --cid AQS1JYt5Zeop3Fbx2v4pfqY1zxVVjUjyagyyMcukWuiy --name rkonfj/about.html --keep-last
```

**Comment by roman-khimov** [comment]
> But is it possible to support deleting objects by attribute?

Not really. It can be somewhat hidden by the CLI, but it'd require a SEARCH first anyway (as just about anything attribute-based) and then DELETE of particular found objects. It can't be atomic even though it may look like that if we're to pack it into a single CLI incantation, so at least now you can see that these are two different operations and you can manage them in any way appropriate for you particular task.

BTW, we do host things from NeoFS as well and for a somewhat smaller websites in a dedicated container the easiest way to go probably is:
 * SEARCH for all objects, save the list
 * upload new ones (complete website "release")
 * drop old ones from the list saved previously

> Since every object has a Timestamp attribute by default, we may be able to judge whether it is an old version based on it.

This at least assumes that there is one client with a single clock source doing things, a valid assumption in many cases, but in general we may have multiple clients with unsynchronized clocks pushing data to various storage nodes. Tree service for S3 gateway solves it in some way, but it's experimental and likely to change.

**Comment by rkonfj** [comment]
Ok, I try to use the `shell script` to combine the `atomic functions` of neofs-cli. Thanks @roman-khimov
