### ISSUE TITLE
Try setting up GH action to run neofs-testcases for neofs-node

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2290]
Once we have a shiny new GH runner try using to run neofs-testcases for PRs/commits of neofs-node. The issue is create in a node since likely that's gonna be a workflow here.

**Comment by roman-khimov** [comment]
See also nspcc-dev/neo-go#2943.

**Comment by roman-khimov** [comment]
Anything left here?

**Comment by vvarg229** [comment]
> Anything left here?

Yes, of course
This task is already done.
