### ISSUE TITLE
v0.35.0 memory consumpion after upgrade

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#2300]
![image](https://user-images.githubusercontent.com/14617699/231097228-1f9f1139-e5fa-4131-8d06-1cc1f812e459.png)
```
(8:08:36)[sergio@titan2:~]% dmesg | grep 'Out of memory'
[Mon Apr 10 11:02:53 2023] Out of memory: Killed process 289299 (neofs-node) total-vm:4520808kB, anon-rss:3517280kB, file-rss:0kB, shmem-rss:0kB, UID:998 pgtables:7212kB oom_score_adj:0
[Mon Apr 10 12:10:53 2023] Out of memory: Killed process 289328 (neofs-node) total-vm:4460120kB, anon-rss:3567464kB, file-rss:0kB, shmem-rss:0kB, UID:998 pgtables:7464kB oom_score_adj:0
[Mon Apr 10 12:27:34 2023] Out of memory: Killed process 289538 (neofs-node) total-vm:4519224kB, anon-rss:3585728kB, file-rss:0kB, shmem-rss:0kB, UID:998 pgtables:7464kB oom_score_adj:0
[Mon Apr 10 12:33:43 2023] Out of memory: Killed process 289672 (neofs-node) total-vm:4586876kB, anon-rss:3586784kB, file-rss:0kB, shmem-rss:0kB, UID:998 pgtables:7356kB oom_score_adj:0
[Mon Apr 10 14:12:49 2023] Out of memory: Killed process 290054 (neofs-node) total-vm:4519480kB, anon-rss:3578708kB, file-rss:0kB, shmem-rss:0kB, UID:998 pgtables:7348kB oom_score_adj:0
[Mon Apr 10 15:03:47 2023] Out of memory: Killed process 290212 (neofs-node) total-vm:4654592kB, anon-rss:3576376kB, file-rss:0kB, shmem-rss:0kB, UID:998 pgtables:7492kB oom_score_adj:0
[Mon Apr 10 15:26:16 2023] Out of memory: Killed process 290398 (neofs-node) total-vm:4519288kB, anon-rss:3583848kB, file-rss:0kB, shmem-rss:0kB, UID:998 pgtables:7388kB oom_score_adj:0
[Mon Apr 10 15:59:13 2023] Out of memory: Killed process 290554 (neofs-node) total-vm:4451700kB, anon-rss:3582792kB, file-rss:0kB, shmem-rss:0kB, UID:998 pgtables:7348kB oom_score_adj:0
[Mon Apr 10 21:59:45 2023] Out of memory: Killed process 290723 (neofs-node) total-vm:4681480kB, anon-rss:3575972kB, file-rss:0kB, shmem-rss:0kB, UID:998 pgtables:7752kB oom_score_adj:0
[Mon Apr 10 22:01:27 2023] Out of memory: Killed process 292060 (neofs-node) total-vm:4471832kB, anon-rss:3594496kB, file-rss:0kB, shmem-rss:0kB, UID:998 pgtables:7372kB oom_score_adj:0
[Mon Apr 10 22:29:14 2023] Out of memory: Killed process 292085 (neofs-node) total-vm:4613792kB, anon-rss:3596172kB, file-rss:0kB, shmem-rss:0kB, UID:998 pgtables:7388kB oom_score_adj:0
```

**Comment by roman-khimov** [comment]
Unfortunately, the issue doesn't reproduce now, so it's impossible to get some meaningful pprof output.

**Comment by roman-khimov** [comment]
inuse_space:
<img width="182" alt="Screenshot_20230412_120534" src="https://user-images.githubusercontent.com/22092804/231409448-220aabae-4b87-4522-9872-f08ff91d239c.png">
<img width="650" alt="Screenshot_20230412_120611" src="https://user-images.githubusercontent.com/22092804/231409457-885a7a92-384b-44f1-846d-6243893631a9.png">
alloc_space is about the same:
<img width="657" alt="Screenshot_20230412_120802" src="https://user-images.githubusercontent.com/22092804/231409977-0b6da828-9892-4caf-a38e-ef9a9919cd4b.png">

[allocs.gz](https://github.com/nspcc-dev/neofs-node/files/11209294/allocs.gz)

**Comment by roman-khimov** [comment]
It's strange. From a quick glance `task` is short-lived and processed synchronously, there shouldn't be a pile of tasks working side-by-side. Task processing code reads objects completely, true, but they're sent elsewhere and forgotten afterwards.

**Comment by cthulhu-rider** [comment]
I'll try to investigate weak spots on this call stack

**Comment by roman-khimov** [comment]
0.36.0 (eats up to 3+ GB pretty quickly):
[allocs-36-2.gz](https://github.com/nspcc-dev/neofs-node/files/11236691/allocs-36-2.gz)
[allocs-36.gz](https://github.com/nspcc-dev/neofs-node/files/11236692/allocs-36.gz)

**Comment by roman-khimov** [comment]
Duplicates #2178.

**Comment by roman-khimov** [comment]
Actually, it may not be a duplicate, but just a misconfiguration. We've had some replication storms after upgrade and we don't have any `replication.pool_size` setting in the testnet configs, which means that the value is taken from the `object.put.pool_size_remote` which is 100. This theoretically means that we could have 100 objects replicating at the same time. Which for 64MB objects means more than 6GB of them (and technically much more than that). There is a lot to optimize in the replication routine, but this particular problem should be solved with a more appropriate config.
