### ISSUE TITLE
`%{NEOFS_NODE_ADDRESS}` is not substituted

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#2305]
https://github.com/nspcc-dev/neofs-node/blob/6f7127a9ea141b8cfd490c8cdc5284cf27dbff73/config/testnet/prometheus.yml#L13

![image](https://user-images.githubusercontent.com/14617699/232990906-76271716-11ee-461a-b1e2-3f6f4f7692ed.png)

**Comment by roman-khimov** [comment]
Take the first from `NEOFS_NODE_ADDRESSES`?

**Comment by 532910** [comment]
metrics should be disabled here, as collectors.fs.neo.org is deconfigured now

https://github.com/nspcc-dev/neofs-node/blob/6f7127a9ea141b8cfd490c8cdc5284cf27dbff73/config/testnet/docker-compose.yml#L24

**Comment by roman-khimov** [comment]
> Take the first from `NEOFS_NODE_ADDRESSES`?

Except I don't see any syntax for that.

**Comment by 532910** [comment]
just remove `prometheus.yml` and other prometheus parts
