### ISSUE TITLE
Add retries to RPC connections

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2307]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I see a storage node not being able to connect to RPC and shutting down because of that (with #2304 sometimes).

## Describe the solution you'd like
It should retry more and have some delay before going through the RPC node list again. Both things need to be configurable, but some sane 5 retries with 5 seconds delay defaults are appropriate.

## Describe alternatives you've considered
Looping forever. An option too (opinions are welcome), that's what NeoGo does for seed nodes, for example, but this may hide configuration errors somewhat. But a delay is needed anyway.

**Comment by notimetoname** [comment]
> Looping forever.

@roman-khimov, AFAIR, that was a feature that _may_ say admin that smth with the network is bad (restarts are seen more easily than some repeated logs (moreover if they are with 5 seconds delay)). Living without morph is bad for most of the components so dying _can_ be the best possibility, no?

**Comment by roman-khimov** [comment]
We can distinguish bad config from bad conditions based on the first connection attempt. If the node tried to connect to every RPC server three times and had not succeeded, then the config is likely broken and it can shutdown with an error. But if it was successful at least once, then likely the config is OK, but what happens now if that the node _will stop_ when it reaches the end of the equally prioritized RPC server list. And restarting the node in this case can cost quite some time which can easily be avoided if it's just to retry.

**Comment by roman-khimov** [comment]
> Yes, but what if the network is down? 

It's likely to get up eventually and stopping doesn't add any benefit.

> Yes, but when it went through the whole list

These lists are usually relatively short.

> nothing will help it until the network is somehow up

That's a wrong assumption to me, occasional disconnects just happen on real networks. It doesn't even require the network to go down completely. So a number of disconnects happen and the node is gone, it'll take time to start again. Instead of just retrying again which is likely to work in most of the cases. Another case is network outage for ~5m, the node will go down again for no good real reason.
