### ISSUE TITLE
Drop deprecated Notifications use from the morph client

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2309]
## Expected Behavior
Not using deprecated APIs.

## Current Behavior
Unfortunately, even after #2308 we have a reference to `c.Notifications` channel in the code. After NeoGo 0.102.0 with nspcc-dev/neo-go#2980 fix it'll no longer be needed.

## Possible Solution
Drop intermediary subscriber/event packages completely. Each service can do `Receive*` for things it needs and each service can then handle a closed connection (related to #1337).

**Comment by notimetoname** [comment]
Blocked until neo-go `v0.102.0` release.
