### ISSUE TITLE
Move documentation out of cmd

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2332]
## Expected Behavior
Documentation in `docs`, code/tests in `pkg` and `cmd`.

## Current Behavior
Quite a lot of command-related documentation is present in the `cmd`.

## Possible Solution
Move it to `docs`.

## Context
I think it's almost impossible to find it in the `cmd`.

**Comment by notimetoname** [comment]
Can it have a subdir with relevant naming? To separate common docs and the "cli" docs?
