### ISSUE TITLE
Fix tests for PRs from forks

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2338]
## Expected Behavior
Any PR running tests fine.

## Current Behavior
Unable to checkout the code if the PR is made from a fork, like in https://github.com/nspcc-dev/neofs-node/actions/runs/4958411498/jobs/8871239674?pr=2336

## Possible Solution
Tune action/checkout likely.

## Steps to Reproduce (for bugs)
Create a PR from fork, see tests failing.

**Comment by roman-khimov** [comment]
Still relevant?

**Comment by vvarg229** [comment]
> Still relevant?

No, the task is finished
