### ISSUE TITLE
Help on ACL details in neofs-cli

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-node#2356]
## Is your feature request related to a problem? Please describe.
I would like to see a map with ACL bits from neofs-cli. 
In the help for `neofs-cli container create` now there is the message
```
      --basic-acl string      HEX encoded basic ACL value or keywords like 'public-read-write', 'private', 'eacl-public-read' (default "private")
```
I need to see a table with bits values, something like this
```
basic ACL: 1fbfbfff (public-read-write)
       RangeHASH    Range      Search     Delete     Put        Head       Get
0 1    1 1 1 1      1 0 1 1    1 1 1 1    1 0 1 1    1 1 1 1    1 1 1 1    1 1 1 1
X F    U S O B      U S O B    U S O B    U S O B    U S O B    U S O B    U S O B
```
and I would like to make it with neofs-cli. 

## Describe the solution you'd like
One might add to `--basic-acl` key a message `To see the basic ACL details run the command: "neofs-cli acl <basic_acl_constant> --help"`. When I run this command, I see a table above.

**Comment by roman-khimov** [comment]
We need a complete list of "pretty" options in `basic-acl` and some reference to `acl basic print` for more details.
