### ISSUE TITLE
Do not put objects to the local storage synchronously

### ISSUE THREAD

**Issue by notimetoname** [nspcc-dev/neofs-node#2359]
https://github.com/nspcc-dev/neofs-node/commit/ef7aeffd4b5a8b79541595f2a0a6e83837ff0689 brought us a "shard-side" load limiting but also took away the possibility to put an object to local and remote storages asynchronously: [see](https://github.com/nspcc-dev/neofs-node/blob/8c56e89bdee9e15c29388df1f77194075eb9d683/pkg/services/object/put/distributed.go#L202-L205) and [see](https://github.com/nspcc-dev/neofs-node/blob/8c56e89bdee9e15c29388df1f77194075eb9d683/pkg/services/object/put/service.go#L63).

What pool size should be chosen is an open question. I think that could be calculated as `numOfShards` * `shardPoolSize` at least.

**Comment by roman-khimov** [comment]
Still relevant?
