### ISSUE TITLE
docker is intendent to run app not OS

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#2379]
neo binaries are static:

```
# ldd /usr/bin/neofs-cli 
	not a dynamic executable
# ldd /usr/bin/neofs-cli 
	not a dynamic executable
```

alpine and bash are not required, please remove them from docker image

**Comment by roman-khimov** [comment]
I thought we have some entry scripts there like we have in NeoGo, but in fact that's not the case, it's just bash and neofs-* binary, so likely this can be improved.
