### ISSUE TITLE
Adapt new NNS contract behavior

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#2390]
* depends on https://github.com/nspcc-dev/neofs-contract/issues/334

after these changes `register` method denies TLD input. Use `registerTLD` method to register system root domains in `neofs-adm morph init` command and others

Also explore other NNS usages within the repository, they almost definitely shouldn't allow to work with TLDs

**Comment by roman-khimov** [comment]
Done in #2662.
