### ISSUE TITLE
Add SQL-like policy setting tool to neofs-cli

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-node#24]
`neofs-cli` needs to work with Storage policy in human friendly format. There should be:
- policy module provinding a way to write a policy in human format (SQL-like, JSON) and apply it netmap (current or pre-constructed)
- container module has to accept human friendly format as storage policy on container creation
- as a best effort, it would be nice to have the ability to translate storage policy of already existing containers from protobuf format into human-readable form.

**Comment by alexvanin** [comment]
I think it is implemented already. There is QL parser (#23, #27) and encoder (#97) for this.
