### ISSUE TITLE
Adapt Neo account contract groups

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#2405]
* track https://github.com/neo-project/proposals/issues/161

when it'll become accepted and implemented, we could replace currently used key sharing mechanism in Sidechain autodeploy procedure introduced in #2402

generally speaking, the proposal may be rejected or accepted for quite a long time. Therefore, the current approach with private key distribution can be tweaked by itself by suggestion https://github.com/nspcc-dev/neofs-node/pull/2402#discussion_r1240344086

**Comment by roman-khimov** [comment]
We no longer have contract keys, so not an issue.
