### ISSUE TITLE
config.yml is outdated

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#2413]
https://github.com/nspcc-dev/neofs-node/blob/master/config/testnet/config.yml

at least `rpc_endpoint` is deprecated. Other deprecated options and other files should be also reviewed.

**Comment by carpawell** [comment]
This file is file not actual at all. See [endpoints](https://github.com/nspcc-dev/neofs-node/blob/27dc0a6c08bfcb43b6a83c8e5440f982587d0800/config/testnet/config.yml#L6-L12) and suggested version [attribute](https://github.com/nspcc-dev/neofs-node/blob/27dc0a6c08bfcb43b6a83c8e5440f982587d0800/config/testnet/config.yml#L24) (well, see also [that](https://github.com/nspcc-dev/neofs-dev-env/pull/261#discussion_r1213360343)).
So at least:
1. Who is a potential user of that files?
2. How can we keep them actual (no one has updated them for ~1 year, and the "user agent" is `v0.27.0`)? I have never contributed to them ever so I just do not track them and do not think about them at release time. We have solved the "unactual" problem for CHANGELOG and storage config documentation with GH actions, so I see that files useless until the same (or smth like the same) is done for them too.

cc @roman-khimov, @cthulhu-rider

**Comment by cthulhu-rider** [comment]
possibly relates or duplicates #2366

**Comment by roman-khimov** [comment]
Duplicates #2366.
