### ISSUE TITLE
batch storage wallets generation

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#2425]
```
% for a in node{01..99}; do
    ./neofs-adm morph -c config.yaml generate-storage-wallet --storage-wallet wallets/${a}-storage.json --initial-gas 5.0 --alphabet-wallets alphabet --label empty
done
```
This takes too long due to `Waiting for transactions to persist...`

**Comment by roman-khimov** [comment]
20 nodes, 15s blocks -> 2.5-5m for the task, not that much, but somewhat more than it could be (and we could have a 100 nodes). Some additional command is needed to take the number of nodes, dir to store wallets and go.

**Comment by carpawell** [comment]
Provided example creates wallets with a single (the same for all) password as provided in `config.yaml`. Is it expected? If we add a new command for a bunch of wallets, will you expect them to have the same password? Will you change 100 passwords? Will you be ready to read the passwords from some other file `neofs-adm` will have created?

I can also suggest some `no-block` (or `not-await` like the opposite of our `await` flags) flag to the _already created_ `generate-storage-wallet` command. It will be possible to go `for` and not to wait block to persist, then wait for 1 or 2 blocks (i expect 100 transfers to fit a single block) and then just go another `for` to check that all the wallets have been top up.

**Comment by 532910** [comment]
> same password

Exactly, moreover, it's not just the same, it's empty!

How often do you set a password for SSL keys?

**Comment by carpawell** [comment]
I think @roman-khimov has something to say about default empty passwords.

**Comment by roman-khimov** [comment]
OK, let's use the same configured (or provided) password. It's up to the user after all. The only problem is output file name pattern, can be some `-XX` suffix.
