### ISSUE TITLE
Adopt support of `OnNEP17PaymentData` contract call arg

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#2429]
when https://github.com/nspcc-dev/neo-go/issues/2987 will be released, and we'll be able to pass `OnNEP17PaymentData` instances to actor's contract calls. In particular, this could be used in Sidechain deployment routine.

**Comment by AnnaShaleva** [comment]
Ref. https://github.com/nspcc-dev/neofs-node/pull/2408#discussion_r1252037170.
