### ISSUE TITLE
IR: Replace Glagolitic letters with indices for Alphabet

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#2431]
it's extremely inconvenient to name Alphabet members by letters of the Glagolitsa alphabet. When i see exact glagolitic letter, i cannot easily realize it's ordinal number. We also cannot support Alphabet size > 41.

i propose to simplify the identification of Alphabet members and index them from 0. Note that this could make Alphabet term irrelevant. For example, we already use indices for NNS domains (`alphabet0.neofs`, `alphabet1.neofs`, ...)

**Comment by roman-khimov** [comment]
Not now. I agree it's very inconvenient in many ways, but it at the same time is very deep in the system. So it's highly risky changing it and not a lot that we gain here (functionally it works).

**Comment by carpawell** [comment]
See also https://github.com/nspcc-dev/neofs-node/issues/2422.
