### ISSUE TITLE
neofs-cli container set-eacl should check that the wallet is the wallet of the container owner 

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-node#2436]
## Is your feature request related to a problem? Please describe.
I write tests on the issue https://github.com/nspcc-dev/neofs-testcases/issues/579
and I found tha`t neofs-cli container delete` and `neofs-cli container set-eacl` handle differently the negative scenario when another user without session token tries to delete a container or set eact.

```
neofs-cli --config /home/varg/work/neofs-testcases/wallet_config.yml container delete --rpc-endpoint 's01.neofs.devenv:8080' --wallet '/home/varg/work/neofs-testcases/TemporaryDir/not_owner_c3406d7b-bce1-43a8-837b-c6b8b52d001e.json' --cid '4jbzrNfyLN7fo6hAMSdbHn9iNZEpKGaosgf1JKHMsmve' --await
return code: 1
output: provided account differs with the container owner: expected NbKfM2i4XeY5rzJRRiR2qxqgwDgMc5Phsc, has NhFabTpE2q2ejFoMcUjcsUM7iEopA5n8jk
```

```
neofs-cli --config /home/varg/work/neofs-testcases/wallet_config.yml --verbose container set-eacl --rpc-endpoint 's01.neofs.devenv:8080' --wallet '/home/varg/work/neofs-testcases/TemporaryDir/not_owner_wallet.json' --cid '67NYwN62AUGfqszbzaLHPZRkJP8abLKWBy99ip8LePmn' --await --table '/home/varg/work/neofs-testcases/TemporaryDir/TestFilesDir/eacl_table_05986754-1af5-4fe8-98de-10077155b86b.json
timed out after 90 seconds
```

## Describe the solution you'd like
neofs-cli container set-eacl should check that the wallet is the wallet of the container owner and fail without going to the NeoFS.

## Describe alternatives you've considered
Leave it as it is

**Comment by carpawell** [comment]
For container removal, we also got [the request](https://github.com/nspcc-dev/neofs-node/issues/2106) from the testing team first and just [did](https://github.com/nspcc-dev/neofs-node/pull/2143) it then. The same can be done for `set-eacl` I guess.

**Comment by roman-khimov** [comment]
Some `--force` should be available as well to set it at the NeoFS API level.
