### ISSUE TITLE
Failed to get the header of a complex object

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-node#2440]
Tests `test_object1_can_be_get_by_attr, test_object2_can_be_get_by_attr, test_put_http_get_http, test_put_http_get_http_curl, test_http_attr_priority_epoch_duration, test_object_can_be_put_get_by_streaming, test_put_grpc_get_http, test_put_with_bearer_when_eacl_restrict, test_object_put_get_attributes, test_put_http_get_http_large_file test_storagegroup_basic_public_container` fall when trying to get the header of a complex object

For example, `test_object_put_get_attributes`:
https://http.t5.fs.neo.org/86C4P6uJC7gb5n3KkwEGpXRfdczubXyRNW5N9KeJRW73/200-1689334253/index.html#categories/67f6bc5b6a0f2fa5ee214ce714fa67cb/277e01d06deb1e7d/

```
RuntimeError: Command: neofs-cli --config /home/runner/work/neofs-node/neofs-node/neofs-testcases/wallet_config.yml object get --rpc-endpoint 's04.neofs.devenv:8080' --wallet '/home/runner/work/neofs-node/neofs-node/neofs-testcases/TemporaryDir/66c0890f-02e1-4402-8a21-b3ebb609ef47.json' --cid 'CEtoXBBt5wrHndXwSBqvKdY3fR3ob7hqRif4bXikYvzg' --oid 'C64v4YTPdSJdp3LaEECxVsy1peixSndytbDCzCS84a3x' --file 'TemporaryDir/TestObjectsDir/8201da02-b3e2-4e15-97ee-4326c6517a1d' --no-progress
Error:
return code: 1
output: rpc error: read object header: status: code = 2049 message = object not found
```

Logs from test_object_put_get_attributes:
[e3f34e9008c6948f.zip](https://github.com/nspcc-dev/neofs-node/files/12051553/e3f34e9008c6948f.zip)

Full logs:
[16bbf66fa515ee23.zip](https://github.com/nspcc-dev/neofs-node/files/12051544/16bbf66fa515ee23.zip)

## Expected Behavior
Tests must be passed

## Current Behavior
Tests are failing

## Steps to Reproduce (for bugs)
Run `test_object1_can_be_get_by_attr, test_object2_can_be_get_by_attr, test_put_http_get_http, test_put_http_get_http_curl, test_http_attr_priority_epoch_duration, test_object_can_be_put_get_by_streaming, test_put_grpc_get_http, test_put_with_bearer_when_eacl_restrict, test_object_put_get_attributes, test_put_http_get_http_large_file test_storagegroup_basic_public_container` tests

## Context
I'm trying to get consistently green tests.

## Regression
Yes

## Your Environment
neo-go version 0.101.1
neofs-s3-authmate version v0.27.1
neofs-s3-gw version v0.27.1
neofs-adm version fc824ee9
neofs-ir version c824ee9
neofs-lens version fc824ee9
neofs-cli version fc824ee9
aws-cli/2.13.0
Python/3.11.4
Linux/5.15.0-1041-azure exe/x86_64.ubuntu.22 prompt/off

**Comment by vvarg229** [comment]
Here's the result of the full test suite:
https://http.t5.fs.neo.org/86C4P6uJC7gb5n3KkwEGpXRfdczubXyRNW5N9KeJRW73/204-1689413727/index.html#
You can see that it affects almost all tests.

**Comment by vvarg229** [comment]
Also in tests `test_static_session_expiration_at_next, test_static_session_start_at_next, test_static_session_range, test_static_session_range, test_static_session_expiration_at_next, test_static_session_start_at_next` I see this error:

```
COMMAND: neofs-cli --config /home/runner/work/neofs-node/neofs-node/neofs-testcases/wallet_config.yml object head --rpc-endpoint 's01.neofs.devenv:8080' --wallet '/home/runner/work/neofs-node/neofs-node/neofs-testcases/TemporaryDir/b197d365-eb5f-47a8-96d2-9bb094ad52b1.json' --cid '83fLCWRHBrc3cFc81eXLUKyrbf4NSkE8vMvPAKLaJUZ8' --oid 'CUVzNMnABcQpB4wKfxY7JMr6xZYPYAovHs2KqsTuPegj' --json --session '/home/runner/work/neofs-node/neofs-node/neofs-testcases/TemporaryDir/TestFilesDir/fc27ccd9-4946-421a-a943-dc169850537e'
RETCODE: 1

STDOUT:
rpc error: read object header via client: status: code = 1024 message = malformed request: token is invalid at 37 epoch)

STDERR:

Start / End / Elapsed	 18:19:55.927668 / 18:19:56.379687 / 0:00:00.452019
```
Report:
https://http.t5.fs.neo.org/86C4P6uJC7gb5n3KkwEGpXRfdczubXyRNW5N9KeJRW73/204-1689440482/index.html#suites/caeb93ac7a2ae98f9e4a3c59e66fe114/c33bf235f8f5adc4/

Could these errors be related?

**Comment by smallhive** [comment]
Tried test `test_object_put_get_attributes` localy
```
pytest --alluredir my-allure-123 pytest_tests/testsuites/services/http_gate/test_http_[object.py](http://object.py/) -k test_object_put_get_attributes
```
[allure report](https://github.com/nspcc-dev/neofs-node/files/12104643/2440.zip)

**Comment by roman-khimov** [comment]
@vvarg229, what's the status of this test now?

**Comment by vvarg229** [comment]
@roman-khimov All tests passed:
`test_object1_can_be_get_by_attr` https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1226-1706208311/index.html#suites/56819eac8c6b9f0929ba3395135425e2/f235d8bf589538e6/
`test_object2_can_be_get_by_attr` https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1226-1706208311/index.html#suites/56819eac8c6b9f0929ba3395135425e2/f235f97a31701cd1/
`test_put_http_get_http` https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1226-1706208311/index.html#suites/144283e21f306ff2dca3ac842153fb15/80a1b38fac0016e0/
`test_put_http_get_http_curl` https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1226-1706208311/index.html#suites/144283e21f306ff2dca3ac842153fb15/ecf0b72a38c8de80/
`test_http_attr_priority_epoch_duration` https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1226-1706208311/index.html#suites/0da9032b8578220ee37fc688cc2e3cc9/4d83812faedaf9b3/
`test_object_can_be_put_get_by_streaming` https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1226-1706208311/index.html#suites/876bf3abcee03cebd59be713dd025520/779116529cb994c6/
`test_put_grpc_get_http` https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1226-1706208311/index.html#suites/144283e21f306ff2dca3ac842153fb15/c8afaa25aa4fa52b/
`test_put_with_bearer_when_eacl_restrict` https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1226-1706208311/index.html#suites/9e00e2624fd1ccb96d877b6e649598cb/65b08c71507eb448/
`test_object_put_get_attributes` https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1226-1706208311/index.html#suites/82c0ac5485b616b3e4c99dbed27900d7/90383343f64446a3/
`test_put_http_get_http_large_file` https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1226-1706208311/index.html#suites/144283e21f306ff2dca3ac842153fb15/c82d51ea0727963/
`test_storagegroup_basic_public_container` https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1226-1706208311/index.html#suites/69b447004f3c682f67955ec900a09cf0/f9ac5a936ed9f15f/

I think we should close this issue.
