### ISSUE TITLE
Incorrect handling of quotes in the policy option when creating a container

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-node#2441]
Quotation marks are not handled correctly, because of this, tests `test_placement_policy_with_nodes, test_object_session_token` failed.

For example in test `test_placement_policy_with_nodes` with  `placement_rule: 'REP 1 IN LOC_PLACE CBF 1 SELECT 1 FROM LOC_SW AS LOC_PLACE FILTER Country EQ Sweden AS LOC_SW'` https://http.t5.fs.neo.org/86C4P6uJC7gb5n3KkwEGpXRfdczubXyRNW5N9KeJRW73/205-1689504895/index.html#suites/a6143bdccc5de4a5db4c836d1239fad4/ada0117750ca52a2/ :
```
COMMAND: neofs-cli --config /home/runner/work/neofs-node/neofs-node/neofs-testcases/wallet_config.yml container create --rpc-endpoint 's01.neofs.devenv:8080' --wallet '/home/runner/work/neofs-node/neofs-node/neofs-testcases/TemporaryDir/3a564e68-4ef7-4215-b460-7644a00559f1.json' --basic-acl '0FBFBFFF' --await --policy 'REP 1 IN LOC_PLACE CBF 1 SELECT 1 FROM LOC_SW AS LOC_PLACE FILTER Country EQ Sweden AS LOC_SW'
RETCODE: 1

STDOUT:
could not build container nodes based on given placement policy, use --force option to skip this check: not enough nodes to SELECT from: 'LOC_PLACE'

STDERR:

Start / End / Elapsed	 11:33:47.015068 / 11:33:47.410508 / 0:00:00.395440
```

The same test with the previous version https://nspcc-dev.github.io/neofs-node/208/#suites/a6143bdccc5de4a5db4c836d1239fad4/d5717f297167236d/ :

```
COMMAND: neofs-cli --config /home/runner/work/neofs-node/neofs-node/neofs-testcases/wallet_config.yml container create --rpc-endpoint 's01.neofs.devenv:8080' --wallet '/home/runner/work/neofs-node/neofs-node/neofs-testcases/TemporaryDir/62516026-3c50-4eac-bd40-dcc11bbe953f.json' --basic-acl '0FBFBFFF' --await --policy 'REP 1 IN LOC_PLACE CBF 1 SELECT 1 FROM LOC_SW AS LOC_PLACE FILTER Country EQ Sweden AS LOC_SW'
RETCODE: 0

STDOUT:
container ID: FfYJzf3BBpz8zCzmi694gtBcVyxH9Pg8pehbFAchDVDK
awaiting...
container has been persisted on sidechain

STDERR:

Start / End / Elapsed	 14:43:51.937187 / 14:43:53.373396 / 0:00:01.436209
```

Full report and logs:
https://http.t5.fs.neo.org/86C4P6uJC7gb5n3KkwEGpXRfdczubXyRNW5N9KeJRW73/205-1689504895/index.html#

## Expected Behavior
Quotes should be handled correctly

## Current Behavior
Quotes are not handling correctly.

## Steps to Reproduce (for bugs)
Run `test_placement_policy_with_nodes` or `test_object_session_token`

## Context
I'm trying to get consistently green tests.

## Regression
Yes

## Your Environment
neo-go version 0.101.1
neofs-s3-authmate version v0.27.1
neofs-s3-gw version v0.27.1
neofs-adm version fc824ee9
neofs-ir version c824ee9
neofs-lens version fc824ee9
neofs-cli version fc824ee9
aws-cli/2.13.0
Python/3.11.4
Linux/5.15.0-1041-azure exe/x86_64.ubuntu.22 prompt/off

**Comment by roman-khimov** [comment]
Works fine since 235c831c.
https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/582-1692787666/index.html

**Comment by roman-khimov** [comment]
Related to dev-env fix https://github.com/nspcc-dev/neofs-dev-env/pull/276
