### ISSUE TITLE
Rework blobovnicza tree

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2453]
## Is your feature request related to a problem? Please describe.
#2382, current bbcz tree is needlessly complex and fragile.

## Describe the solution you'd like
One DB per shard is sufficient.

## Describe alternatives you've considered
Keeping some number of them doesn't seem to be helpful.

## Additional context
We need migration.

**Comment by carpawell** [comment]
> One DB per shard is sufficient.

How about one layer of DBs? Can it be more optimal for storing small objects? No open DBs caches and no complex logic at all but just one layer.

**Comment by roman-khimov** [comment]
BTW, speaking of names, blobovnicza is not really appropriate here as these are not BLOBs. They're more of a BSOB or BMOB.

**Comment by cthulhu-rider** [comment]
> speaking of names

blobovnicza should be definitely replaced. I thought about new one a bit: "bolt with tiny objects" - boltin/bolbin.

**Comment by roman-khimov** [comment]
`boltiny`: :+1: 
`peapod`: :tada:
`pisum`: :rocket:

**Comment by carpawell** [comment]
IMO, naming should not depend on a certain DB name.

**Comment by cthulhu-rider** [comment]
`pisum` is ok to me, but ceteris paribus i'd select other one

**Comment by roman-khimov** [comment]
Fixed in #2462, but not closed.

**Comment by cthulhu-rider** [comment]
> Fixed in #2462, but not closed.

do we need anything within this issue?

**Comment by roman-khimov** [comment]
It's done to me. We will drop bbcz eventually and we will optimize peapod additionally, we may simplify configurations, but all of those are different things.
