### ISSUE TITLE
Announce node version in SN attributes automatically

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2455]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I can't tell what node versions are being used on the network. We even have nspcc-dev/neofs-contract#299.

## Describe the solution you'd like
We can have version in an attribute for now. Node can set it automatically, but allow to override via config (much like #602). These attributes should be documented appropriately.

**Comment by carpawell** [comment]
> but allow to override via config

What can it be useful for?

> These attributes should be documented appropriately.

How (where) should the docs be placed? API? This repo? Is it gonna be another [well-known attr](https://github.com/nspcc-dev/neofs-api/blob/b8476e4b5f24e64388bd0532e2652fec4ba121db/netmap/types.proto#L160-L208)?

**Comment by roman-khimov** [comment]
> What can it be useful for?

It's an attribute and in general it can't be checked server-side. Maybe there is some use case for overrides as well. But I mostly mean that if you set it in the config (just like any other attribute), it should win over the default value because that's the thing written in the config and expected to be used by admin.

> How (where) should the docs be placed? API? This repo?

Everywhere. Node behavior should be documented for admin, API should be documented for API users.

> Is it gonna be another well-known attr?

Yep, looks like this. It doesn't affect anything at the moment, yet at the same time it's very useful to have some admin-level visibility into the system.
