### ISSUE TITLE
Drop compatibility code from loadPlacementBuilder.BuildPlacement

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2456]
## Expected Behavior
Placements are provided by SDK.

## Current Behavior
We had to replicate the old behavior in loadPlacementBuilder.BuildPlacement when updating to RC8 (#2346).

## Possible Solution
We will be updating to RC10 and when that happens we'll have new sorting everywhere. So we can drop this code at the same time and either don't use placement there at all or generate some OID for it as needed.

Refs. nspcc-dev/neofs-sdk-go#438 and #2442.

**Comment by cthulhu-rider** [comment]
i see two ways:
1. calc fake `oid.ID` with `load_announcement_<epoch>0000...` with fixed-len epoch
2. sort nodes by public keys lexicographically

**Comment by cthulhu-rider** [comment]
> 2. you mean the same "main" node for the same container set every epoch?

yes, why not (taking into account many containers with different leaders). We can also rotate leader by epoch, but this doesn't make much difference

**Comment by carpawell** [comment]
If we _need_ to have it fine with RC10 I would go that [way](https://github.com/nspcc-dev/neofs-node/commit/0309a6705ca3bb89d16fae3d34417fdfdda7ef39#diff-e0838346ed7a3bbb2ec458701698ddc84ae2ef9f2b7ea43de69482b2b3a09dcdR404-R410) (the same node subset choose a different node for a different container).

Also, I am totally ok with a separate func in SDK (does not apply any pivot at all, only the epoch).

> yes, why not

Not good for a decentralized network IMO. Predefined node does all the money work.

**Comment by cthulhu-rider** [comment]
> Not good for a decentralized network IMO

if u focus on decentralization, then each node will act for itself and send own values directly to the contract instead of other untrusted node (rotation changes nothing in terms of decentralization)

**Comment by roman-khimov** [comment]
> each node will act for itself and send own values directly to the contract instead of other untrusted node (rotation changes nothing in terms of decentralization)

That's the way it should be. But long-term. Short-term we need to rotate leaders in some predictable manner.

**Comment by roman-khimov** [comment]
Fixed in #2478 without a reference?

**Comment by carpawell** [comment]
Yes.
