### ISSUE TITLE
Possible incorrect error when a container is deleted by a static session token without the right permissions

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-node#2466]
I write tests on the issue https://github.com/nspcc-dev/neofs-testcases/issues/579
and I found that neofs-cli container delete handle differently in the negative case when a non-valid wallet is specified.
The difference is which static session token I use - the one created on the container owner's wallet, or the one created on another wallet.

## Expected Behavior
I'm not sure it's exactly a bug, I'd like to discuss what behavior we expect in which case.

## Steps to Reproduce (for bugs)
1. Create container
2. Create static session token using container owner wallet
3. Create static session token using another wallet
4. Try to delete container using static session token from step 2 - you'll get a "timed out after 90 seconds" error.
5. Try to delete container using static session token from step 3 - you'll get a "session issuer differs with the container owner" error.

See allure reports:

[report.zip](https://github.com/nspcc-dev/neofs-node/files/12232955/report.zip)
[report_2.zip](https://github.com/nspcc-dev/neofs-node/files/12232956/report_2.zip)

Test code:
```
    @allure.title("Not owner and not trusted party can NOT delete container")
    def test_static_session_token_container_delete_only_trusted_party_proved_by_the_container_owner(
            self,
            owner_wallet: WalletFile,
            user_wallet: WalletFile,
            stranger_wallet: WalletFile,
            scammer_wallet: WalletFile,
            static_sessions: dict[ContainerVerb, str],
            temp_directory: str,
            not_owner_wallet,
    ):
        with allure.step("Create container"):
            cid = create_container(
                owner_wallet.path,
                shell=self.shell,
                endpoint=self.cluster.default_rpc_endpoint,
            )

        user_token = self.static_session_token(owner_wallet, user_wallet, self.shell, temp_directory)
        stranger_token = self.static_session_token(user_wallet, stranger_wallet, self.shell, temp_directory)

        with allure.step("Try to delete container using scammer token"):
            with pytest.raises(RuntimeError, match=NOT_SESSION_CONTAINER_OWNER):
                delete_container(
                    wallet=scammer_wallet.path,
                    cid=cid,
                    session_token=stranger_token[ContainerVerb.DELETE],
                    shell=self.shell,
                    endpoint=self.cluster.default_rpc_endpoint,
                    await_mode=True,
                )

        with allure.step("Try to delete container using scammer token"):
            with pytest.raises(RuntimeError, match=NOT_SESSION_CONTAINER_OWNER):
                delete_container(
                    wallet=scammer_wallet.path,
                    cid=cid,
                    session_token=user_token[ContainerVerb.DELETE],
                    shell=self.shell,
                    endpoint=self.cluster.default_rpc_endpoint,
                    await_mode=True,
                )
```

## Your Environment
neo-go
0.101.1
neofs-s3-authmate
0.27.1
neofs-cli
0.36.1-125-g8cda197e
neofs-adm
0.36.1-125-g8cda197e
AWS
aws-cli/2.9.19 Python/3.11.4 Linux/6.2.0-25-generic source/x86_64.ubuntu.23 prompt/off

**Comment by cthulhu-rider** [comment]
> I'd like to discuss what behavior we expect in which case

expected behavior is described in https://github.com/nspcc-dev/neofs-testcases/issues/579, so any other behaviors are incorrect (bug)

**Comment by vvarg229** [comment]
> > I'd like to discuss what behavior we expect in which case
> 
> 
> 
> expected behavior is described in https://github.com/nspcc-dev/neofs-testcases/issues/579, so any other behaviors are incorrect (bug)

Yes, but there's no description of expected errors

**Comment by cthulhu-rider** [comment]
> > > I'd like to discuss what behavior we expect in which case
> > 
> > 
> > expected behavior is described in [nspcc-dev/neofs-testcases#579](https://github.com/nspcc-dev/neofs-testcases/issues/579), so any other behaviors are incorrect (bug)
> 
> Yes, but there's no description of expected errors

added https://github.com/nspcc-dev/neofs-testcases/issues/579#issuecomment-1661633619

**Comment by roman-khimov** [comment]
It's the same thing (see #2501 as well).
