### ISSUE TITLE
Check SN availability when approving it for a netmap

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2475]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I see new nodes on the map, but they're not responding to any queries (port closed/firewalled/whatever, but the node is unreachable).

## Describe the solution you'd like
Check availability of the node before approving it.

**Comment by cthulhu-rider** [comment]
[EndpointInfo](https://github.com/nspcc-dev/neofs-api/blob/953b4c5a9df1409da2a795b34bf9af66699689c6/netmap/service.proto#L27) could be good for this:
* node should be online to respond
* we'll may use response to make some sanity checks in the future

any other ideas?

**Comment by roman-khimov** [comment]
Makes sense. It can be checked against node data we have in the request.
