### ISSUE TITLE
IR healthcheck is broken on SDK RC-10

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#2477]
```
$ neofs-cli -c cli.yml control healthcheck --ir --endpoint localhost:8070 -w wallet.json
Enter password > 
can't create API client: can't init SDK client: write request: rpc error: code = Unimplemented desc = unknown service neo.fs.v2.netmap.NetmapService
```

reason is in https://github.com/nspcc-dev/neofs-sdk-go/blob/8e843feba00f8aab93994291cd5f894c9acc3b06/client/client.go#L125: Inner Ring doesn't serve `NetmapService`

at the same time, CLI uses https://pkg.go.dev/github.com/nspcc-dev/neofs-sdk-go/client#Client.ExecRaw to request IR's `ControlService`

**Comment by carpawell** [comment]
I think SN/IR just should not use `client.Client` and have some internal gRPC handling code. `control` <-> `neofs-api` relation is a coincidence, they should not (re)use each other.

**Comment by roman-khimov** [comment]
Isn't it fixed already?

**Comment by carpawell** [comment]
@roman-khimov, healthcheck -- [yes](https://github.com/nspcc-dev/neofs-node/commit/1513b785124431efb82ba9ce2dc7d9df59165cb4), having neofs-api-go dep for `control` service -- no. Another issue for that? Continue here?

**Comment by roman-khimov** [comment]
That's a different one, if we have a working control service then we're fine here.
