### ISSUE TITLE
Support static data slicing in CLI `object put`

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#2482]
starting from https://github.com/nspcc-dev/neofs-sdk-go/releases/tag/v1.0.0-rc.10 NeoFS CLI may support both local and remote data slicing (currently only remote)

static slicing may be an option, dynamic - default behavior (to keep current behavior)

**Comment by cthulhu-rider** [comment]
* not related directly, but similar feature is considered in https://github.com/nspcc-dev/neofs-s3-gw/issues/808

**Comment by roman-khimov** [comment]
Duplicates #952.
