### ISSUE TITLE
neofs-cli container set-eacl --force allows successful modification with the same table but a non-owner wallet

### ISSUE THREAD

**Issue by AliceInHunterland** [nspcc-dev/neofs-node#2498]
Using `neofs-cli container set-eacl -f` with the same table that has already been set by the owner results in successful modification even if the user is not the container owner or authorized representative. 

`neofs-cli container set-eacl -f -w /non-owner-wallet.json --table /already-set-by-owner-table.json`  skips verification and is expected to catch a timeout as `neofs-cli container set-eacl -f -w /non-owner-wallet.json --table /different-table.json` does in such case ( only owner or authorized representative can set a table). However, it finishes with `EACL has been persisted on sidechain`.  The key point of the bug is that the table is the same as the owner has already set.
## Expected Behavior

```
neofs-cli container set-eacl -f -w /non-owner-wallet.json --table /already-set-by-owner-table.json
eACL modification request accepted for processing (the operation may not be completed yet)
awaiting...
eACL modification was requested, but timeout has happened while waiting for the outcome
``` 

## Current Behavior

```
neofs-cli container set-eacl -f -w /non-owner-wallet.json --table /already-set-by-owner-table.json
eACL modification request accepted for processing (the operation may not be completed yet)
awaiting...
EACL has been persisted on sidechain
``` 
## Possible Solution

We can't prevent the issue entirely, but we can make certain cases easier. By comparing the sent and received data, we can't eliminate false positives due to lack of feedback. However, we can check and compare tables before transactions. If they match, we can avoid unnecessary requests, indicating the table is already set. This simplifies scenarios like accidental command repetition.
## Steps to Reproduce (for bugs)

1. Create a container:
```
neofs-cli -r localhost:8080 -w ./owner_wallet.json container create --policy "REP 1" --basic-acl eacl-public-read-write --await
``` 
2. Set the EACL table by the owner:
```
neofs-cli -r localhost:8080 -w ./owner_wallet.json --cid 3dbidwCq7uQF6vboU977XBX7qBM1i1JimXntgV2cCCc1  container set-eacl --table ./eacl_table.json --await
``` 
3. Attempt to set the same EACL table by a non-owner:
```
./bin/neofs-cli -r localhost:8080 -w ./non_owner_wallet.json --cid 3dbidwCq7uQF6vboU977XBX7qBM1i1JimXntgV2cCCc1  container set-eacl --table ./eacl_table.json --await
```

**Comment by roman-khimov** [comment]
There might be cases when you really need a transaction to happen, in that sense I'd expect `--force` to still perform the required action. When I'm using `--force` I have a reason to do that and I don't want to be stopped by some logic like that.

And yes, we don't have a transaction ID and current `--await` logic is very fragile. I'd leave it as is, non-forced invocations are fine and forced ones can't be fixed with the current API.

**Comment by roman-khimov** [comment]
Nothing to fix here.
