### ISSUE TITLE
Invalid error output when other role sending a request with prohibited headers

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-node#2502]
```
COMMAND: neofs-cli --config /home/runner/work/neofs-node/neofs-node/neofs-testcases/wallet_config.yml object put --rpc-endpoint 's03.neofs.devenv:8080' --wallet '/home/runner/work/neofs-node/neofs-node/neofs-testcases/TemporaryDir/35f9b04a-bd7a-49ca-8cf9-87ba2f3fa5ed.json' --cid '3Ycb48kajSy8LSgyLTSSh3CKDL7k6trkpmsGUs2ocXLd' --file '/home/runner/work/neofs-node/neofs-node/neofs-testcases/TemporaryDir/TestFilesDir/27500f3b-c150-4c04-89f7-bd6a373455a9' --no-progress --xhdr 'check_key=other_value'
RETCODE: 1

STDOUT:
rpc error: copy data into object stream: EOF

STDERR:

Start / End / Elapsed	 08:58:55.583929 / 08:58:56.097062 / 0:00:00.513133
```

See:
https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/490-1692002283/index.html#suites/526197b5274bae768c0a631fa726cb06/493b4e3adb61f806/

## Expected Behavior
We expect an error message like this:
`rpc error: read object header via client: status: code = 2049 message = object not found`

## Current Behavior
`rpc error: copy data into object stream: EOF`

## Steps to Reproduce (for bugs)
Run `test_extended_acl_filters_request` or `test_extended_acl_filters_request` test.

## Regression
Yes
https://github.com/nspcc-dev/neofs-node/pull/2493
https://github.com/nspcc-dev/neofs-node/actions/runs/5831023199
@cthulhu-rider 

## Your Environment
neo-go 0.101.1
neofs-s3-authmate 0.27.1
neofs-cli 86c5d3b7
neofs-adm 86c5d3b7
AWS aws-cli/2.13.7 Python/3.11.4 Linux/5.15.0-1042-azure exe/x86_64.ubuntu.22 prompt/off

**Comment by cthulhu-rider** [comment]
duplicates #2500, but current is more informational so ill close that one

**Comment by roman-khimov** [comment]
Keeping the first issue is preferable, additional data can be retrieved from links. But OK, keeping this one here.

**Comment by vvarg229** [comment]
> > Regression
> 
> > Yes
> 
> > https://github.com/nspcc-dev/neofs-node/pull/2493
> 
> 
> 
> @vvarg229, what do you mean by that? I does not seem to be the reason. Or you meant that was the last working PR?

Sorry for the incomplete description.
I mean it's the PR after which the tests started failing with this error.
