### ISSUE TITLE
Incorrect processing of branches specified in workflow_dispatch

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-node#2509]
https://github.com/nspcc-dev/neofs-node/blob/master/.github/workflows/run-tests.yml#L20

This will not work, only the master will always be used:
https://github.com/nspcc-dev/neofs-node/blob/master/.github/workflows/run-tests.yml#L54

We need to fix the description in workflow_dispatch, or fix the work with branches. The second is better.

**Comment by roman-khimov** [comment]
Long obsolete.
