### ISSUE TITLE
incorrect expire_at behavior for a bearer token 

### ISSUE THREAD

**Issue by evgeniiz321** [nspcc-dev/neofs-node#2538]
Related to https://github.com/nspcc-dev/neofs-testcases/pull/621

## Expected Behavior
I set lifetime=1 and expire_at=current_epoch + 1 and I expect that the bearer token will expire after 2 epoch ticks. In other scenarios with lifetime, expire_at params(e.g. locking tests) it works ok. 

## Current Behavior
But for the bearer token, I have to set expire_at=current_epoch + 2 during the token creation to have the same behavior as with lifetime=1

## Steps to Reproduce (for bugs)
1. Allure - ```test_bearer_token_expiration``` [allure.tar.gz](https://github.com/nspcc-dev/neofs-node/files/12492082/allure.tar.gz). Notice expire_at parametrized test. It uses expire_at=current_epoch + 2. With current_epoch+1 it fails constantly. 

## Regression
(No)

## Your Environment
Run on current latest master of neofs-node - 98717120a74c62b328b45f036f770b02685fb9b8

**Comment by carpawell** [comment]
@evgeniiz321, @vvarg229, @roman-khimov, shouldn't [those lines](https://github.com/nspcc-dev/neofs-testcases/blob/7af282f90f32e80301a146c91d9db49ee2bcb0b8/pytest_tests/testsuites/acl/test_bearer.py#L247-L248) be swapped?

**Comment by roman-khimov** [comment]
Likely so.

**Comment by roman-khimov** [comment]
Test issue, fixed in https://github.com/nspcc-dev/neofs-testcases/pull/638
