### ISSUE TITLE
Rename `neofs-lens [...] inspect`

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#2548]
## Is your feature request related to a problem? Please describe.
We have some set of `neofs-lens` "storage" subcommands: `meta`, `write-cache`, `peapod`, `blobovnicza`. All of them have `inspect` command that means `get` _literally_. It does a component's `Get` method call and returns an object. `inspect` is more like research and fetching some additional info to me.

## Describe the solution you'd like
`inspect` -> `get` subcommand renaming.

## Describe alternatives you've considered
Keep it as is. But it is likely that we will have some more commands for the `inspect` word in the future.

**Comment by roman-khimov** [comment]
We need to keep inspect for one release as an alias.

**Comment by AliceInHunterland** [comment]
> We need to keep inspect for one release as an alias.

do we want to use cobra functionality for inspect deprecation? or just renaming is okay?

**Comment by carpawell** [comment]
> or just renaming is okay?

I think we need to copy-paste all the `inspect` functions and name them `get`. The old ones should be deprecated (if the cobra has smth to print about the deprecation, that is a good addition too), CHANGELOG should say that we have the new ones and every good dev should use it from now. And that is all for the `v0.39.0`.

`v0.40.0` should just drop `inspect` (with the corresponding CHANGELOG record).
