### ISSUE TITLE
Improve neofs-adm morph set-config --force documentation

### ISSUE THREAD

**Issue by evgeniiz321** [nspcc-dev/neofs-node#2555]
## Is your feature request related to a problem? Please describe.
related to https://github.com/nspcc-dev/neofs-testcases/pull/628. It is not clear when --force flag should be used and the behavior is not clear as well. E.g. if I set some unknown_key to 120 with the force flag. I will get this back:

```
COMMAND: neofs-cli --config ./TemporaryDir/empty-password.yml netmap netinfo --rpc-endpoint 's01.neofs.devenv:8080' --wallet '../neofs-dev-env/services/storage/wallet01.json'
RETCODE: 0

STDOUT:
Epoch: 5
Network magic: [net 0x3c2d] 15405
Time per block: 1s
NeoFS network configuration (system)
  Audit fee: 10000
  Storage price: 100000000
  Container fee: 1000
  EigenTrust alpha: 0.1
  Number of EigenTrust iterations: 4
  Epoch duration: 240
  Inner Ring candidate fee: 10000000000
  Maximum object size: 524288
  Withdrawal fee: 100000000
  Homomorphic hashing disabled: false
  Maintenance mode allowed: false
NeoFS network configuration (other)
  SystemDNS: 636f6e7461696e6572
  unknown_key: 313230
```
Unknown key is now equal to 313230. It is not obvious why it is so. 

## Describe the solution you'd like
Please add an example of the 'right' force usage and what to expect in the end.

## Don't forget to add labels!
- component label (`neofs-adm`, `neofs-storage`, ...)
- issue type (`enhancement`, `refactor`, ...)
- `goodfirstissue`, `helpwanted` if needed
- does this issue belong to an epic?
- priority (`P0`-`P4`) if already triaged
- quarter label (`202XQY`) if possible

**Comment by roman-khimov** [comment]
The behaviour itself is OK, but it needs to be explained in doc.
