### ISSUE TITLE
Implement PoR check in data audit

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#256]
In single audit task (see #255) inner ring node makes PoR check.

In this check inner ring node should:
- [x] get storage group object (1),
- [x] for each member of storage group, inner ring node makes `object.Head` request with `main_only` flag (2),
- [x] compare cumulative object size and homomorphic hash with the values from **step 1** (3),
- [x] depending on **step 3** save storage group ID in list of _succeeded_ or _failed_ storage groups in audit result (4).

**Comment by realloc** [comment]
Related: nspcc-dev/neofs-api#110

**Comment by alexvanin** [comment]
Closed by #271 #276
