### ISSUE TITLE
TLS errors unclear response by `neofs-cli`

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#2561]
## Expected Behavior
`v0.32.0`:
```
▶ ./neofs-cli-amd64 netmap nodeinfo --generate-key -r grpcs://st1.t5.fs.neo.org:8080                             
rpc error: write request: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"
```

Immediate response, understandable error.

## Current Behavior
`v0.33.0`+:
```
▶ ./neofs-cli-amd64 netmap nodeinfo --generate-key -r grpcs://st1.t5.fs.neo.org:8080
can't create API client: can't init SDK client: open gRPC connection: gRPC dial: context deadline exceeded
```

15 seconds timeout. Error... well, could be better.

## Possible Solution
- SDK is broken?
- `go` is broken?
- `neofs-cli` is broken?
- gRPC lib is broken?
- ???

## Steps to Reproduce (for bugs)

Get the provided CLI versions from the GH release pages, use testnet endpoints, pretend to be an idiot and use a secure (`grpcs` "protocol") client for an insecure endpoint.

## Context
Extremely annoying bug while you try to find out what is wrong with your certs: https://github.com/nspcc-dev/neofs-dev-env/pull/287.

## Regression
`v0.33.0` CLI release. 

## Your Environment
Does not work locally and on GH workers (ubuntu if it means something).

**Comment by cthulhu-rider** [comment]
@carpawell were you able to verify/refute any of the hypotheses?
