### ISSUE TITLE
Node 4 can't join the network in dev env

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2565]
#2475 regression, tests are failing:
https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/708-1694198138/index.html

`EndpointInfo RPC call result differs: attr number: got 10, expect 4`

We can either temporarily disable this check or make it work.

**Comment by carpawell** [comment]
https://github.com/nspcc-dev/neofs-node/actions/runs/6150466421/job/16688482411 says it was closed in https://github.com/nspcc-dev/neofs-node/pull/2568.
