### ISSUE TITLE
Do not use spaces in JSON keys (logs)

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#2582]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I see spaces in JSON keys. To me, that is the same bad style as using spaces in filenames. You never know when it breaks some of your code. Also, that is easier to read keys without spaces in the logs.

## Describe the solution you'd like
Do not use spaces when working with `zap` library. Do [this](https://github.com/nspcc-dev/neofs-node/blob/3749ce78dc175210e364dde4db42ffc448d1e89b/pkg/morph/client/notary.go#L215), not [this](https://github.com/nspcc-dev/neofs-node/blob/3749ce78dc175210e364dde4db42ffc448d1e89b/pkg/local_object_storage/engine/control.go#L234).

## Describe alternatives you've considered
Be free with the keys.

## Additional context
https://github.com/nspcc-dev/neofs-node/pull/2444#discussion_r1326815723.

**Comment by carpawell** [comment]
@roman-khimov, @532910, @MaxGelbakhiani, @smallhive, @AliceInHunterland, any thoughts are welcome.

**Comment by cthulhu-rider** [comment]
imo any tools working with JSON must rely to JSON specification only, and since it doesn't prohibit whitespaces in object keys, the tools must be prepared to them

but at the same time i agree that we could live w/o spaces

**Comment by 532910** [comment]
I hate json in any form as a user-oriented format because it isn't, and love spaces in file names. So I'm for spaces!

**Comment by roman-khimov** [comment]
I just don't see any issue with spaces. We have spaces? OK. We don't have spaces? OK.

**Comment by carpawell** [comment]
OK, it seems that I am the only one who sees problems with spaces.
