### ISSUE TITLE
Use Cobra `MarkFlagsOneRequired` feature

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#2595]
sometimes [`Cobra`](https://github.com/spf13/cobra)-based programs need to declare several mutual exclusive flags with exactly one required. Currently, we use [`MarkFlagsMutuallyExclusive`](https://pkg.go.dev/github.com/spf13/cobra#Command.MarkFlagsMutuallyExclusive) method to mark mutex flags. But "at least one" setting should be checked manually

upcoming library [`release`](https://github.com/spf13/cobra/milestone/10) gonna provide `MarkFlagsOneRequired` method which will allow us to drop extra check

**Comment by roman-khimov** [comment]
#2754 unblocks this.
