### ISSUE TITLE
Allocation optimizations

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#2613]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when a storage node does not store objects fast. Some profiles say it allocates a lot. Because of the different things.

## Describe the solution you'd like

Do some object marshaling optimizations (the list is extendable):
1. Do not (un)marshal an object if a node reads it for replications only; just stream it as is;
2. Do not sign a message more than once during the [initial object distribution](https://github.com/nspcc-dev/neofs-node/blob/c817194269943e4ed56d85eedf33b529bb1b282e/pkg/services/object/put/distributed.go#L151-L164) (for `REP N` without a local copy, a node will sign and send the same message N times);
3. ...

## Describe alternatives you've considered
Look at profiles, get used to profiles, love profiles.

**Comment by roman-khimov** [comment]
The first is #2317. I'd say this one is for the second.

**Comment by carpawell** [comment]
@roman-khimov, did not know #2317 exists. Initially planned this issue to be a general issue with some discussion. Can be reworked/renamed.

**Comment by roman-khimov** [comment]
I think this was solved in 894c825caf64dfd795059880bf07a4e8b4034791. Not that there are no more optimizations to make, but this is not specific enough any longer.
