### ISSUE TITLE
Dictionary zstd compression

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#2630]
We use https://github.com/klauspost/compress compression library and [zstd](https://facebook.github.io/zstd/) compression algorithm. It (algorithm) supports some training/dictionary compression for small files: https://facebook.github.io/zstd/#small-data. Can possibly speed up compression for small files. Can be useful. Should be researched.

**Comment by roman-khimov** [comment]
Duplicates #2120.
