### ISSUE TITLE
Use genesis role designations for autodeploy

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2643]
NeoGo can designate roles in block 0 from 0.103.0: https://github.com/nspcc-dev/neo-go/blob/master/docs/node-configuration.md#Genesis-Configuration

Which means we can have notary (and alphabet role) enabled for IR nodes right from the beginning. That's the way we should set up our new networks, old ones don't care much, but new ones can rely on this and drop another very annoying step from the autodeploy with signature exchange via NNS.

I don't think we need old role setup code at all, while theoretically we can set up a network without it and try running a node in this setting, practically it won't happen, we will create new networks with internal CNs using this new configuration. But this needs to be controlled for internal CN config, because CN itself can be used both on old and new networks. A simple "set_roles_in_genesis" config can be used in this case (expanding to appropriate keys automatically, they're the same as validators).

**Comment by cthulhu-rider** [comment]
blocked [next](https://github.com/nspcc-dev/neo-go/milestone/69) Neo Go release. See:
* #2652
* https://github.com/nspcc-dev/neo-go/pull/3229
