### ISSUE TITLE
Drop network_settings config

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2660]
## Is your feature request related to a problem? Please describe.
We have it since #2444, but:
* it's a lot of things to configure
* autodeploy is deactivated without it
* this configuration is only relevant for initial deployments, it's not used in any other way
* network configuration can't be changed by changing it
* it differs from neofs-adm syntax (https://github.com/nspcc-dev/neofs-node/blob/bbfbd9bce59a09c99e61d6b937ae18fcab847e4b/cmd/neofs-adm/internal/modules/config/config.go#L31)

## Describe the solution you'd like
Deploy contracts with default parameters (bringing us closer to https://github.com/nspcc-dev/neofs-contract/issues/372), let neofs-adm handle changes. Activate autodeploy/autoupdate with a specific `contract_autodeploy` flag.

## Describe alternatives you've considered
Leaving it in a release doesn't seem to be viable.

**Comment by cthulhu-rider** [comment]
`contracts_autodeploy` sounds insufficient: for example, tokens are transferred and roles are assigned if necessary. I'd call `sidechain_autodeploy`. Or we may use `morph` section (where `consensus` resides for example) and just `autodeploy`

**Comment by roman-khimov** [comment]
`fschain_autodeploy`. No sides, no morphs, please.
