### ISSUE TITLE
IR can't properly start with outdated epoch

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2680]
## Expected Behavior
IR always working fine.

## Current Behavior
Consider a network with outdated epoch (like "- Epoch is not updated for 1247 block(s) (normal duration: 240)"), old contracts and new shiny IR with contract autoupdate functionality. It starts, detects outdated contracts and tries to push an update tx which fails:
```
neofs-ir[865]: 2023-12-15T19:17:31.879Z        error        deploy/contracts.go:312        failed to send Notary request updating the contract, will try again later        {"contract": "NeoFS Notary Proxy", "domain": "proxy.neofs", "error": "failed to submit notary request: Expired transaction (-510) - transaction has expired: ValidUntilBlock = 2744419, current height = 2745421"}
```
Our VUB setting logic is epoch-based, so the contract can't be updated. But a new epoch can't be arranged because IR is waiting for contract updates. It's a deadlock.

## Possible Solution
Either we need to tick an epoch, or we need to adjust VUB setting.

## Steps to Reproduce (for bugs)
Stop 0.38.1 IR (leave CN) for a long time, update it to 0.39.0, can happen easily because of the chain sync (which takes time).

**Comment by cthulhu-rider** [comment]
it makes no sense to base VUBs on NeoFS epochs:
* epochs could stuck
* chain height is much more accessible and predictable

so, we may set VUB to `100(N+1) > current height >= 100N`
