### ISSUE TITLE
node/object: Optimize placement ops

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#2692]
_* inspired by https://github.com/nspcc-dev/neofs-node/issues/2686#issuecomment-1863370406_

## Is your feature request related to a problem? Please describe.
in some scenarios `ObjectService` server of the storage node calculates list of container nodes again and again for fixed network map (epoch stays unchanged for some period of time) and container (e.g. data load into single container)

this is easy observable from profiles attached to #2686. Millions of objects may be uploaded into single container within one epoch, and node will do https://pkg.go.dev/github.com/nspcc-dev/neofs-sdk-go/netmap#NetMap.ContainerNodes millions of times

## Describe the solution you'd like
cache the results. Cache should have limited size ofc (it's enough to start with fixed size LRU cache). For some placements like "the latest epoch" the cache must be invalidated on epoch switch

## Describe alternatives you've considered
no other ideas for now

**Comment by roman-khimov** [comment]
Pretty easy to do, yes.

**Comment by roman-khimov** [comment]
Duplicates #1988.
