### ISSUE TITLE
Container removal broke a lot of tests

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2709]
## Expected Behavior
Like before #2638 merge: https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1168-1703535611/index.html

## Current Behavior
https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1169-1703535726/index.html

## Possible Solution
Fix it.

## Steps to Reproduce (for bugs)
Run testcases.

## Regression
Yeah, #2638.

**Comment by cthulhu-rider** [comment]
what prevents us from tracking tests' breakage before merging?

**Comment by roman-khimov** [comment]
It was ~ok: https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1165-1703509070/index.html

**Comment by cthulhu-rider** [comment]
> It was ~ok: https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1165-1703509070/index.html

i see, we run only a bit more than 10% of all tests on PRs. Is there a plan to autorun all tests?

**Comment by roman-khimov** [comment]
These are just different modes, PR and master. 2h+ test suite for every push into PR is too expensive.

**Comment by cthulhu-rider** [comment]
can PR tests be run when the changes are ready-to-merge (manually, or on approvals) somehow? all tests take some time anyway, so it's better to catch failures in the PR, not within merge-detect-PR-merge-detect-PR... flow

**Comment by roman-khimov** [comment]
Only if https://github.com/nspcc-dev/neofs-node/actions/workflows/run-tests.yml is to be parameterized for that (it autodetects PR/master currently). But you'll forget to run it, don't worry.

**Comment by cthulhu-rider** [comment]
>  forget to run it, don't worry

forget to run - another problem, dont run at all - current

**Comment by cthulhu-rider** [comment]
same OKness again https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1176-1703703416/index.html
