### ISSUE TITLE
Filter API extensions

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2730]
Epic tracking currently relevant filter API extensions.

* https://github.com/nspcc-dev/neofs-api/issues/265
* https://github.com/nspcc-dev/neofs-api/issues/256
* https://github.com/nspcc-dev/neofs-api/issues/255
* https://github.com/nspcc-dev/neofs-sdk-go/pull/550

SDK/node issues to be added.

**Comment by cthulhu-rider** [comment]
@roman-khimov anything else we wanna support about this, or we happy?

**Comment by roman-khimov** [comment]
I think we're done at this stage. We can of course do way more things with attributes, but this set is finished.
