### ISSUE TITLE
grpc: Simplify server TLS config

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#2755]
* blocked by #2754

gRPC release [v1.60.0](https://github.com/grpc/grpc-go/releases/tag/v1.60.0) contains server-side TLS [fix](https://github.com/grpc/grpc-go/issues/6758)

storage node's code [touches](https://github.com/nspcc-dev/neofs-node/blob/0f81d2029a391680bc06ea8f65a0da335181cf6a/cmd/neofs-node/grpc.go#L32-L51) this API. At a glance it is very similar, but the list of cipher suites is not completely equivalent

need to revise and try to rely on gRPC defaults which follow RFC 7540 since then

**Comment by roman-khimov** [comment]
What? We're maintaining a list of cipher suites internally? I want to kill it ASAP.
