### ISSUE TITLE
Storage node is excluded from network map during tests

### ISSUE THREAD

**Issue by evgeniiz321** [nspcc-dev/neofs-node#2770]
See details and logs in this comment - https://github.com/nspcc-dev/neofs-testcases/pull/734#issuecomment-1984106332

Can be reproduced in github on a full tests run, usually node disappears after test - test_expired_object_should_be_deleted_after_locks_are_expired, but that doesn't seem to be related. After that node sporadically appears and disappears again.

**Comment by carpawell** [comment]
Closed in #2777.
