### ISSUE TITLE
Zero per-epoch cost for non-empty container

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2819]
## Expected Behavior
Each epoch should cost at least 1 picoGAS if container is not empty.

## Current Behavior
There are containers that have data in them (estimate should not be zero), but pay nothing. It's not all of them like that, some do pay, but there are known ones.

## Context
Mainnet.

## Your Environment
* Version used: 0.40.1

**Comment by roman-khimov** [comment]
https://github.com/nspcc-dev/neofs-node/issues/2820#issuecomment-2075082179 didn't help.

**Comment by carpawell** [comment]
Damn, fixed in #2830.
