### ISSUE TITLE
Ersatz-chain for object headers

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2864]
_For a test purpose_ create a branch that works this way:
 * all object headers SN accepts (new objects) are put into transactions that just do PUSHDATA and leave it on the stack, this needs to be done _after_ appropriate replication
 * these transactions are pushed into the main chain we have
 * SN waits for transaction acceptance and says OK to user
 * default chain block time shifted to 100ms, epoch is 10000 blocks

This needs to be a branch that can de deployed for performance testing easily (no additional configurations). We may then add some contract for additional processing, but let's do this test quickly.

**Comment by carpawell** [comment]
@roman-khimov

> just do PUSHDATA and leave it on the stack

Just syntenic here, right? No real storing.

> default chain block time shifted to 100ms, epoch is 10000 blocks

Out of this issue's scope? Or what did you mean?

**Comment by roman-khimov** [comment]
> Just syntenic here, right? No real storing.

At this stage yes.

> Out of this issue's scope

Embedded CN has some defaults, I don't remember if we have this configured explicitly during NeoFS setup for performance testing (@EESergey?).

**Comment by carpawell** [comment]
> Embedded CN has some defaults

You said "main chain" that was not witnessed as an embedded CN (have i missed something?) so it was where i was confused. Is it required to be changed too? How many services should be started in total?

**Comment by roman-khimov** [comment]
"main" was not meant to be mainnet (vs FS chain), it was meant to be main FS chain (vs per-container chains!)

**Comment by carpawell** [comment]
@roman-khimov, how about this: https://github.com/nspcc-dev/neofs-node/tree/feat/test-meta-on-chain?

**Comment by roman-khimov** [comment]
Looks like it for the first test.

**Comment by carpawell** [comment]
@roman-khimov, can we close it? Should here be a summary?

**Comment by roman-khimov** [comment]
Yes. Yes.

**Comment by carpawell** [comment]
We have tested it on 4 machines (100ms blocks, epoch duration was 10000 blocks, every _initial_ PUT put object's header on the stack, sent it via RPC, and waited for inclusion to some block). Container policy was `REP 3` (mostly, some additional tests were also made on REP 1).

After all, at a 1-byte load, no chain bottleneck was found. Its block time was quite stable (p(95)=120ms), block processing took almost always less than 1ms, and average object PUT took ~100ms (the same as without additional chain modification).

Required 106.3+ neo-go release with some fixes. No changes were necessary on the node side for this type of testing.

@EESergey
