### ISSUE TITLE
Add object status command to the control service

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#2886]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when external test code cannot see what is happening in the storage engine. We need to add some possibility to check object's status according to current node state.

## Describe the solution you'd like
Add `neofs-cli control object-status` (or add `object` subcommand and also move `drop-objects` command here). It should return object's status. Optionally it can return some debug information about its internal info: shard ID that stores it, storage type that stores it, writecache status, etc.

## Describe alternatives you've considered
Not so many. None of them to be precise.

## Additional context
We need some tooling to check node behavior: https://github.com/nspcc-dev/neofs-testcases/pull/822#pullrequestreview-2142949647.

**Comment by cthulhu-rider** [comment]
* see also #2853, maybe it will be possible to implement both
