### ISSUE TITLE
Store time at which metabase was resynced

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#2887]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when we miss some details about meta when it [behaves badly](https://github.com/nspcc-dev/neofs-node/issues/2844).

## Describe the solution you'd like
Store some timestamp that indicates the last metabase resynchronization. Do not think absolute time is a good idea, so epoch can be a better option.

## Describe alternatives you've considered
(:

## Additional context
Every time we debug metabase is an "additional context".

**Comment by roman-khimov** [comment]
We'll change metabase format a bit in the next version, so we better do this at the same time.
