### ISSUE TITLE
`meta.DB.Open(readOnly)` does not move metabase in RO mode

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#2889]
## Expected Behavior
Metabase is asked to open bbolt in RO, and I expect the internal state to be RO too.

## Current Behavior
Bbolt is opened in RO, however, metabase accepts write operations and returns bbolt's error.

## Possible Solution
`Open` sets mode to RO (additional test for it is also good).

## Context
Firstly found in https://github.com/nspcc-dev/neofs-node/pull/2884.

**Comment by roman-khimov** [comment]
> Bbolt is opened in RO

Which is technically sufficient.

> metabase accepts write operations and returns bbolt's error.

You want it to return some other specific error?

**Comment by carpawell** [comment]
> Which is technically sufficient.

Sure, that is how it should be done, but there are also some additional things in our code related to RO/RW states that currently behave strangely.

> You want it to return some other specific error?

We have everything for it: [a code](https://github.com/nspcc-dev/neofs-node/blob/a0447ce5697c723fe9abe4f2542471078a33220e/pkg/local_object_storage/shard/mode/mode.go#L11), [internal state](https://github.com/nspcc-dev/neofs-node/blob/a0447ce5697c723fe9abe4f2542471078a33220e/pkg/local_object_storage/metabase/db.go#L38), and [check](https://github.com/nspcc-dev/neofs-node/blob/a0447ce5697c723fe9abe4f2542471078a33220e/pkg/local_object_storage/metabase/inhume.go#L98-L105) in every method but opening in RO mode make it useless.
