### ISSUE TITLE
Validate session token on the node

### ISSUE THREAD

**Issue by smallhive** [nspcc-dev/neofs-node#2898]
## Is your feature request related to a problem? Please describe.
Using session tokens with bucket operations like create/delete bucket is an async story. In the SDK we use Waiter to get the successful result of such operations.

Despite this, if the session token is expired, the waiter will wait until timeout, because the request was correct, and correctly signed.

## Describe the solution you'd like
It would be perfect if the node were requested immediately if the session token expired, was wrong by any parameter, etc.
Or even in any other requests, when node can check something

## Additional context
Receiving any error on any request to the node can make the developer's life easier

**Comment by carpawell** [comment]
Can you give an example operation that does no work? TBH, I thought that expiration is checked immediately.

**Comment by smallhive** [comment]
ContainerPut. If the token has expired there is no immediate response to the client with error
