### ISSUE TITLE
Health status: HEALTH_STATUS_UNDEFINED

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#2923]
while v43 process looks healthy (reports metrics, no errors in the log) health status is always `HEALTH_STATUS_UNDEFINED`

```
# neofs-cli control healthcheck -c /etc/neofs/ir/control.yml --ir
Health status: HEALTH_STATUS_UNDEFINED
```

this breaks ansible and update process

**Comment by roman-khimov** [comment]
It takes some time to update contracts.

**Comment by roman-khimov** [comment]
Some blocks.

**Comment by roman-khimov** [comment]
We can add an additional status and expose it via Prometheus.
