### ISSUE TITLE
Example - Host a website on Neo FS 

### ISSUE THREAD

**Issue by lock9** [nspcc-dev/neofs-node#293]
Hi.
Is it possible to host a website on NeoFS? How? 
My reference:
https://snapshot.page/#/sushi/proposal/Qmajj2U9nM9fCJ6Yo5t3m2E2SdecREF9URW4noUs2Z7wwS

Bonus question: Is Neo FS Neo 3 ready? 

Thanks
(Not sure where to post this)

**Comment by realloc** [comment]
Hi! Sorry for late answer, there were Christmas and New Year holidays in Russia =)

Yes, it is possible to host static website on NeoFS via HTTP protocol gateway. You can try it with neofs-dev-env right now.
 Public NeoFS testnet launch in Neo3-preview4 testnet is planned for the end of January, after that the one may use free public http gate (with reasonable bandwidth limitations).

Current NeoFS "Yeouido" release is Neo3-preview4 compatible =)

**Comment by lock9** [comment]
I will try that! Thanks!
