### ISSUE TITLE
Add split object meta into signed data

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2935]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when we can't easily untangle big object status based on meta info.

## Describe the solution you'd like
Extend data added in #2928 to contain split id associated things. The goal is to have enough data to avoid network communication when processing big objects.

**Comment by carpawell** [comment]
> The goal is to have enough data to avoid network communication when processing big objects.

@roman-khimov, what is the exact use case here? The simplest thing is to try to put every part in the message. But the message could be really big then. Also, we now know that we [try to minimize our](https://github.com/nspcc-dev/neofs-contract/pull/448#discussion_r1860489419) our lists in the meta info. It may have first object ID, link object ID, or both but that is not "avoid network communication".
