### ISSUE TITLE
HEAD operation leads to RPC requests

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2972]
## Expected Behavior
HEAD operation returning result using local data only.

## Current Behavior
```
read object header from NeoFS: status: code = 1024 message = connection to the RPC node has been lost"
```
Why some RPC request?

## Possible Solution
Change something.

## Steps to Reproduce (for bugs)
Not known.

## Context
Mainnet.

## Regression
Doesn't look like.

## Your Environment
* Version used: 0.43.0
* Operating System and version (`uname -a`): Debian stable

**Comment by carpawell** [comment]
> Why some RPC request?

But why not? How do you plan to check ACL rules in a general case?

**Comment by roman-khimov** [comment]
In general yes, it can't be avoided. But in many cases we can avoid additional ones. We know requests from other container nodes immediately, for example and they can't be affected by RPC.
