### ISSUE TITLE
Add method to change netmap state of the storage node in Control API

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#315]
Storage node for now has two network map states: online and offline. Offline nodes are removed from network map and from list of candidates in netmap contract. To switch the state node invokes `UpdateState` method of netmap contract. 

Control API should provide method similar to `UpdateState` as proxy between node and netmap contract. However node won't be shut down after it's state was updated to offline. It still can work as a relay node. 

Adopt these changes in neofs-cli.

## Important side-notes
1. Maybe `online` and `offline` naming is a bit confusing, because offline node can process requests. However for the network, node becomes invisible as it tracked as a client by storage nodes at direct p2p communication.
2. You can't update state after going `offline`. Control API should invoke `AddPeer` in case of `offline->online` change.
3. Maybe we should drop state update at graceful shutdown (#298) if neofs-cli is able to turn node offline via Control API

//сс: @realloc @cthulhu-rider

**Comment by realloc** [comment]
If node state can be controlled via `neofs-cli`, then we don't need to force `offline` state at node shutdown. This also should prevent flapping on node restarts.
