### ISSUE TITLE
Query language for search filters in CLI

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#362]
With adoption of https://github.com/nspcc-dev/neofs-api/issues/119 and https://github.com/nspcc-dev/neofs-api/issues/120, CLI should be able to produce search queries with these match filters. Right now CLI syntax supports `x=y` queries for `STRING_EQUAL` match filter. It is kinda bad to use `!` symbol for negation, since it is reserved in bash. And it is not the answer for unary `NOT_PRESENT` match filter.

For key \ value pairs of ASCII symbols CLI can support this grammar
```
<expr> := <binary_exp> | <unary_exp>

<binary_exp> := <string> <binary_op> <string>
<unary_exp> := <string> <unary_op> 

<binary_op> := EQ | NE
<unary_op> := NOPRESENT

<string> := "<ASCII char>+"
```

E.g. `--filter 'A EQ B' --filter 'C NOPRESENT'`

For complex rules or key\value pairs with UTF-8 symbols support JSON encoding of filter structure `--filter filters.json`

**Comment by fyrchik** [comment]
I think something like `opname:parameters` or `opname:p1[:p2[:p3 ...]]` is convenient and expressive enough. Short form for both operation and whole parameter is possible too.
Full: `equal:x=y` (`equal:x:y` support varargs in a straightforward manner), short `x=y`
Full: `not:x=y`, short `x^y`.
Full: `not_present:x` ( `missing:x` or something else).

Though this will require some breaking changes if same option is reused (`equal:x` is interpreted as string now).

**Comment by cthulhu-rider** [comment]
Be careful when using delimiters: most (or all?) human-readable delimiters are valid characters for both key and value.

**Comment by alexvanin** [comment]
> I think something like `opname:parameters` or `opname:p1[:p2[:p3 ...]]` is convenient and expressive enough

While it is quite expressive and convenient, we've decided that average CLI user is not ready for s-expressions, so we stick with simpler option.
