### ISSUE TITLE
Set price and locode attributes from config instead of raw attributes

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#376]
**Is your feature request related to a problem? Please describe.**
Storage node may have a bunch of announced attributes. They are specified in configuration in a raw format (without strict validation), e.g. `NEOFS_NODE_ATTRIBUTE_0=/StorageType:SSD`. However there are at least two mandatory attributes that have to be defined: 
- `Price`
-  `UN-LOCODE`

There is also a `Capacity` but we are not working with this attribute right now. 
The only way to define them -- do it in raw format: `NEOFS_NODE_ATTRIBUTE_1=/UN-LOCODE:RU HTA`. 

**Describe the solution you'd like**
I propose to configure `Price` and `UN-LOCODE` attributes explicitly:
```
NEOFS_NODE_ATTRIBUTE_PRICE=100
NEOFS_NODE_ATTRIBUTE_LOCODE=RU HTA
```

This values should expand list of raw configured attributes. Consider using **raw** attributes in case of overlapping.

**Comment by realloc** [comment]
I suggest to leave only attribute settings. This makes configuration more intuitive and leaves no room for possible conflicts between the same parameters set in attributes and in regular configuration options.
