### ISSUE TITLE
Support any number of alphabet contracts 

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#392]
Right now inner ring has support of seven alphabet contracts in the network. However seven is not strict requirement, amount of alphabet contracts should be matched with amount of consensus nodes. For example there is a single consensus node in [neofs-dev-env](https://github.com/nspcc-dev/neofs-dev-env).

## Problem areas
There are three places where we have hadrcoded for this:

(1) [Contract list](https://github.com/nspcc-dev/neofs-node/blob/38727c2930fc07f859ed2656a1d2639a1d9bd2a3/pkg/innerring/innerring.go#L93) in inner ring server
```go
	contracts struct {
		...

		alphabet [alphabetContractsN]util.Uint160 // in morph
	}
```

(2) [Parser](https://github.com/nspcc-dev/neofs-node/blob/38727c2930fc07f859ed2656a1d2639a1d9bd2a3/pkg/innerring/innerring.go#L632) of contract list from config
```go
func parseAlphabetContracts(cfg *viper.Viper) (res [7]util.Uint160, err error) {
	// list of glagolic script letters that represent alphabet contracts
	glagolic := []string{"az", "buky", "vedi", "glagoli", "dobro", "jest", "zhivete"}

	for i, letter := range glagolic {
		contractStr := cfg.GetString("contracts.alphabet." + letter)

		res[i], err = util.Uint160DecodeStringLE(contractStr)
		if err != nil {
			return res, errors.Wrapf(err, "ir: can't read alphabet %s contract", letter)
		}
	}

	return res, nil
}
```

(3) [Constant](https://github.com/nspcc-dev/neofs-node/blob/38727c2930fc07f859ed2656a1d2639a1d9bd2a3/pkg/innerring/innerring.go#L109) in inner ring server and its [usage](https://github.com/nspcc-dev/neofs-node/blob/38727c2930fc07f859ed2656a1d2639a1d9bd2a3/pkg/innerring/state.go#L40)
```go
func (s *Server) voteForSidechainValidator(validators []keys.PublicKey) error {
	index := s.Index()
	if index < 0 || index >= alphabetContractsN {
		s.log.Info("ignore validator vote: node not in alphabet range")

		return nil
	}
	...
}
```

(4) [Alphabet processor](https://github.com/nspcc-dev/neofs-node/blob/38727c2930fc07f859ed2656a1d2639a1d9bd2a3/pkg/innerring/processors/alphabet/processor.go#L22) 
Even though alphabet processor code uses `len(alphabetContracts)`, it's declared as an array, not a slice.
```go
	Processor struct {
		...
		alphabetContracts [7]util.Uint160
		...
	}
```

## To Do
At this issue we have to:
- [ ] come up with a way to configure any number of alphabet contracts, but probably still support their names (because glagolitic script is cool), 
- [ ] replace `[7]util.Uint160` arrays with `[]util.Uint160`
- [ ] replace `alphabetContractsN` const with `len(server.contracts.alphabet)`

## Future changes
Later (probably with new governance model) this might be tweaked a bit once again, e.g. list and amount of alphabet contracts could fetched from the network (as network parameter?)

**Comment by alexvanin** [comment]
1. As for configuring alphabet contracts, I think we can hardcode whole glagolitic alphabet and iterate over it until there are empty script hashes. 

2. Another options is to drop glagolitic alphabet suffixes and iterate over numbers `NEOFS_IR_CONTRACTS_ALPHABET_1`, `NEOFS_IR_CONTRACTS_ALPHABET_2` until there are empty script hashes.

3. Another options is to set it as a generic list of string values. We do that for `NEOFS_IR_MORPH_VALIDATORS` (list of committee voting):
```
NEOFS_IR_CONTRACTS_ALPHABET=c22ec393723c72aaaec1ce4c1a83a8480de09092,c7a46472340642207268e38dcf7ff3873debc34b,...
```

4. Another option to explicitly define amount of alphabet contracts `NEOFS_IR_CONTRACTS_ALPHABET_AMOUNT=3` and use it together with (1) or (2).

Thoughts @realloc @cthulhu-rider ?

**Comment by realloc** [comment]
I suggest to use (4) with (1)
