### ISSUE TITLE
Metabase graveyard should not have tombstone-to-tombstone records

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#395]
## Expected Behavior
Metabase graveyard should not have records with key corresponding to tombstone address. 
## Current Behavior
Metabase does not control types of graveyard addresses and potential tombstone-to-tombstone records.
## Possible Solution

- Before recording `address1: address2` to graveyard during `Inhume` operation, make sure the `address1` is not tombstone.
- While recording `address1: address2` to graveyard remove all records with `address2` values.

## Your Environment

* Version used: **v0.15.0**

**Comment by alexvanin** [comment]
> Before recording address1: address2 to graveyard during Inhume operation, make sure the address1 is not tombstone.

I think it can be done in one `<CID>_TS` bucket lookup, so it should work fine.

**Comment by alexvanin** [comment]
If we fix this, isn't example (not the repairer itself, it is useful to have one) from https://github.com/nspcc-dev/neofs-node/issues/394 become obsolete?
