### ISSUE TITLE
Support morph chain workflow

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#396]
There is an option to deploy NeoFS contract in sidechain. In this case inner ring application does not need two listener components. We should support mode with single listener when all contracts deployed in single chain.

**Comment by cthulhu-rider** [comment]
@alexvanin what about `Client`?

**Comment by alexvanin** [comment]
> @alexvanin what about `Client`?

Forgot about it. For sure we don't need two clients with single chain.
