### ISSUE TITLE
Make UN-LOCODE attribute optional

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#397]
According to https://github.com/nspcc-dev/neofs-api/discussions/130#discussioncomment-381211 `UN-LOCODE` attribute is not mandatory for storage nodes. If there is one, then it is parsed into `Region`, `Country`, etc. If there is no such attributes, then do nothing.

**Comment by cthulhu-rider** [comment]
Do we need to do smth if `UN-LOCODE` attribute is missing, but some of [`Continent`, `Country`, etc.] are present?

**Comment by alexvanin** [comment]
As @realloc said that "the node should not be denied entering network because of some node attribute not set", I think it should work both ways. The node should not be denied entering network because some attributes are present.

The tricky case when both `UN-LOCODE` and [`Continent`, `Country`, etc.] are present. In this case we prioritize `UN-LOCODE` values (I think it is already done this way).

**Comment by realloc** [comment]
If the node provides some attributes, they must be valid or not conflicting. If there is LOCODE attribute, it must be valid. If there are other geographical attributes that can be derived from LOCODE, they must be logically valid and be set in the same format. If those conditions are not met, the node must be denied entering the network.

For now there can be two ways:
1. Don't allow any LOCODE derivable attributes without LOCODE attribute set
2. If LOCODE is not set, check derivable attributes for correctness

The second one seems to be a more solid choice.

**Comment by cthulhu-rider** [comment]
> If the node provides some attributes, they must be valid or not conflicting. If there is LOCODE attribute, it must be valid. If there are other geographical attributes that can be derived from LOCODE, they must be logically valid and be set in the same format. If those conditions are not met, the node must be denied entering the network.
> 
> For now there can be two ways:
> 
> 1. Don't allow any LOCODE derivable attributes without LOCODE attribute set
> 2. If LOCODE is not set, check derivable attributes for correctness
> 
> The second one seems to be a more solid choice.

@realloc in 2. you mean that we try to find the entry in NeoFS LOCODE database that fully matches to sub-set of location attributes? And if we do, we does not modify attributes, otherwise we deny the entry to the network map?

**Comment by realloc** [comment]
Yes, like that.
I see it as a series of logical checks to make sure that location attributes are set in the exactly same format and wording.
