### ISSUE TITLE
Session token is not written to the object

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#41]
## Expected Behavior
In case of trusted object placement within opened session between user and trusted node session token must be written to object body.

## Current Behavior
Session token is not written to the objects during trusted placement.

## Possible Solution

1. write session token to object in format transformer;

1. take session token from the request and write to object before transformations.

## Your Environment

* `jindo` branch

**Comment by alexvanin** [comment]
Fixed in #56: https://github.com/nspcc-dev/neofs-node/pull/56/commits/7854663fd3ff1fd8c0f85f26c89343f2e02f3176
