### ISSUE TITLE
Resend some API messages instead of creating new one

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#431]
Before https://github.com/nspcc-dev/neofs-api-go/pull/263 neofs client could not reuse pre-created messages to send it to remote peers. That's the reason storage node has some behavior flaws: 
- search requests are recreated each time node wants to resend it,
- produced split `object.Put` requests signed by session key and lack node key signature.

Now node can prepare message, sign or re-sign it and then send it with `client.Raw()` invocation. To do so object service should provide some way to get original request message for object service method handlers.

**Comment by cthulhu-rider** [comment]
I came up with the following possible approaches to solving this problem.
## 1. Embed raw request to signatures of the existing methods
The body of each method comes to form a specific request [message](https://github.com/nspcc-dev/neofs-api-go/blob/2fcb6d961335a7fd9676b3dad5e6f56bdf00f43a/rpc/message/message.go#L12)(s). We can add the ability to pass message through method's args (dedicated context, parameter or option).

The questions arising in this approach: 
#### a. How to support cross-versioning?
Possible solution: define version-dependent message provider
```
type VersionedMessage interface {
    ToVersion(*pkg.Version) (message.Message, error)
}
```
#### b. Where to get call method info?
Possible solution 1: extend message interface with method
```
    CallMethodInfo() common.CallMethodInfo
```
Possible solution 2: create methods like [this](https://github.com/nspcc-dev/neofs-api-go/blob/2fcb6d961335a7fd9676b3dad5e6f56bdf00f43a/v2/rpc/container.go#L22) which can accept  [message.Message](https://github.com/nspcc-dev/neofs-api-go/blob/2fcb6d961335a7fd9676b3dad5e6f56bdf00f43a/rpc/message/message.go#L12) and make exisiting methods to call new ones.
## 2. Completely raw communication
Current `Client`'s methods are left untouched. Calling context should work with `Client.Raw()` instance (using `client.SendUnary`, etc.) and work within the single version during single call (until raw client ).

The question `1.b.`  also arises in this approach.

**Comment by alexvanin** [comment]
Done in #499
