### ISSUE TITLE
Submit sidechain notification handlers to worker pool(s)

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#440]
**Description**
Handlers of sidechain notification events are expected to be very lightweight since event `Listener` call them synchronously one-by-one. If some list of instructions isn't lightweight (e.g. contains network ops), it is expected that handler will generate go-routine for asynchronous execution of these instructions.

Right now node application registers all notification handlers regardless of their "weight".
 
**Possible solution**

1. have a notification worker pool (global or per-contract);
2. make `registerNotificationHandlers` func to set closures over worker pool: 
```
hi.SetHandler(func(ev event.Event) {
	err := c.cfgMorph.workerPool.Submit(h) // or corresponding contract pool
	if err != nil {
		c.log.Warn("could not submit notification handler to worker pool",
			zap.String("error", err.Error()),
		)
	}
})
```

**Alternatives**

We can split handlers into sync and async groups, and use worker pool for async handlers only.

**Additional context**
It would be useful to share the mechanism between applications, for example add function to event pkg:
```
func AsyncHandler(pool util.WorkerPool, handler Handler, log *logger.Logger) Handler {
	return func(ev Event) {
		err := pool.Submit(func() {
			handler(ev)
		})
		if err != nil {
			log.Warn("could not submit notification handler to worker pool",
				zap.String("error", err.Error()),
			)
		}
	}
}
```

**Comment by alexvanin** [comment]
I like the idea of having pool of routines in `Listener` component. I think it can be considered as having global worker pool. 

Any complex logic with sync and async events can be implemented outside of the listener, e.g. as inner ring processors maintain their own pools and rules on handling such events.

**Comment by cthulhu-rider** [comment]
> I like the idea of having pool of routines in `Listener` component. I think it can be considered as having global worker pool.
> 
> Any complex logic with sync and async events can be implemented outside of the listener, e.g. as inner ring processors maintain their own pools and rules on handling such events.

Do you mean to add worker pool to `Listener` implementation? All proposed solutions do not imply affecting the internal structure of the `Listener` (the 2nd paragraph of your statement implies the same).

**Comment by alexvanin** [comment]
> All proposed solutions do not imply affecting the internal structure of the Listener

Then I got you wrong, but still I have nothing against of worker pools in handlers. Storage node definitely will benefit from that.
