### ISSUE TITLE
Container's object listing ignored split objects

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-node#45]
When searching for objects from particular container, split objects are ignored, because they do not exist as a single object.

## Expected Behavior
Container listing returned all objects: regular objects, split objects, split object parts.

## Current Behavior
Split object are ignored

## Possible Solution
On each node serving search request for container listing, additionally list all OIDs from Parent fields and merge those lists in response.

**Comment by alexvanin** [comment]
Fixed in https://github.com/nspcc-dev/neofs-node/pull/54
