### ISSUE TITLE
Storage node with enabled rebootstrap will eventually go online after setting it to offline via CLI

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#470]
With re-bootstrap option `bootstrap.periodic.enabled: true` storage node will send bootstrap message and go to network map after it was set to offline mode via CLI command: `./bin/neofs-cli -c config.yaml control set-status --status offline` (node sends `netmap.UpdateState(offline)` tx.

It seems like a bug, however re-bootsrap option is designed to send bootstrap messages regarding of it network map state every N epochs. What do you think?

**Comment by realloc** [comment]
If the state change command is sent fom `neofs-cli`, then the node has to remember this state until next restart or another state change via `neofs-cli` call. In offline state the node behaves as if it is offline and doesn't perform active actions, like re-bootstrap.
