### ISSUE TITLE
Dynamic/constant `alpha` parameter of eigenTrust algorithm

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#497]
Decide if `alpha` of the eigentrust algorithm parameter should be dynamic(via global config) or constant.

In the first realization it was considered that `alpha`  is going to be read from env. But this may lead to incorrect algorithm work due to a potential situation when different nodes use a different implementation of the eigentrust algorithm.

Now it is constant but hidden behind Interface that can be changed to reading from global config.

**Comment by alexvanin** [comment]
We've decided to keep this value constant but for the possible performance and accuracy tweaks store it in global config. If `alpha` parameter will be changed one day, then all storage node will use updated value synchronously.
