### ISSUE TITLE
Define the rules for using `Debug` log msgs

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#513]
There are some `Debug` messages(e.g. [there](https://github.com/nspcc-dev/neofs-node/blob/master/pkg/services/container/announcement/load/controller/calls.go#L66), [there](https://github.com/nspcc-dev/neofs-node/blob/master/pkg/services/reputation/local/controller/calls.go#L104) and so on) that seem quite critical and not only for debug usage(in my terminology "debug" is for messages like "start doing smth", "finish doing smth", "trying to send smth in the net").

If a developer tries to start the app and test it locally, he can find it a little bit difficult NOT in debug mode(cause there are no error messages, that were sent as a debug msg) and IN debug mode too(cause there are too many debug messages that are from other parts of code and that are not "error messages" at all).

**Comment by alexvanin** [comment]
As we discussed, each case is individual. The rule of thumb is: if error message can help user (not the developer) to identify **and** fix the issue (e.g. bad connection with a specific remote node may reconsider firewall rules), then it should be printed at error or warn level. If developer sees debug error that satisfies this rule, then log level can be changed. However everything needs a balance, we don't want to overwhelm logs too much, therefore there won't be strict rules about this anytime soon.

I will close this issue next week if there won't be additional discussions.
