### ISSUE TITLE
Add vmagent to storage-testnet image

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#551]
Docker image for self-hosted storage nodes in testnet should have vmagent configured to collect and transfer node metrics to a public dashboard.

**Comment by aprasolova** [comment]
@alexvanin
1. Should running vmagent be configurable for user? Might user turn it off?
2. Should pushed metrics be configurable for user or for us?
3. Should pushed metrics contain bind address of node?

**Comment by alexvanin** [comment]
> 1. Should running vmagent be configurable for user? Might user turn it off?

It should not be manually configurable. Advanced user can rebuilt image without telemetry from scratch. For everyone else, we don't want want to have external option for turning it off in testnet. For mainnet it should be reconsidered.

> 2. Should pushed metrics be configurable for user or for us?

The set of metrics should be pre-configured in the image by developers.

> 3. Should pushed metrics contain bind address of node?

I don't mind while it is exposed by pprof. Not sure if it is, though.
