### ISSUE TITLE
Provide additional context to `fatalOnError`

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#552]
Idea of `fatalOnError` function is to avoid `if err != nil` pattern in storage node initialization because it happens a lot and it always leads to panic. It worked well with `pkg/errors` because wrap function could provide additional context to the error and also returned nil if there was no error. However it won't work with `fmt.Errorf` so we got error checking pattern back (saw that in #549 and #542). 

I propose to provide context details directly to `fatalOnError`.

```go
func fatalOnErr(err error, details string) {
	if err != nil {
		log.Fatal(fmt.Errorf("%s: %w", details, err))
	}
}
```

**Comment by cthulhu-rider** [comment]
Good idea.

In order not to touch on the places where the detail of the error is not required and not to force them to pass `""`, I suggest to create a separate function `func fatalOnErrDetailed(err error, details string)`
