### ISSUE TITLE
Multiaddress validation by IR

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#557]
In #549 there was a chain of actions: TLS was added => changed the argument of client cache's `Get()` method from string to `network.Address` to define what exactly connection should be created => changed client cache's key's format from "HostString"  to multiaddr  => "/dns4/s01.neofs.devenv/tcp/8080/tls" and "/tls/dns4/s01.neofs.devenv/tcp/8080" are logically the same keys(and both are correct for `go-multiaddr` library), but there will be two clients created for them

Therefore, it should be discussed, if IR should validate(to be in the same format) multiaddress on bootstrap or not.

**Comment by alexvanin** [comment]
Another option is to define canonical multiaddress field order and convert all address to it locally in client cache.

**Comment by fyrchik** [comment]
I think only first of the options is correct and we can (should) disallow another. I haven't found an explicit description in a doc, but
`Encapsulate` method appends wrapped protocol to the end https://github.com/multiformats/go-multiaddr/blob/master/multiaddr.go#L140
Here is example in doc https://github.com/multiformats/go-multiaddr/blob/master/doc.go#L29

Second example (`/tls/dns4/...`) means something like "ip4 over TLS" which is certainly not what we want. It is not difficult to validate address on a client especially when most of the parsing will be hidden in a SDK.
