### ISSUE TITLE
capricious neofs-cli keys 

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-node#571]
## Expected Behavior
1. I'm able to print neofs-cli version two ways: `neofs-cli version` and `neofs-cli --version`
2. I'm able to print help topic for netmap two ways: `neofs-cli netmap help` and `neofs-cli netmap --help`

## Current Behavior
1.
```
$ neofs-cli version
Version: v0.20.0 
Build: 2021-05-21T10:04:40+00:00 
Debug: false

$ neofs-cli --version
Error: unknown flag: --version
Usage:
  neofs-cli [command]
...
and long help message
```
2.
```
$ neofs-cli netmap help
netmap called

$ neofs-cli netmap --help
Operations with Network Map

Usage:
  neofs-cli netmap [flags]
  neofs-cli netmap [command]
...
and relevant help message
```
## Possible Solution
Implement expected behavior.

## Regression
No

## Your Environment
```
$ neofs-cli version
Version: v0.20.0 
Build: 2021-05-21T10:04:40+00:00 
Debug: false
```

**Comment by cthulhu-rider** [comment]
`help` and `--help` are native Cobra lib features on which our CLI is based on. `version` is a dedicated command to print the CLI version.

We decided with @alexvanin to replace `version` command with `--version` flag. @aprasolova, what do you think?

**Comment by aprasolova** [comment]
I believe it might be more convinient for our future users if neofs-cli would support both `version/help` and `--version/--help` keys. `neo-go` and `docker` CLIs supports `help`/`--help`, for instance.
