### ISSUE TITLE
Incorporate grpcweb proxy wrapper into neofs-node

### ISSUE THREAD

**Issue by hal0x2328** [nspcc-dev/neofs-node#618]
**Is your feature request related to a problem? Please describe.**
Web-based dApps may wish to create new NeoFS containers, check account balances or modify EACLs; however gRPC isn't natively supported by browsers. There is the grpc-web protocol that can act as a bridge, but it relies on a proxy server to translate the requests from grpc-web to gRPC.

**Describe the solution you'd like**
There is a proxy server available called grpcweb that can be deployed as a code wrapper around the gRPC server object:
https://github.com/improbable-eng/grpc-web/tree/master/go/grpcweb

**Describe alternatives you've considered**
I implemented a grpc-web interface to NeoFS using the envoy proxy combined with neofs-http-gw, but it would be a superior solution if the proxy capability was natively implemented in neofs-node so anyone could stand up a dApp and immediately begin connecting to NeoFS via public nodes instead of having to worry about maintaining their own services.

It was also mentioned that creating a twirp interface may be an alternative, but I think grpcweb may be an easier drop-in solution requiring very little in the way of code changes.

**Comment by amlwwalker** [comment]
this sounds fantastic. Would make life a tonne easier not to have to host this ourselves and would make devving apps that can use NeoFS sweeet.

**Comment by roman-khimov** [comment]
Does https://github.com/nspcc-dev/neofs-rest-gw/ solve your problem?

**Comment by roman-khimov** [comment]
REST gw is likely to be sufficient for this.
