### ISSUE TITLE
Try native JSON-RPC server for accounting service in neofs-node

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#620]
We can try to implement native JSON-RPC services in neofs-node while they do not have stream methods. Only object service has RPCs with streams, so we can do that for all other services.

**Comment by cthulhu-rider** [comment]
This can be an alternative to the proposal https://github.com/nspcc-dev/neofs-node/issues/618.

**Comment by alexvanin** [comment]
We've tried JSON-RPC server but it requires more use-cases to implement it properly in node.

**Comment by alexvanin** [comment]
JSON-RPC expected to be friendly for web-developer. But it can't be friendly in terms of NeoFS, due to complex signature scheme, that requires stable marshaling, etc. So the better approach is to implement separate RESTful API Gateway with auth protocol similar to `auth-box` in [S3 Gateway](https://github.com/nspcc-dev/neofs-s3-gw). Storage node will keep using binary gRPC streams.
