### ISSUE TITLE
Move morph/client wrappers to SDK

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#621]
3rd party apps might want to access contract data without type conversions. Consider moving wrappers into SDK and find missing contract methods.

**Comment by fyrchik** [comment]
Related #625 .

**Comment by cthulhu-rider** [comment]
Ready to do after NeoFS SDK Go release v1.0.

Maybe postpone by purging non-notary envs. 

We need to consider compatibility flow.

**Comment by roman-khimov** [comment]
Shouldn't be needed, contracts can have autogenerated RPC bindings and they're sufficient for the purpose.
