### ISSUE TITLE
Reduce amount of wrappers in `pkg/morph/client`

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#625]
Currently we have hierarchy of clients talking to our contracts:
1. Raw neo-go client.
2. Static client talking to a specific contract (see also nspcc-dev/neo-go#1967)
3. Low-level wrapper in `pkg/morph/client/balance`
4. High-level wrapper in `pkg/morph/client/balance/wrapper`.

Do we need to separate 3 and 4? I suggest removing one of the levels as it feels artificial and unnecessary verbose.
With additional struct it is also easier to forget to add argument on a higher level. With direct invocation compiler ensures completeness for us.

As @cthulhu-rider noticed, we can have `func Method(args MethogArgs)` in contract and use the struct imported from `neofs-contract` repo directly (this will need client support from neo-go though).

I am OK with any variant as long as it reduces the amount of code needed to write and maintain while increasing readability.

**Comment by cthulhu-rider** [comment]
I don't think we need to drop l3 since it controls:
* method names;
* arg order;
* arg types.

Why structures? The original thought was to try to completely mirror the arguments from the contracts code. Additional advantage of readable support for a potentially large number of call arguments.

**Comment by alexvanin** [comment]
> As @cthulhu-rider noticed, we can have func Method(args MethogArgs) in contract and use the struct imported from neofs-contract repo directly (this will need client support from neo-go though).

While it sounds good, I am not sure we are going in this direction anytime soon. Also I talked with @realloc about it the other day and he wasn't happy about sending `[]interface{}` params and type casting in contract runtime.

**Comment by cthulhu-rider** [comment]
> > As @cthulhu-rider noticed, we can have func Method(args MethogArgs) in contract and use the struct imported from neofs-contract repo directly (this will need client support from neo-go though).
> 
> While it sounds good, I am not sure we are going in this direction anytime soon. Also I talked with @realloc about it the other day and he wasn't happy about sending `[]interface{}` params and type casting in contract runtime.

Type casting is performed anyway in contract. `StructT` type is supported, it would be nice to use it. Btw we return structures which are splitted up into `[]interface{}`. When dealing with arguments, the overhead seems to be negligible, isn't it @fyrchik @roman-khimov?

**Comment by alexvanin** [comment]
> StructT type is supported, it would be nice to use it. 

Maybe we are thinking about different things there, let me clarify. 

If `func Method(args MethodArgs)` will be compiled in neo-go the same way as `func Method(arg1 int, arg2 []byte)` then you won't be able to expand `MethodArgs` struct with additional fields.

If `func Method(args MethodArgs)` will be compiled in neo-go as `func Method(data interface{})` then you will be able to expand such struct but contract byte code should do something like [that](https://github.com/nspcc-dev/neofs-contract/blob/14382d701c7d04c7846aba8c41c5e1e58dfe86b0/neofs/neofs_contract.go#L85) implicitly. That's what we discussed with @realloc. 

Probably this should be discussed in different issue in neofs-contract repo.

**Comment by cthulhu-rider** [comment]
> If func Method(args MethodArgs) will be compiled
I meant only this approach.

**Comment by alexvanin** [comment]
Speaking of client structure complexity.

> Currently we have hierarchy of clients talking to our contracts:
>
> - Raw neo-go client.
> - Static client talking to a specific contract (see also nspcc-dev/neo-go#1967)
> - Low-level wrapper in pkg/morph/client/balance
> - High-level wrapper in pkg/morph/client/balance/wrapper.
>
> Do we need to separate 3 and 4? I suggest removing one of the levels as it feels artificial and unnecessary verbose.

I am not sure about merging (3) and (4), however it is a valid concern why we need both if nobody use (3) except (4). I think some apps might want to use (3) without NeoFS related structure parsing for some reason, hard to say.

But I would love to remove some code from (3). For example constructors of (3) provide options to set up contract method names. Don't see how it can be useful in our case. There can't be two versions of `NeoFS` contract in same NeoFS network: it is either the same contract with additional method or completely new contract.

**Comment by alexvanin** [comment]
(3) can be done with code generation, that will be awesome.

**Comment by fyrchik** [comment]
I think if (3) can be useful for external code, we can should move it to SDK (and merge it there with 4, maybe). We don't really gain anything by having (3). At some point contracts are expected to have mostly fixed interface, so no changes are needed. If we need (3) level client because (4) doesn't suit our needs, this is a bad wrapper, we better change (4). And in case of parameter/method addition, we need to write code in 2 places instead of one.

Some examples:
1. `neofsid` some switching is done https://github.com/nspcc-dev/neofs-node/blob/master/pkg/morph/client/neofsid/wrapper/keys.go#L76, and the same is done at the callsite https://github.com/nspcc-dev/neofs-node/blob/master/pkg/innerring/processors/neofs/process_bind.go#L106 . These are 2 separate methods, we can (should) split it on the 3+4-th level.
2. Same for `subnet`: there are switches both in the methods and on the call-site (though, we don't have 2-level wrappers here).
