### ISSUE TITLE
Try pebble for writecache

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#632]
Compared to #619 with its own quirks, adopting pebble for write-cache is more straightforward and can potentially lead to more substantial improvements.

**Comment by alexvanin** [comment]
We have benchmark results from #619, but it is interesting to see if the difference between bbolt.DB and pebble is going to be the same on a high performance server hardware. First describe a benchmark for the write cache operations (I suppose we can simplify test from [bench_test.go](https://github.com/fyrchik/neofs-node/blob/meta-pebble/pkg/local_object_storage/metabase/bench_test.go) for write cache `Put` and `Get` operations). If pebble still 1.5x \ 2.0x faster on these operations, then make a PR that replaces write cache k:v storage implementation.

/cc @fyrchik @cthulhu-rider @carpawell @realloc @anatoly-bogatyrev

**Comment by alexvanin** [comment]
Based on benchmarks, pebble does not provide much improvement.
