### ISSUE TITLE
Node accepts containers with non unique attributes

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#634]
The same as #633 but for container attributes.

```
$ ./bin/neofs-cli -r [...] --binary-key [...] container create --policy [...] --attributes Timestamp=0

$ ./bin/neofs-cli -r [...] --binary-key [...] container get --cid [...]
...
attribute: Timestamp=0 (1970-01-01 03:00:00 +0300 MSK)
attribute: Timestamp=1624378604 (2021-06-22 19:16:44 +0300 MSK)
```

**Comment by cthulhu-rider** [comment]
Any container attribute should have a non-empty value according to [spec](https://github.com/nspcc-dev/neofs-api/blob/030c59ccbae04d9717c40e6562f8a6de2f729d4e/container/types.proto#L34). I suggest to add this check too.
