### ISSUE TITLE
neofs-cli create container blocking

### ISSUE THREAD

**Issue by bettybao1209** [nspcc-dev/neofs-node#636]
Hi, I use the dev-env to launch the priv chain and input `neofs-cli container create --rpc-endpoint s01.neofs.devenv:8080 --address NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM --wallet wallets/wallet.json --basic-acl public-read-write --await  --policy "REP 1 SELECT 1 FROM *"`, while it always throws the `timeout: container has not been persisted on sidechain`. 

So could you tell me what I  can do to find the cause?

**Comment by alexvanin** [comment]
I think you missed deposit step at neofs-dev-env startup. Check NeoFS balance with this command. It should be non zero.

```
$ neofs-cli accounting balance  --rpc-endpoint s01.neofs.devenv:8080 --address NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM --wallet wallets/wallet.json
```

To make a deposit just run `make prepare.ir` command (you need `expect` utility installed on your machine to avoid manual wallet password input). It will invoke `./bin/deposit.sh` script that makes GAS transfer to NeoFS smart contract address in main chain.

By the way, in next release neofs-cli will immediately throw error if your balance is not sufficient to create container, see https://github.com/nspcc-dev/neofs-node/issues/591.

**Comment by bettybao1209** [comment]
> ```
> neofs-cli accounting balance  --rpc-endpoint s01.neofs.devenv:8080 --address NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM --wallet wallets/wallet.json
> ```

Yes, exactly. Thanks for your help!!
