### ISSUE TITLE
Bump go version up to latest stable

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#638]
go1.14 version is out of go support cycle. Also new versions of `spf13` packages use features from later go releases. 

Before release we need to to:
- [ ] update go up to go1.16 or other latest stable version,
- [ ] update `spf13` packages.

Related to #600

**Comment by roman-khimov** [comment]
> update go up to go1.16

Maybe 1.15 would be enough for now (I'm not sure what spf13 needs)?

**Comment by alexvanin** [comment]
> Maybe 1.15 would be enough for now (I'm not sure what spf13 needs)?

spf13 packages use `io/fs` from go1.16
Also go1.17 scheduled to august, I think, and this release will end go1.15 support. I would like to target go1.16 /  go1.17.
