### ISSUE TITLE
Always proceed public keys during intra-container communication

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#645]
NeoFS does not prohibit the announcement of the same network addresses to different nodes.

In current implementation storage node works with network addresses only during the work (placement traversing). Examples:

- to check if node info is a descriptor of the local node we compare addresses from the network map;
- we don't check if response was signed with the expected key.

TODO:

1. define remote node info interface similar to the one from reputation or container service;
2. make placement traverser to return list of these interfaces instead of `[]network.Address`;
3. extend the interface with method to get public key;
4. replace `network.IsLocalAddress` function with `IsLocalServer(ServerInfo)` and use it where it is needed;
5. add the ability to receive response pubic key from the client (API Go library or SDK);
6. check keys from response signatures in Object service.

**Comment by alexvanin** [comment]
Done #797. However as it noted in PR, we can do better job if we will be able to check if remote node uses expected public key. Blocked by https://github.com/nspcc-dev/neofs-api-go/issues/337
