### ISSUE TITLE
data file are executable

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#646]
```
rei # l /srv/neofs/data0/blobovnicza/0/0 
-rwxr-x--- 1 neofs-storage neofs-storage 10489856 Jun 24 04:40 /srv/neofs/data0/blobovnicza/0/0
```

**Comment by cthulhu-rider** [comment]
Node reads permissions from [config](https://github.com/nspcc-dev/neofs-node/blob/1f461baf0b74d41b5c9fd6d3c75ce32a512544c1/config/example/node.yaml#L91). Check yours.

**Comment by alexvanin** [comment]
The same permissions config value is being used both for dirs and database files. 

```go
	err := os.MkdirAll(path.Dir(b.path), b.perm)
	if err == nil {
		b.boltDB, err = bbolt.Open(b.path, b.perm, b.boltOptions)
	}
```

Dirs are required to be executable, but files are not. Maybe we should create dirs with some default permission e.g. `755` and use config values only for database files.

**Comment by 532910** [comment]
https://github.com/nspcc-dev/neofs-node/blob/1f461baf0b74d41b5c9fd6d3c75ce32a512544c1/config/example/node.yaml#L123

`667`?

**Comment by cthulhu-rider** [comment]
These are examples of values, everyone chooses their own

**Comment by 532910** [comment]
https://github.com/nspcc-dev/neofs-node/blob/1f461baf0b74d41b5c9fd6d3c75ce32a512544c1/config/example/node.yaml#L119

These are odd examples...

**Comment by cthulhu-rider** [comment]
the goal is to convey the format, not teach you to choose

**Comment by cthulhu-rider** [comment]
> Dirs are required to be executable, but files are not. Maybe we should create dirs with some default permission e.g. `755` and use config value only for database files.

We can do `+x` for dirs from the configured perm.

**Comment by realloc** [comment]
It turned out people just take the sample/default config. Let's change the default permissions to 660 for data files and 770 for the directories, the way it wouldn't need user actions.
