### ISSUE TITLE
Cli docker image not building

### ISSUE THREAD

**Issue by Abhimanyu121** [nspcc-dev/neofs-node#649]
## Expected Behavior
`make image-cli` should build docker image for cli. 

## Current Behavior

Currently tried it on three environments MacOS with m1 chip and intel chip, windows machine with intel chip (X64) and it fails to build in all three machines with no error in the logs at all.

## Steps to Reproduce (for bugs)

1. In neofs-node dir run `make image-cli`

## Context

We are working on having a docker based solution to push files, and neofs-cli isn't working in docker due to arch type differences.
## Your Environment

* Version used: v0.21.0-1-g4988477-dirty 
* Operating System and version (`uname -a`): ```Darwin USERNAME 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64```

**Comment by alexvanin** [comment]
Unfortunately, we do not support the macOS platform. More platforms will be supported after '1.0' release. Additionally, we use [homomorphic encryption](https://github.com/nspcc-dev/tzhash) that requires AVX/AVXv2 instructions, that are not supported on the ARM platform. 

However, you should be able to build NeoFS CLI binary and image on Intel based Mac. Or you can get image from [DockerHub](https://hub.docker.com/layers/nspccdev/neofs-cli/0.21.1/images/sha256-04eecc0b194ff5dd8544a20b9ad2ca7514151c2bc533c599183e0e9096f4b2f9?context=repo).

**Comment by Abhimanyu121** [comment]
Thanks a lot for reply, will use it from docker hub.
