### ISSUE TITLE
"Unsupported version" error using neofs-cli v0.21.1 with recent dev-env

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#655]
## Setup
dev-env 74717177c088b0833161a4a0bb2067412a69a18c, neofs-cli v0.21.1:
```
$ ~/bin/neofs-cli container get -r 192.168.130.73:8080 --cid 5LSSzNunga4kN2Q5yAPnACaSN3HjzkVVgbVGT3hXeLNE -k KxDgvEKzgSBPPfuVfw67oPQBSjidEiqTHURKSDL1R7yGaGYAeYnr
Error: rpc error: unsupported version 2.8
```

## Expected Behavior
Container data returned successfully.

**Comment by roman-khimov** [comment]
It works with neofs-cli v0.22.0.

**Comment by alexvanin** [comment]
This is expected when latest neofs-cli v0.22.0 (with API v2.8) connects to neofs-node v0.21.1 (with API v2.7). Client does not support auto negotiation yet, but it definitely will. 

However it is not expected for neofs-cli v0.21.1 to throw such error when connecting to neofs-node v0.21.1 or later.

**Comment by cthulhu-rider** [comment]
The problem is caused by the fact that API client returns an error if container version is newer than corresponding API Go library version. It is checked [here](https://github.com/nspcc-dev/neofs-api-go/blob/59179bed92020b59bb022664146ead87931de2b7/pkg/client/container.go#L176).
