### ISSUE TITLE
[0.22.0 BUG]: CLI returns 0 exit-code on non-existent object get

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-node#657]
## Expected Behavior
Non-zero exit-code.

## Current Behavior
```
$ neofs-cli --rpc-endpoint <rpc> --wif <wif> object get --cid <cid> --oid <oid> --file file
can't get object: reading the response failed: rpc error: code = Unknown desc = object already removed
$ echo $?
0
```

## Steps to Reproduce (for bugs)
1. put an object
2. delete that object
3. get tombstone
4. get the object via neofs-cli

## Regression
Yes. In previous version CLI returned non-zero ec.

## Your Environment
```
$ neofs-cli --version
Version: v0.22.0 
Build: 2021-06-30T16:38:25+00:00 
Debug: false
```
```
$ uname -a
Linux username 4.15.0-144-generic #148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by alexvanin** [comment]
Seems like side effect of replacing `RunE` to `Run` in https://github.com/nspcc-dev/neofs-node/pull/624
Explicit `os.Exit(1)` should help, I think.

**Comment by cthulhu-rider** [comment]
Does this case need to check failure of CLI process or the particular error?

**Comment by alexvanin** [comment]
> failure of CLI process or the particular error?

I think in both cases we can throw non zero exit code, however it might be different depending on the reason: internal error or RPC response error.

**Comment by cthulhu-rider** [comment]
> might be different depending on the reason

Exactly. Therefore, it makes no sense to return a non-zero exit code yet. The application does not specify this, and therefore should not be expected.

**Comment by alexvanin** [comment]
> Therefore, it makes no sense to return a non-zero exit code yet. 

Can't agree with that. It may not specify exact codes, but it is ready to return some non zero values. This is enough for the scripts, including test cases.

**Comment by cthulhu-rider** [comment]
Then we need to either identify errors that generate a non-zero return code, or cancel it. All errors concerning NeoFS IMOshould not generate a non-zero code.This will allow you to separate the incorrect use of the command by the test and the runtime of the storage error.

**Comment by alexvanin** [comment]
>  All errors concerning NeoFS IMO should not generate a non-zero code.

Take `ssh` client and pass incorrect password when connecting to remote server -- you'll get non zero error code. 

As soon as it called *NeoFS* CLI why shouldn't it return non zero exit code when *NeoFS itself* returned error?

**Comment by cthulhu-rider** [comment]
You have a set of errors `{E0, E1, ...}` that NeoFS can return for particular command. How do you know if CLI has received a specific error `Ex`?

**Comment by realloc** [comment]
> You have a set of errors {E0, E1, ...} that NeoFS can return for particular command. How do you know if CLI has received a specific error Ex?

For now, it's enough to distinguish an error from success. Detailed mapping of NeoFS errors to exit codes could be done later, together with NeoFS Errors refactoring.

**Comment by cthulhu-rider** [comment]
If I understand the logic of the test correctly, return 
```
can't get object: reading the response failed: rpc error: code = Unknown desc = object already removed
```
is considered a passing, everything else is a failure (even OK). If so, exit codes is not a solution, because Get after Delete can return anything.

**Comment by realloc** [comment]
The test itself is a separate matter. `neofs-cli` is expected to return non-zero exit code in case of any error.
