### ISSUE TITLE
Add "Upgrading" section in changelog

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-node#673]
Some releases have breaking changes in configuration and data formats preventing simple upgrade via binary change. For such occasions we need to add the upgrading instructions in `CHANGELOG.md`.

When new release comes out, operators and automation (ansible roles, dev-env, etc) developers would see the instructions and implement the required migration procedures in their code.

**Comment by alexvanin** [comment]
Closed in #719
