### ISSUE TITLE
Refactor logging component

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#696]
We use `zap`  logger as a basis of app logger. Currently [Logger](https://github.com/nspcc-dev/neofs-node/blob/aed76f6b5a5f65fb78313cf6289134bde08c189f/pkg/util/logger/logger.go#L15) type is an alias, but this does not seem desirable from the side of the application code. I propose to provide a specific API built on the built-in-Go and NeoFS-specific types, and close `zap` in the implementation. This will make it possible to complete the use of a wide range of `zap` features to those that are required specifically for our applications. Also, when changing `zap` API or switching to a new fundamental basis, the application code will not be affected.

The similar approach was performed for the config types based on `viper`.

**Comment by cthulhu-rider** [comment]
Also:
1. underline meaningful log messages (object lifetime, etc.)
2. per-component log (in config)

**Comment by roman-khimov** [comment]
Another proposal: drop `pkg/util/logger`, use `zap` and be done with it.

**Comment by cthulhu-rider** [comment]
lets use `zap` everywhere until other needs
