### ISSUE TITLE
Manifest for nspccdev/neofs-aio:latest not found

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-node#702]
Couldn't pull image `nspccdev/neofs-aio` with `latest` tag. But using `0.22.3` tag works correctly.

## Expected Behavior
Image pulled successfully

## Current Behavior
Couldn't pull image. Error:
```
Using default tag: latest
Error response from daemon: manifest for nspccdev/neofs-aio:latest not found: manifest unknown: manifest unknown
```

## Steps to Reproduce

1. Run `docker pull nspccdev/neofs-aio`

**Comment by alexvanin** [comment]
Without image uploading in CI pipeline, we have to set latest tag manually and we don't, for some reason. I think it is good time to finally fix up pipeline.

**Comment by aprasolova** [comment]
Now `latest` tag for `nspccdev/neofs-aio` exists and is updated on release.
