### ISSUE TITLE
Failed to set-eacl if its size exceeds 1024 bytes

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-node#731]
If size of eacl table exceeds 1024 bytes it cannot be set. Such table, for example, may contain:
* 7 allowed records for specific public key
* 7 allowed records for specific public key with filter by `FileName` attribute
* 5 (other than `put` and `delete`) allowed records for  `others` role with filter by `FileName` attribute
* 7 denied records for `others` role

## Expected Behavior
EACL has been persisted on sidechain

## Current Behavior
```
rpc error: transport error: rpc error: code = Unknown desc = could not handle request: could not handle request: could not execute SetEACL request: could not invoke method (setEACL): chain/client: contract execution finished with state FAULT; exception: error encountered at instruction 3045 (SYSCALL): failed to invoke syscall 1634664853: notification size shouldn't exceed 1024
```

## Steps to Reproduce

1. Try to set-eacl that exceeds 1024 bytes: ` ./bin/neofs-cli -w wallet.json --address NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM  -r s01.neofs.devenv:8080 --cid 6Dk9CTMhRY5M8UXfay3KauKgK9i9khWCRDo8hwDT9Bhv container set-eacl --table eacl.json --await
`

## Your Environment
* Version used: v0.22.1
* Operating System and version (`uname -a`): Linux 5.8.0-59-generic # 66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alexvanin** [comment]
Notification size limit is [hardcoded](https://github.com/nspcc-dev/neo-go/blob/ab480f78c56f7791bffe14f051c14d2656d4d19e/pkg/core/interop/runtime/engine.go#L17) and not configurable, so we need to find a workaround. 

In notary enabled environment we can throw away all notifications and make Alphabet nodes listen for transactions to sign directly from notary payload pool. 

In notary disabled environment we can:
- accept 1KiB limitation for all containers, extended ACLs, Storage Node attributes, etc.
- store notification data in the contract for short amount of blocks and notify the storage key where the data is available (not the thing I would like to do before N3 mainnet release, but we can try it),
- ...

/cc @realloc @roman-khimov

**Comment by roman-khimov** [comment]
> In notary disabled environment ... accept 1KiB limitation for all containers

We have better environments that can work correctly.

**Comment by realloc** [comment]
In the disabled environment, providing an inclusive temporary contract storage space could be costly, hard to predict the fee and making eACL changes even slower. We could support partial eACL updates, but that's not an option until `neofs-next`.

I'd suggest accepting the 1KiB limitation until the notary is back to NeoFS Sidechain.
