### ISSUE TITLE
Smart contract script hash auto negotiation

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#736]
NeoFS Adm utility deployes side chain network with NNS contract that stores data about all side chain smart contract script hashes. Inner Ring app and Storage app can use data from NNS contract. However we should not change the configuration. If smart contracts are present in local config, then use values from there.

**Comment by fyrchik** [comment]
The code to retrieve hashes from NNS can be found in `cmd/neofs-adm`. Currently they are stored as hex-encoded little-endian string (this is the form we use in every CLI). It can be more convenient to store them as raw bytes if we use them mostly for automatic processing vs user-level display.

**Comment by alexvanin** [comment]
What about main chain contract addresses? They are not presented in NNS contract. I would like to keep them in Inner Ring node config.

**Comment by realloc** [comment]
Mainnet contract hash is well-known for N3 mainnet/testnet and may be kept as a config option. But we should keep in mind that it still needs update for devenv.
