### ISSUE TITLE
neofs-adm can't use relative path to the alphabet keys dir

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#739]
neofs-adm can't use relative path to the alphabet keys dir:
For alphabet-wallets:~/alphabet/
```
Error: can't create wallet: open ~/alphabet/az.json: no such file or directory
```

**Comment by alexvanin** [comment]
@realloc @anatoly-bogatyrev @fyrchik 

Admin tool can be invoked by worker / job with it's own OS account and home path, therefore it might lead to an error. Is it okay to support `~` to avoid these cases? It works perfectly fine if `alphabet-wallets` specified as a flag (bash resolves it automatically).

**Comment by realloc** [comment]
At current development stage it's ok to expect correct absolute path in the config.
