### ISSUE TITLE
Storage nodes do not switch between RPC endpoints

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#746]
Storage node config provides a list of endpoints for Neo RPC client. Node creates client with random RPC endpoint. Unfortunately it did not switch to other endpoint even if RPC node is dead. 

In case of Listener component, it produces internal error and application is restarted with new connection. 
In case of the client, Storage node will just return errors on incoming NeoFS API requests that trigger side chain invocations.

While it is hard to maintain listener component switch, we can easily define multiclient component for RPC node (the same way we have multiclient of NeoFS API client).

Additionally, we can adopt this mulitclient in Inner Ring node application.

/cc @carpawell

**Comment by cthulhu-rider** [comment]
Several approaches can be considered:
- forget about the node on failure 4ever;
- give it the lowest priority for the next time;
- do exactly like API multi-client: every time iterate over fixed list of endpoints.

@alexvanin

**Comment by alexvanin** [comment]
> do exactly like API multi-client: every time iterate over fixed list of endpoints.

:+1:

**Comment by alexvanin** [comment]
Closed in #769
