### ISSUE TITLE
Use CustomGroup scope for side chain contract invocations

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#749]
Global scope is not that good even if it is used in side chain. Update neofs-contract repo with custom group scope support in manifest and specify this group scope in side chain invocation of morph client.

**Comment by roman-khimov** [comment]
See `contract manifest add-group` command in neo-go to sign manifests (nspcc-dev/neo-go#2100).

**Comment by alexvanin** [comment]
See main chain scope fix in #751

**Comment by fyrchik** [comment]
It can be easier with https://github.com/nspcc-dev/neo-go/pull/2251

**Comment by alexvanin** [comment]
Closed in https://github.com/nspcc-dev/neofs-node/pull/1124
