### ISSUE TITLE
Fix bootstrap process without side chain notifications

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#750]
Alphabet nodes approve fixed version of `netmap.AddPeer` invocation from storage nodes: they add location attributes based on `UN-LOCODE` attribute. This contradicts the way Alphabet nodes will approve notary invocations after https://github.com/nspcc-dev/neofs-node/issues/519. We should figure out the fix for this.

Possible solutions
1. keep using notifications for `AddPeer` invocations with 1KiB limit of NodeInfo structure,
2. do not sign notary transaction from Storage node and sign new transactions built manually by Alphabet nodes,
3. parse `UN-LOCODE` attribute on Storage node (requires valid copy of LOCODE database on every storage node or store it side chain).

**Comment by carpawell** [comment]
I suggest using `2.`  way. payment for such approach is fallback TXs with `RET` opcode only from SN in sidechain

It is ok when SN use `netmap.AddPeer` only on its startup, but a little bit worse when it uses it for healthcheck. so, maybe, healthcheck process should be improved

`2.` approach implemented in #815
