### ISSUE TITLE
Support metabase reinitalization 

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#789]
Storage data or metabase might be corrupted because of external reasons. In this case Storage node may provide inconsistent responses of object service request, e.g. successful HEAD, but failed GET.  We should have an option to reinitialize and sync metabases within available shards. 

Proposal: 
- define metabase restore function in the shard, that goes over all available blobovnizcas, fstrees, writecache files, reads all the objects and translate them over metabase data,
- define storage engine function, that goes through selected shards and calls metabase restore function.

To initialize metabase restore we can:
1. support restore operation in the Storage node start if it is configured this way,
2. add separate `neofs-node` command to restore the data,
3. add separate `neofs-cli` command to restore the data.

I would go with (1), but I am a bit worried that it might took too long for the storage node to startup. Maybe startup and restore should be different independent operations.

Questions:
- Should we rebuild database from the start or try to sync available data? As for me, syncing and merging seems quite complex than empty start, so I prefer complete rebuild.
- How object parsing order going to affect the resulting metabase?

Related to https://github.com/nspcc-dev/neofs-node/issues/394 but implying repairer is a runtime worker and metabase reinitialization is done before Store node start.

**Comment by cthulhu-rider** [comment]
I'd implement two useful operations:

1. Metabase `Reset` method: cleans up all static buckets. Executed on `Init` step in `restore` config flag is set.
2. `Shard`'s internal function `restore`: iterates over `BlobStor`'s objects and saves them in `Metabase`.
