### ISSUE TITLE
Add object module to neofs-cli

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-node#79]
`neofs-cli` needs to have a module for object operations.

Minimal required feature set:

- Get object by address
  Header is ignored by default. Using an option it should be printed or saved to file in JSON or protobuf format
  Payload should be streamed to `stdout` or saved to file
  There should be an option to dump the requested object 'as-is' in binary form
  Use GetRange request if `--range` option is set

- Head object by address
  `--main` and `raw` options must be supported 
  Header should be printed or saved in JSON or protobuf format to file

- Get object's payload hash
  Return full payload hash if `--range` option is not set

- Delete object by address

- Search
  Search query should be accepted in binary, JSON or SQL-like format

**Comment by alexvanin** [comment]
It is mostly implemented in https://github.com/nspcc-dev/neofs-node/pull/96
Minor fixes of object related commands should be issued in new issues.
