### ISSUE TITLE
Do not listen events from unhealthy Neo RPC nodes

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#795]
Consider Neo RPC node unhealthy if it is restoring the chain. In this case Inner Ring and Storage nodes may receive events from the past to handle. Since Inner Ring application mostly stateless, it can't filter out such events. The simplest way to fix it --- wait for the chain to be restored or choose other Neo RPC endpoint.

## How to check Neo RPC node state
Unfortunately, there is no RPC to check node status. Possible solution is to monitor block height for short period of time and classify the state based on the speed of height change, e.g.: healthy if there are less than 2 new blocks per second. 

/cc @AnnaShaleva @roman-khimov @fyrchik

**Comment by roman-khimov** [comment]
I can throw in some ideas from neo-go side, but they all have some side-effects:
 * don't run RPC service before the node is in sync
   Which changes the behavior radically and having RPC exposed while the node is synchronizing actually has its use cases too (what if you want to get those stale notifications? what if you need to quickly check something for account that hasn't been touched for a month, but don't want to wait a month of blocks to be processed?)
 * expose synchronization status (that is kept internally already!) to the outside world via RPC (`getversion` extension or a separate API)
   Not hard to do, but still that would be the status as this single node sees it, technically it can still be wrong (although not likely to).

On the other hand, on neofs-node side you can:
 * check for height change speed
   Which is very unreliable, blocks are different, node state is different, block processing time is unpredictable in general.
 * check for the latest block timestamp
   Of course your clocks won't be in perfect sync with any of CNs.
 * keep some state like the last block processed
   That's some local state with all of its problems and it only allows to judge if the node is past some known point in time or not, whether it's up to date with the rest of the network is still unknown.

That I guess is all the possibilities we have.

**Comment by AnnaShaleva** [comment]
I like the last idea of keeping the latest state (block processed) on the neofs node. It shouldn't be resource-demanding and it looks easy to implement.

There's one more possible thing that can be done on neofs-node side: usually, there are several known RPC nodes in the network, so you can iterate over them, ask for the chain's height, choose the best (or the median) height `H` as the etalon one and bind to this RPC node for further cooperation. This idea is similar to one that is used to initiate the state exchange process, so maybe it will help somehow. See [`tryInitStateSync` method](https://github.com/nspcc-dev/neo-go/pull/2019/files#diff-20dff1d8d865de2cfb9b17512e135b82a529bd2330845f756ee35d0a23befe29R1240) for example.

**Comment by alexvanin** [comment]
> keep some state like the last block processed

I agree with this solution, however I see an issue there: `state.NotificationEvent` nor `NotaryRequestEvent` do not store associated block number. It means that I can't figure out whether this event should be processed or dropped. I can't rely on the block subscription because there is no strict order of these events.

**Comment by AnnaShaleva** [comment]
If you store the last block processed, then you can ignore events from stale RPC nodes by comparing RPC node height and local last block number.

When it comes to `NotaryRequestEvent`, you can always pay attention to:
1. `type` field of the event. If it's `removed` then the request isn't valid anymore (it was removed from the pool).
2. `ValidUntilBlock` field of main (or fallback) transaction. If it is lower than the current chain's height, then the request is invalid.
3. `NotValidBefore` attribute value of the fallback transaction. If it is lower than the current chain's height, then the alphabet node shouldn't respond to this request, because main transaction is outdated and it's not possible anymore to collect signatures for that request.

When it comes to `state.NotificationEvent` you may use `state.AppExecResult` instead and filter it manually by notification event name or scripthash. `state.AppExecResult` contains container scripthash, so you can easily get associated block number from it.

**Comment by alexvanin** [comment]
> If you store the last block processed, then you can ignore events from stale RPC nodes by comparing RPC node height and local last block number.

This should work, thanks!

**Comment by alexvanin** [comment]
> expose synchronization status

Are there any issues on that or should we create new one? 

By the way, what can go wrong if neo-go node will not accept subscription requests until node is in a synchronized state? As far as I understand, subscription API is a sort of an extension, so it should not affect whole RPC service. This would mostly solve the issue for us as well. 

/cc @roman-khimov

**Comment by alexvanin** [comment]
> Not yet, the question is --- do we really need it?

It seems for me a bit easier and more flexible than implementing special `StartRPCAfterSync` switch. For example, monitor apps can reuse this API as well to set healthy status of the node on each restart. Maybe I am wrong with my estimations, though.
