### ISSUE TITLE
Storage Node changes EACL version

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#804]
EACL tables that are set via `neofs-cli` with SDK version that differs from SN's(or CLI's, did not check what exactly affects it) could not be validated(`neofs-cli` says `timeout: EACL has not been persisted on sidechain`) since returned EACL has SN's(or CLI's) version, not the original one. Despite the error message, EACL is set though.

**Comment by alexvanin** [comment]
So in the end, who's changing table version: CLI or Storage node?

**Comment by carpawell** [comment]
@alexvanin, it is CLI(via api call from the `neofs-api-go` library) who changes the version and I guess it is done [here](https://github.com/nspcc-dev/neofs-api-go/blob/v1.29.0/pkg/client/container.go#L359)

do not know was it supposed to be always set as `neofs-api-go`'s version or not

**Comment by alexvanin** [comment]
As soon as we update neofs-sdk-go, it should be closed, right?
