### ISSUE TITLE
Add netmap module to neofs-cli

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-node#81]
Basic set of  operations to implement:

- Dump netmap for latest Epoch or for Epoch number set in option, if available.
  Should be saved to file or printed to `stdout` in different formats including JSON and protobuf.

- Get latest Epoch number
  
- Request [LocalNodeInfo](https://github.com/nspcc-dev/neofs-api/blob/master/netmap/service.proto#L19) from particular host

- Filter netmap from file or `stdin` using set of filters. List of filters can
  be set in binary, JSON or SQL-like format

**Comment by alexvanin** [comment]
Netmap service is not implemented on storage node yet, so this issue is blocked for a while. There are `accounting`, `object`, `session` and `container` services at neofs storage node at the moment.

**Comment by alexvanin** [comment]
Two out of four proposed operation make sense now.

1. :x: There is no RPC to fetch netmap from node.
2. :heavy_check_mark: CLI will get epoch number from response meta header of any request (e.g. `netmap.LocalNodeInfo` )
3. :heavy_check_mark: Just to mention, that `LocalNodeInfo` will miss pretty Location \ Region \ City attributes that set by inner ring nodes from locodes (they are available only in network map stored in netmap contract).
4. :x: Not sure about the filters, but it can print out container nodes from network map, built with the help of https://github.com/nspcc-dev/neofs-node/issues/94. I suggest to do that in separate issue.

**Comment by alexvanin** [comment]
Fixed in #145
