### ISSUE TITLE
Senseless keys in `neofs-cli accounting balance`

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-node#810]
There are keys available for `neofs-cli accounting balance` command:
```
$ neofs-cli accounting --help
Operations with accounts and balances

Usage:
  neofs-cli accounting [command]

Available Commands:
  balance     Get internal balance of NeoFS account

Flags:
  -h, --help   help for accounting

Global Flags:
      --address string        address of wallet account
      --binary-key string     path to the raw private key file
  -c, --config string         config file (default is $HOME/.config/neofs-cli/config.yaml)
      --generate-key          generate new private key
  -r, --rpc-endpoint string   remote node address (as 'multiaddr' or '<host>:<port>')
      --ttl uint32            TTL value in request meta header (default 2)
  -v, --verbose               verbose output
  -w, --wallet string         path to the wallet
      --wif string            WIF or NEP-2
  -x, --xhdr strings          Request X-Headers in form of Key=Value
```
The global flags `--xhdr` and `--ttl` aren't applicable to the balance request: we cannot specify X-Headers for accounts, and setting of TTL to any value will not affect the response.
I believe these flags confuses a user, and my proposal is to get rid of them for `accounting balance`. 
What do you think?

**Comment by aprasolova** [comment]
The same issue with `--generate-key` flag. It doesn't work when no RPC node specified
```
$ neofs-cli accounting balance  --generate-key
provided RPC endpoint is incorrect
```
And there is no sense to request balance for a key that has just been generated (of course, it's zero)
```
$ neofs-cli accounting balance -r s01.neofs.devenv:8080  --generate-key
0.00000000
```

**Comment by alexvanin** [comment]
After internal discussion, we have decided that NeoFS CLI application should be focused on user experience and use-cases instead of the pure protocol support. This means that commands should define only usable flags.

First step to do this: 
- [ ] remove global flags from application root
- [ ] use global flags as regular in all child commands
- [ ] keep only wallet related flags for `accounting balance` command.

**Comment by carpawell** [comment]
@anatoly-bogatyrev, @aprasolova, @EliChin all global flags(except `config`) have been deleted in #854, `accounting balance` does not have `ttl`, `generate-key` and `xhdr` flags anymore

please, open a new issue if you meet any other flags that are senseless in the context of some cli command
