### ISSUE TITLE
Sticky bit might violate basic ACL policy

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#818]
*Not verified*

It seems that sticky bit affects basic ACL policy that allows `SYSTEM` request senders to put objects (replication mechanism). 

https://github.com/nspcc-dev/neofs-node/blob/41a30d6ec298d8f2dc5dc53a487d872b55282ba7/pkg/services/object/acl/acl.go#L401-L402

Seems like `stickyBitCheck` returns false on objects replicated in such container and it fails basic ACL check.

/cc @realloc @carpawell @cthulhu-rider

**Comment by realloc** [comment]
Yes, the Role check may be needed to fit the spec requirements.

**Comment by cthulhu-rider** [comment]
Current specification does not cover described case:
```
X 	Sticky 	Flag denying different owners of the request and the object
		If set, object in Put request must have one Owner and be signed with the same signature
```
@realloc will add an edit based on which we can roll out the fix.
