### ISSUE TITLE
Reconsider storage node healthcheck mechanism

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#830]
Storage nodes send bootstrap request once per couple of epochs. Due to https://github.com/nspcc-dev/neofs-node/issues/750 these bootstrap requests will produce fallback transactions, which are totally unnecessary.

**Comment by cthulhu-rider** [comment]
Maybe related to netmap local view?

IR modifies source TX, so user TX doesn't exec. Solution?

Postpone to notary  only?

**Comment by roman-khimov** [comment]
@carpawell, can you please remind me if we're still rewriting the original transaction in the handler?

**Comment by carpawell** [comment]
@roman-khimov, hmmm, it seems like we are still dropping the original TX and [creating](https://github.com/nspcc-dev/neofs-node/blob/df2cc08a08191ce0f6ff84f36c393ed9b26f20da/pkg/innerring/processors/netmap/process_peers.go#L74-L80) a new one with the alphabet witness only. Moreover, we still have method [duplication](https://github.com/nspcc-dev/neofs-contract/blob/9dcf82fc4045b959181e1bb509a8dff31725e5a0/contracts/netmap/contract.go#L255-L290) that adapted contracts to the previous bootstraps.
So we have done some optimizations with overwriting original TXs but have not fixed other kludges.
