### ISSUE TITLE
Split object assembly moved to a container nodes (again)

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#838]
Some time ago we decided that nodes which process request, should assemble split objects. There was a config flag to disable forced assembly policy on the node (right now flag is hardcoded).

```
User <--> [Personal node] <---> [ Container Node, ..., Container Node ]
            Assembles
            Split
            Object
```

This was achieved by sending **new** object get requests with RAW flag set. Container nodes return `SplitInfoError` and personal node is able to build a chain of object and assemble split object.

This has changed with introduction of request forwarder in object service. Now node does not produce new requests if it is not necessary. In described case, personal node re-signs original request and sends it to container nodes. Container nodes that store last object in the chain or linking object are able to build the chain themself and they do assemble required object.

Technically it is totally correct, however it goes against earlier decision to assemble objects on the non container nodes.

/cc @cthulhu-rider @carpawell @realloc @fyrchik

**Comment by cthulhu-rider** [comment]
Need to explore current implementation.

**Comment by roman-khimov** [comment]
Not an issue. Non-container node can't really access container objects.
