### ISSUE TITLE
Storage node maintenance mode

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#922]
Maintenance mode is the storage node mode when it does not process any requests, but remaining active in network map. During this mode user can reconfigure storage engine, evacuate data, etc.
Maintenance mode is not the status announced in network map mode like `online` or `offline`.

In maintenance mode Storage node:
- returns error on all API requests,
- flushes all data from write cache to the blobstor.

To activate maintenance mode, use control service `set-status` command.

**Comment by cthulhu-rider** [comment]
Caller should remember the previous status himself to exit the maintenance mode.
