### ISSUE TITLE
Transform base64 encoded `NodeInfo` structure to JSON

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#94]
Network map is stored in blockchain as a array of binary encoded `NodeInfo` structures. Neo-go can invoke `Netmap()` method to return these structures. On top of that we can build whole network map structure represented in JSON. 

To do that we should be able to convert base64 encoded `NodeInfo` into JSON. CLI can work as a unix filter: 
```
echo "RXhhbXBsZQ==" | neofs-cli decode node-info | jq
```

**Comment by realloc** [comment]
Related: #168

**Comment by alexvanin** [comment]
Closed because #168 will return JSON formatted netmap via node's control API.
