### ISSUE TITLE
neofs-cli archived

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#956]
Please add an explanation why https://github.com/nspcc-dev/neofs-cli has been archived and where should I go.

**Comment by alexvanin** [comment]
nspcc-dev/neofs-cli repository was maintained before neofs-node was open sourced. After that neofs-cli became a part of neofs-node mono repository to keep synchronization with node features and node releases. Separate repository was archived, as you see. Issues related to neofs-cli belong here.

**Comment by alexvanin** [comment]
I am not sure where this explanation should be added. Maybe add faq.md.

**Comment by 532910** [comment]
In the About section, and possibly on the top of README.md

**Comment by 532910** [comment]
There should a link to the actual repo.

**Comment by alexvanin** [comment]
Done https://github.com/nspcc-dev/neofs-cli/commit/62b6011d86367a21f1c992d081295aaf7e1a24b7

**Comment by 532910** [comment]
What about **About** update?
