### ISSUE TITLE
could not open BoltDB: timeout

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#959]
```
$ sudo ./neofs-cli util locode info --db /usr/local/lib/locode_db-v0.1.0 --locode 'RU VAO'
could not open BoltDB: timeout
```

**Comment by 532910** [comment]
locode_db-v0.2.1 gives the same result

**Comment by cthulhu-rider** [comment]
Expected if some process opened the database file for writing or system resources were not freed after using it. @532910 is it possible to reproduce the erroneous output and see which process and how opened the file (e.g. `lsof  <path>`)?

**Comment by 532910** [comment]
yep, it's in use by two neofs net monitors

**Comment by cthulhu-rider** [comment]
Then https://github.com/nspcc-dev/neofs-node/pull/960 is expected to fix it too.
