### ISSUE TITLE
Implement neofs-adm tests on CI

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#967]
There are things we could check automatically:
1. Deploy latest version of contract with the latest version of neofs-adm.
2. Deploy previous version of contracts with the previous neofs-adm version and update to the latest version.

Later a test for dump generation can also be added, see #722 .
@alexvanin @anatoly-bogatyrev

**Comment by alexvanin** [comment]
I guess there is nothing to be done from neofs-adm side. It will be nice to have such job in CI.
